export const csSidebar = [
    {
        text: '计算机网络',
        link: '/cs/network/',
        items: [
            {
                text: '网络基础',
                link: '/cs/network/basic/',
                collapsed: true,
                items: [
                    { text: 'OSI 与 TCP/IP 模型', link: '/cs/network/basic/osi-tcpip' },
                    { text: '常见端口号与协议对应关系', link: '/cs/network/basic/port-protocol' },
                    { text: 'URI、URL、URN 的区别', link: '/cs/network/basic/uri-url-urn' },
                ],
            },
            {
                text: '物理层与数据链路层',
                link: '/cs/network/physical-datalink/',
                collapsed: true,
                items: [
                    { text: '以太网、ARP 协议、MAC 地址', link: '/cs/network/physical-datalink/ethernet-arp' },
                    { text: '交换机与 VLAN', link: '/cs/network/physical-datalink/switch-vlan' },
                ],
            },
            {
                text: '网络层',
                link: '/cs/network/network-layer/',
                collapsed: true,
                items: [
                    { text: 'IP 地址分类与子网掩码', link: '/cs/network/network-layer/ip-subnet' },
                    { text: 'IPv4 与 IPv6 对比', link: '/cs/network/network-layer/ipv4-ipv6' },
                    { text: 'ping 与 traceroute', link: '/cs/network/network-layer/icmp' },
                    { text: '路由与路由算法', link: '/cs/network/network-layer/routing' },
                    { text: 'NAT 机制与内网穿透', link: '/cs/network/network-layer/nat' },
                ],
            },
            {
                text: '传输层',
                link: '/cs/network/transport-layer/',
                collapsed: true,
                items: [
                    { text: 'TCP 三次握手', link: '/cs/network/transport-layer/tcp-three-handshake' },
                    { text: 'TCP 四次挥手', link: '/cs/network/transport-layer/tcp-four-wave' },
                    { text: '为什么是三次握手', link: '/cs/network/transport-layer/tcp-handshake-why' },
                    { text: '为什么是四次挥手', link: '/cs/network/transport-layer/tcp-wave-why' },
                    { text: 'TCP 状态转换图', link: '/cs/network/transport-layer/tcp-state' },
                    { text: 'TCP 可靠性保证', link: '/cs/network/transport-layer/tcp-reliability' },
                    { text: 'TCP 滑动窗口与流量控制', link: '/cs/network/transport-layer/tcp-window' },
                    { text: 'TCP 拥塞控制', link: '/cs/network/transport-layer/tcp-congestion' },
                    { text: 'TCP 与 UDP 对比与适用场景', link: '/cs/network/transport-layer/tcp-vs-udp' },
                    { text: 'UDP 报文结构与特点', link: '/cs/network/transport-layer/udp' },
                    { text: 'QUIC 协议：HTTP/3 底层协议', link: '/cs/network/transport-layer/quic' },
                ],
            },
            {
                text: '应用层',
                link: '/cs/network/application-layer/',
                collapsed: true,
                items: [
                    { text: 'HTTP 请求与响应', link: '/cs/network/application-layer/http-structure' },
                    { text: 'HTTP 方法对比', link: '/cs/network/application-layer/http-method' },
                    { text: 'HTTP 状态码', link: '/cs/network/application-layer/http-status' },
                    { text: 'HTTP 版本演进', link: '/cs/network/application-layer/http-version' },
                    { text: 'HTTP/2 特性', link: '/cs/network/application-layer/http2' },
                    { text: 'HTTP/3：QUIC 替代 TCP', link: '/cs/network/application-layer/http3' },
                    { text: 'HTTPS 加密原理', link: '/cs/network/application-layer/https-tls' },
                    { text: '数字证书与 CA 认证', link: '/cs/network/application-layer/digital-certificate' },
                    { text: 'DNS 解析流程', link: '/cs/network/application-layer/dns' },
                    { text: 'DNS 记录类型', link: '/cs/network/application-layer/dns-record' },
                    { text: 'CDN 原理与缓存策略', link: '/cs/network/application-layer/cdn' },
                    { text: 'WebSocket：全双工通信原理', link: '/cs/network/application-layer/websocket' },
                    { text: 'SMTP、POP3、IMAP 邮件协议', link: '/cs/network/application-layer/email-protocol' },
                    { text: 'FTP 协议工作原理', link: '/cs/network/application-layer/ftp' },
                    { text: 'SSH 远程登录原理', link: '/cs/network/application-layer/ssh' },
                ],
            }
        ],
    },
    {
        text: '操作系统',
        link: '/cs/os/',
        items: [
            {
                text: '进程与线程',
                link: '/cs/os/process-thread/',
                collapsed: true,
                items: [
                    { text: '进程、线程、协程的区别', link: '/cs/os/process-thread/diff' },
                    { text: '进程状态转换与 PCB', link: '/cs/os/process-thread/process-state' },
                    { text: '进程调度算法', link: '/cs/os/process-thread/scheduling-algorithm' },
                    { text: '多级反馈队列调度算法', link: '/cs/os/process-thread/mlfq' },
                    { text: '进程间通信', link: '/cs/os/process-thread/ipc' },
                    { text: '线程同步机制', link: '/cs/os/process-thread/thread-sync' },
                    { text: '进程同步与互斥', link: '/cs/os/process-thread/process-sync' },
                    { text: '死锁：条件与处理', link: '/cs/os/process-thread/deadlock' },
                ],
            },
            {
                text: '内存管理',
                link: '/cs/os/memory/',
                collapsed: true,
                items: [
                    { text: '内存管理机制', link: '/cs/os/memory/memory-management' },
                    { text: '分页机制与页表结构', link: '/cs/os/memory/paging' },
                    { text: '分段机制与段页式管理', link: '/cs/os/memory/segmentation' },
                    { text: '页面置换算法', link: '/cs/os/memory/page-replacement' },
                    { text: '局部性原理与抖动', link: '/cs/os/memory/locality-thrashing' },
                    { text: '虚拟内存与请求分页', link: '/cs/os/memory/virtual-memory' },
                ],
            },
            {
                text: '文件系统',
                link: '/cs/os/file-system/',
                collapsed: true,
                items: [
                    { text: '文件系统结构', link: '/cs/os/file-system/fs-structure' },
                    { text: '文件分配方式', link: '/cs/os/file-system/file-allocation' },
                    { text: '目录实现与文件系统一致性', link: '/cs/os/file-system/directory' },
                    { text: '磁盘调度算法', link: '/cs/os/file-system/disk-scheduling' },
                ],
            },
            {
                text: '操作系统原理',
                link: '/cs/os/principle/',
                collapsed: true,
                items: [
                    { text: '内核态 vs 用户态与系统调用', link: '/cs/os/principle/kernel-user-mode' },
                    { text: '中断与异常处理机制', link: '/cs/os/principle/interrupt' },
                    { text: 'I/O 控制与 DMA', link: '/cs/os/principle/io-management' },
                    { text: '死锁处理策略详解', link: '/cs/os/principle/deadlock-strategy' },
                ],
            },
            {
                text: 'Linux',
                link: '/cs/os/linux/',
                collapsed: true,
                items: [
                    { text: 'Linux 进程与线程管理', link: '/cs/os/linux/linux-process' },
                    { text: 'Linux 内存管理', link: '/cs/os/linux/linux-memory' },
                    { text: 'Linux 文件系统', link: '/cs/os/linux/linux-filesystem' },
                    { text: 'Linux 网络协议栈', link: '/cs/os/linux/linux-network' },
                    { text: 'Linux 常用命令与 Shell 脚本', link: '/cs/os/linux/linux-command' },
                    { text: 'Linux 性能分析', link: '/cs/os/linux/linux-performance' },
                ],
            },
            { text: '操作系统面试高频问题汇总', link: '/cs/os/interview-summary' },
        ],
    },
    {
        text: '网络安全',
        link: '/cs/security/',
        items: [
            {
                text: '密码学基础',
                link: '/cs/security/cryptography/',
                collapsed: true,
                items: [
                    { text: '对称加密算法', link: '/cs/security/cryptography/symmetric-encryption' },
                    { text: '非对称加密：RSA、ECC、SM2', link: '/cs/security/cryptography/asymmetric-encryption' },
                    { text: '混合加密原理', link: '/cs/security/cryptography/hybrid-encryption' },
                    { text: '消息摘要算法', link: '/cs/security/cryptography/hash' },
                    { text: '数字签名与 PKI', link: '/cs/security/cryptography/digital-signature' },
                    { text: '密钥交换协议', link: '/cs/security/cryptography/key-exchange' },
                    { text: '国密算法：SM2/SM3/SM4 系列', link: '/cs/security/cryptography/national-secret' },
                ],
            },
            {
                text: '身份认证与授权',
                link: '/cs/security/auth/',
                collapsed: true,
                items: [
                    { text: '身份认证方式', link: '/cs/security/auth/authentication' },
                    { text: 'OAuth 2.0 授权', link: '/cs/security/auth/oauth2' },
                    { text: 'OIDC 身份认证', link: '/cs/security/auth/oidc' },
                    { text: 'SSO 单点登录', link: '/cs/security/auth/sso' },
                    { text: 'RBAC 权限模型', link: '/cs/security/auth/rbac' },
                    { text: 'LDAP 统一认证', link: '/cs/security/auth/ldap' },
                    { text: '零信任架构', link: '/cs/security/auth/zero-trust' },
                ],
            },
            {
                text: '应用层安全',
                link: '/cs/security/application/',
                collapsed: true,
                items: [
                    { text: 'XSS 跨站脚本', link: '/cs/security/application/xss' },
                    { text: 'CSRF 跨站请求伪造', link: '/cs/security/application/csrf' },
                    { text: 'SQL 注入', link: '/cs/security/application/sql-injection' },
                    { text: 'SSRF 服务端请求伪造攻击', link: '/cs/security/application/ssrf' },
                    { text: '文件上传漏洞与防护策略', link: '/cs/security/application/file-upload' },
                    { text: '命令注入', link: '/cs/security/application/code-injection' },
                    { text: '反序列化漏洞', link: '/cs/security/application/deserialization' },
                    { text: '越权漏洞', link: '/cs/security/application/idor' },
                    { text: '路径遍历与文件包含漏洞', link: '/cs/security/application/path-traversal' },
                    { text: 'WAF 原理与绕过', link: '/cs/security/application/waf' },
                ],
            },
            {
                text: '网络层安全',
                link: '/cs/security/network/',
                collapsed: true,
                items: [
                    { text: 'TLS/SSL 协议', link: '/cs/security/network/tls' },
                    { text: 'HTTPS 证书', link: '/cs/security/network/https' },
                    { text: 'DNS 安全方案', link: '/cs/security/network/dns-security' },
                    { text: 'ARP 欺骗与 MITM', link: '/cs/security/network/arp-spoofing' },
                    { text: 'DDoS 攻击与防御', link: '/cs/security/network/dos-ddos' },
                    { text: 'IPsec VPN', link: '/cs/security/network/ipsec' },
                    { text: 'VPN 技术', link: '/cs/security/network/vpn' },
                    { text: '防火墙技术', link: '/cs/security/network/firewall' },
                    { text: 'IDS 与 IPS', link: '/cs/security/network/ids-ips' },
                ],
            },
            {
                text: '系统层安全',
                link: '/cs/security/system/',
                collapsed: true,
                items: [
                    { text: '缓冲区溢出', link: '/cs/security/system/buffer-overflow' },
                    { text: 'ROP 攻击与返回导向编程', link: '/cs/security/system/rop' },
                    { text: '权限提升漏洞', link: '/cs/security/system/privilege-escalation' },
                    { text: '后门与 Rootkit 原理', link: '/cs/security/system/backdoor' },
                    { text: '安全沙箱与容器隔离机制', link: '/cs/security/system/sandbox' },
                    { text: 'SELinux 与 AppArmor', link: '/cs/security/system/selinux' },
                ],
            },
            {
                text: '安全运维',
                link: '/cs/security/devops/',
                collapsed: true,
                items: [
                    { text: '渗透测试方法', link: '/cs/security/devops/pentest' },
                    { text: '漏洞扫描工具', link: '/cs/security/devops/vulnerability-scan' },
                    { text: '代码审计', link: '/cs/security/devops/code-audit' },
                    { text: '日志安全分析', link: '/cs/security/devops/siem' },
                    { text: '应急响应流程', link: '/cs/security/devops/incident-response' },
                    { text: '等保合规要求', link: '/cs/security/devops/compliance' },
                ],
            },
            { text: '计算机安全面试高频问题汇总', link: '/cs/security/interview-summary' },
        ],
    },
    {
        text: '数据结构与算法',
        link: '/cs/algorithm/',
        items: [
            {
                text: '基础数据结构',
                link: '/cs/algorithm/basic/',
                collapsed: true,
                items: [
                    { text: '数组与链表：原理与对比', link: '/cs/algorithm/basic/array-linkedlist' },
                    { text: '栈与队列：实现与应用场景', link: '/cs/algorithm/basic/stack-queue' },
                    { text: '哈希表：散列函数与冲突解决', link: '/cs/algorithm/basic/hash-table' },
                    { text: '字符串匹配算法', link: '/cs/algorithm/basic/string-match' },
                ],
            },
            {
                text: '树结构',
                link: '/cs/algorithm/tree/',
                collapsed: true,
                items: [
                    { text: '二叉树：遍历方式与性质', link: '/cs/algorithm/tree/binary-tree' },
                    { text: '二叉查找树', link: '/cs/algorithm/tree/bst' },
                    { text: 'AVL 树：平衡条件与旋转操作', link: '/cs/algorithm/tree/avl-tree' },
                    { text: '红黑树：五大性质与插入修复', link: '/cs/algorithm/tree/red-black-tree' },
                    { text: 'B 树与 B+ 树：数据库索引核心', link: '/cs/algorithm/tree/b-plus-tree' },
                    { text: 'Trie 树（前缀树）：字符串检索', link: '/cs/algorithm/tree/trie-tree' },
                    { text: '哈夫曼树与哈夫曼编码', link: '/cs/algorithm/tree/huffman-tree' },
                ],
            },
            {
                text: '图结构',
                link: '/cs/algorithm/graph/',
                collapsed: true,
                items: [
                    { text: '图的表示：邻接矩阵 vs 邻接表', link: '/cs/algorithm/graph/graph-representation' },
                    { text: '图的遍历：DFS 与 BFS', link: '/cs/algorithm/graph/graph-traversal' },
                    { text: '最短路径算法', link: '/cs/algorithm/graph/shortest-path' },
                    { text: '最小生成树：Prim 与 Kruskal', link: '/cs/algorithm/graph/mst' },
                    { text: '拓扑排序与关键路径', link: '/cs/algorithm/graph/topological-sort' },
                    { text: '并查集：合并与查找', link: '/cs/algorithm/graph/union-find' },
                ],
            },
            {
                text: '算法思想',
                link: '/cs/algorithm/thinking/',
                collapsed: true,
                items: [
                    { text: '递归与分治：汉诺塔与归并排序', link: '/cs/algorithm/thinking/recursion-divide' },
                    { text: '回溯算法：八皇后与全排列', link: '/cs/algorithm/thinking/backtracking' },
                    { text: '贪心算法', link: '/cs/algorithm/thinking/greedy' },
                    { text: '动态规划', link: '/cs/algorithm/thinking/dynamic-programming' },
                    { text: '动态规划经典问题', link: '/cs/algorithm/thinking/dp-classic' },
                    { text: '位运算：常用技巧与实战', link: '/cs/algorithm/thinking/bit-operation' },
                ],
            },
            {
                text: '查找与排序',
                link: '/cs/algorithm/search-sort/',
                collapsed: true,
                items: [
                    { text: '排序算法总览', link: '/cs/algorithm/search-sort/sort-overview' },
                    { text: 'O(n²) 排序算法', link: '/cs/algorithm/search-sort/sort-o-n2' },
                    { text: 'O(n log n) 排序', link: '/cs/algorithm/search-sort/sort-o-nlogn' },
                    { text: '计数排序与桶排序', link: '/cs/algorithm/search-sort/sort-linear' },
                    { text: '二分查找及其变体', link: '/cs/algorithm/search-sort/binary-search' },
                    { text: '海量数据处理', link: '/cs/algorithm/search-sort/mass-data' },
                ],
            },
            { text: '算法高频面试题汇总', link: '/cs/algorithm/interview-summary' },
        ],
    }
]
