export const csSidebar = [
    {
        text: "计算机网络",
        link: "/cs/network/",
        items: [
            { text: "OSI七层模型与TCP/IP四层模型", link: "/cs/network/osi-tcpip" },
            { text: "TCP三次握手与四次挥手", link: "/cs/network/tcp-handshake" },
            { text: "TCP可靠传输机制（确认/重传/校验）", link: "/cs/network/tcp-reliability" },
            { text: "流量控制与拥塞控制", link: "/cs/network/flow-congestion" },
            { text: "TCP与UDP对比及场景选型", link: "/cs/network/tcp-vs-udp" },
            { text: "HTTP/1.1 特性与瓶颈", link: "/cs/network/http1" },
            { text: "HTTP/2 多路复用与头部压缩", link: "/cs/network/http2" },
            { text: "HTTP/3 QUIC协议", link: "/cs/network/http3" },
            { text: "HTTPS加密过程（TLS/SSL）", link: "/cs/network/https" },
            { text: "Session与Cookie区别", link: "/cs/network/session-cookie" },
            { text: "常见状态码", link: "/cs/network/status-code" },
            { text: "DNS解析流程", link: "/cs/network/dns" },
            { text: "CDN原理与架构", link: "/cs/network/cdn" },
        ],
    },
    {
        text: "操作系统",
        link: "/cs/os/",
        items: [
            { text: "进程与线程区别与联系", link: "/cs/os/process-thread" },
            { text: "协程与线程对比", link: "/cs/os/coroutine" },
            { text: "进程间通信方式", link: "/cs/os/ipc" },
            { text: "线程同步机制", link: "/cs/os/thread-sync" },
            { text: "用户态与内核态切换", link: "/cs/os/user-kernel" },
            { text: "虚拟内存与物理内存映射", link: "/cs/os/virtual-memory" },
            { text: "内存分页与分段", link: "/cs/os/paging-segmentation" },
            { text: "页面置换算法", link: "/cs/os/page-replacement" },
            { text: "死锁的四个必要条件", link: "/cs/os/deadlock" },
            { text: "死锁预防/避免/检测/恢复策略", link: "/cs/os/deadlock-solution" },
            { text: "银行家算法", link: "/cs/os/banker" },
            { text: "进程调度算法", link: "/cs/os/scheduling" },
            { text: "阻塞/非阻塞IO与同步/异步IO", link: "/cs/os/io-models" },
            { text: "select/poll/epoll 对比", link: "/cs/os/epoll" },
            { text: "零拷贝技术", link: "/cs/os/zero-copy" },
        ],
    },
    {
        text: "网络安全",
        link: "/cs/security/",
        items: [
            { text: "对称加密 vs 非对称加密", link: "/cs/security/symmetric-asymmetric" },
            { text: "常见加密算法", link: "/cs/security/encryption-algorithms" },
            { text: "哈希算法与应用场景", link: "/cs/security/hash" },
            { text: "数字签名与数字证书", link: "/cs/security/digital-signature" },
            { text: "TLS/SSL握手流程", link: "/cs/security/tls-handshake" },
            { text: "HTTPS与HTTP区别", link: "/cs/security/https-vs-http" },
            { text: "OAuth2.0授权流程", link: "/cs/security/oauth2" },
            { text: "JWT结构与使用场景", link: "/cs/security/jwt" },
            { text: "JWT与Session对比", link: "/cs/security/jwt-vs-session" },
            { text: "SQL注入原理与防护", link: "/cs/security/sql-injection" },
            { text: "XSS攻击与防护", link: "/cs/security/xss" },
            { text: "CSRF攻击与防护", link: "/cs/security/csrf" },
            { text: "DDOS攻击类型与防护", link: "/cs/security/ddos" },
        ],
    },
    {
        text: "数据结构与算法",
        link: "/cs/algorithm/",
        items: [
            { text: "数组 vs 链表", link: "/cs/algorithm/array-vs-linkedlist" },
            { text: "栈与队列实现及应用", link: "/cs/algorithm/stack-queue" },
            { text: "哈希表原理", link: "/cs/algorithm/hashmap" },
            { text: "二叉树遍历", link: "/cs/algorithm/tree-traversal" },
            { text: "二叉搜索树与平衡二叉树", link: "/cs/algorithm/bst-avl" },
            { text: "红黑树特性与原理", link: "/cs/algorithm/red-black-tree" },
            { text: "B树与B+树对比", link: "/cs/algorithm/btree-bplus" },
            { text: "冒泡/选择/插入排序", link: "/cs/algorithm/basic-sort" },
            { text: "快速排序", link: "/cs/algorithm/quick-sort" },
            { text: "归并排序", link: "/cs/algorithm/merge-sort" },
            { text: "堆排序与优先队列", link: "/cs/algorithm/heap-sort" },
            { text: "排序算法对比总结", link: "/cs/algorithm/sort-comparison" },
            { text: "二分查找", link: "/cs/algorithm/binary-search" },
            { text: "LRU缓存实现", link: "/cs/algorithm/lru-cache" },
            { text: "布隆过滤器原理与应用", link: "/cs/algorithm/bloom-filter" },
            { text: "动态规划经典问题", link: "/cs/algorithm/dp" },
            { text: "双指针技巧", link: "/cs/algorithm/two-pointer" },
            { text: "滑动窗口算法", link: "/cs/algorithm/sliding-window" },
            { text: "递归与迭代转换", link: "/cs/algorithm/recursion" },
        ],
    },
];