export const databaseSidebar = [
    {
        text: "MySQL",
        link: "/database/mysql/",
        items: [
            { text: "MySQL 架构（Server层/存储引擎层）", link: "/database/mysql/architecture" },
            { text: "InnoDB 与 MyISAM 对比", link: "/database/mysql/innodb-myisam" },
            { text: "B+Tree 索引原理", link: "/database/mysql/btree-index" },
            { text: "聚簇索引 vs 二级索引", link: "/database/mysql/clustered-secondary" },
            { text: "联合索引最左前缀原则", link: "/database/mysql/leftmost-prefix" },
            { text: "索引失效场景分析", link: "/database/mysql/index-invalidation" },
            { text: "覆盖索引与回表", link: "/database/mysql/covering-index" },
            { text: "索引下推（ICP）", link: "/database/mysql/index-condition-pushdown" },
            { text: "Explain 执行计划解读", link: "/database/mysql/explain" },
            { text: "慢查询日志与优化", link: "/database/mysql/slow-query" },
            { text: "事务四大特性（ACID）", link: "/database/mysql/acid" },
            { text: "四种隔离级别", link: "/database/mysql/isolation-levels" },
            { text: "MVCC 多版本并发控制", link: "/database/mysql/mvcc" },
            { text: "ReadView 可见性判断", link: "/database/mysql/readview" },
            { text: "当前读 vs 快照读", link: "/database/mysql/current-snapshot-read" },
            { text: "锁分类（行锁/表锁/间隙锁/临键锁）", link: "/database/mysql/locks" },
            { text: "间隙锁解决幻读", link: "/database/mysql/gap-lock" },
            { text: "死锁原因与排查", link: "/database/mysql/deadlock" },
            { text: "SQL 优化实战案例", link: "/database/mysql/sql-optimization" },
            { text: "主从复制原理", link: "/database/mysql/master-slave" },
            { text: "binlog 三种格式（STATEMENT/ROW/MIXED）", link: "/database/mysql/binlog" },
            { text: "读写分离架构", link: "/database/mysql/read-write-split" },
            { text: "分库分表策略", link: "/database/mysql/sharding" },
            { text: "分页查询优化", link: "/database/mysql/pagination" },
            { text: "count 查询优化", link: "/database/mysql/count-optimization" },
        ],
    },
    {
        text: "Redis",
        link: "/database/redis/",
        items: [
            { text: "Redis 数据结构（String/Hash/List/Set/ZSet）", link: "/database/redis/data-structures" },
            { text: "String 底层 SDS 原理", link: "/database/redis/sds" },
            { text: "ZSet 底层跳表原理", link: "/database/redis/skiplist" },
            { text: "Redis 线程模型（单线程/多线程）", link: "/database/redis/thread-model" },
            { text: "Redis 持久化 RDB vs AOF", link: "/database/redis/persistence" },
            { text: "混合持久化", link: "/database/redis/mixed-persistence" },
            { text: "缓存穿透与布隆过滤器", link: "/database/redis/cache-penetration" },
            { text: "缓存击穿与互斥锁", link: "/database/redis/cache-breakdown" },
            { text: "缓存雪崩与解决方案", link: "/database/redis/cache-avalanche" },
            { text: "缓存一致性（延迟双删）", link: "/database/redis/cache-consistency" },
            { text: "缓存淘汰策略（LRU/LFU/TTL）", link: "/database/redis/eviction" },
            { text: "Redis 分布式锁（SETNX + Lua）", link: "/database/redis/distributed-lock" },
            { text: "RedLock 算法与争议", link: "/database/redis/redlock" },
            { text: "Redis 主从复制", link: "/database/redis/master-slave" },
            { text: "Redis 哨兵机制", link: "/database/redis/sentinel" },
            { text: "Redis Cluster 集群", link: "/database/redis/cluster" },
            { text: "Redis 持久化对性能影响", link: "/database/redis/performance" },
            { text: "Redis 内存优化（压缩列表/整数集合）", link: "/database/redis/memory-optimization" },
            { text: "Redis 事务（MULTI/EXEC）", link: "/database/redis/transaction" },
            { text: "Redis 发布订阅", link: "/database/redis/pub-sub" },
            { text: "Redis 与 Memcached 对比", link: "/database/redis-vs-memcached" },
        ],
    },
    {
        text: "MongoDB",
        link: "/database/mongodb/",
        items: [
            { text: "MongoDB 文档模型设计", link: "/database/mongodb/document-model" },
            { text: "BSON 与 JSON 对比", link: "/database/mongodb/bson" },
            { text: "MongoDB 索引类型", link: "/database/mongodb/indexes" },
            { text: "聚合框架（Aggregation Pipeline）", link: "/database/mongodb/aggregation" },
            { text: "复制集（Replica Set）原理", link: "/database/mongodb/replica-set" },
            { text: "分片集群（Sharded Cluster）", link: "/database/mongodb/sharded-cluster" },
            { text: "分片键选择策略", link: "/database/mongodb/shard-key" },
            { text: "MongoDB 与 MySQL 对比", link: "/database/mongodb-vs-mysql" },
            { text: "MongoDB 适用场景", link: "/database/mongodb/scenarios" },
        ],
    },
    {
        text: "其他数据库",
        link: "/database/others/",
        items: [
            { text: "PostgreSQL 特性与 MySQL 对比", link: "/database/others/postgresql" },
            { text: "TiDB 分布式架构（Placement Driver/TiKV/TiDB）", link: "/database/others/tidb" },
            { text: "TiDB 与 MySQL 兼容性", link: "/database/others/tidb-compatibility" },
            { text: "达梦数据库（信创背景/Oracle兼容）", link: "/database/others/dameng" },
            { text: "GaussDB（华为生态/分布式）", link: "/database/others/gaussdb" },
            { text: "数据库选型决策矩阵", link: "/database/others/selection" },
        ],
    },
];