export const databaseSidebar = [
    {
        text: 'MySQL',
        link: '/database/mysql/',
        items: [
            {
                text: 'MySQL 基础',
                link: '/database/mysql/basic/',
                collapsed: true,
                items: [
                    { text: 'MySQL 整体架构：连接层、服务层、存储引擎层', link: '/database/mysql/basic/architecture' },
                    { text: 'MySQL 存储引擎对比：InnoDB vs MyISAM vs Memory', link: '/database/mysql/basic/engine-compare' },
                    { text: 'InnoDB 存储引擎特性详解', link: '/database/mysql/basic/innodb' },
                    { text: 'MySQL 数据类型选择与优化', link: '/database/mysql/basic/data-type' },
                    { text: 'SQL 执行过程：从客户端到结果返回', link: '/database/mysql/basic/sql-execution' },
                ],
            },
            {
                text: '索引与数据结构',
                link: '/database/mysql/index/',
                collapsed: true,
                items: [
                    { text: 'MySQL 索引体系：B+ 树索引、Hash 索引、全文索引、空间索引', link: '/database/mysql/index/index-type' },
                    { text: 'B+ 树索引结构与查询原理', link: '/database/mysql/index/btree-index' },
                    { text: 'B+ 树 vs B 树 vs 红黑树 vs 哈希表', link: '/database/mysql/index/index-structure-compare' },
                    { text: '聚簇索引 vs 非聚簇索引（二级索引）', link: '/database/mysql/index/clustered-index' },
                    { text: '回表查询与覆盖索引', link: '/database/mysql/index/covering-index' },
                    { text: '联合索引与最左前缀原则', link: '/database/mysql/index/composite-index' },
                    { text: '索引下推（Index Condition Pushdown）', link: '/database/mysql/index/index-pushdown' },
                    { text: '索引失效的 11 种情况', link: '/database/mysql/index/index-invalid' },
                    { text: '索引创建原则与使用注意事项', link: '/database/mysql/index/index-design' },
                    { text: '自适应哈希索引（Adaptive Hash Index）', link: '/database/mysql/index/ahi' },
                    { text: 'MRR（Multi-Range Read）优化', link: '/database/mysql/index/mrr' },
                ],
            },
            {
                text: '事务与隔离级别',
                link: '/database/mysql/transaction/',
                collapsed: true,
                items: [
                    { text: '事务的 ACID 特性与实现原理', link: '/database/mysql/transaction/acid' },
                    { text: '并发事务问题：脏读、不可重复读、幻读', link: '/database/mysql/transaction/transaction-problem' },
                    { text: '四种隔离级别：Read Uncommitted ~ Serializable', link: '/database/mysql/transaction/isolation-level' },
                    { text: 'MVCC 原理：ReadView 与版本链', link: '/database/mysql/transaction/mvcc' },
                    { text: 'MVCC 在 RC 和 RR 级别下的差异', link: '/database/mysql/transaction/mvcc-rc-rr' },
                    { text: '当前读与快照读', link: '/database/mysql/transaction/current-snapshot-read' },
                    { text: 'ReadView 生成时机与隐含条件', link: '/database/mysql/transaction/readview' },
                ],
            },
            {
                text: '锁机制',
                link: '/database/mysql/lock/',
                collapsed: true,
                items: [
                    { text: '全局锁与表级锁：MDL 锁', link: '/database/mysql/lock/table-lock' },
                    { text: '行锁与 Next-Key Lock：记录锁、间隙锁、临键锁', link: '/database/mysql/lock/row-lock' },
                    { text: '意向锁：IX 与 IS', link: '/database/mysql/lock/intention-lock' },
                    { text: '两阶段锁协议与死锁避免', link: '/database/mysql/lock/two-phase-lock' },
                    { text: '死锁产生条件与处理策略', link: '/database/mysql/lock/deadlock' },
                    { text: '乐观锁与悲观锁实现', link: '/database/mysql/lock/optimistic-pessimistic-lock' },
                ],
            },
            {
                text: 'SQL 优化',
                link: '/database/mysql/sql-optimize/',
                collapsed: true,
                items: [
                    { text: '慢查询定位：slow_query_log 与 long_query_time', link: '/database/mysql/sql-optimize/slow-query' },
                    { text: 'EXPLAIN 执行计划详解：type、key、Extra 字段', link: '/database/mysql/sql-optimize/explain' },
                    { text: 'Using filesort 与 Using temporary 优化', link: '/database/mysql/sql-optimize/filesort-temporary' },
                    { text: 'JOIN 原理与嵌套循环连接（NLJ）', link: '/database/mysql/sql-optimize/join-principle' },
                    { text: 'JOIN 优化：基于规则的优化与成本优化', link: '/database/mysql/sql-optimize/join-optimize' },
                    { text: '子查询分类与优化', link: '/database/mysql/sql-optimize/subquery' },
                    { text: '分页查询优化：延迟关联与游标分页', link: '/database/mysql/sql-optimize/pagination' },
                    { text: 'COUNT(*) vs COUNT(1) vs COUNT(column) 性能对比', link: '/database/mysql/sql-optimize/count-performance' },
                    { text: 'INSERT、UPDATE、DELETE 优化', link: '/database/mysql/sql-optimize/dml-optimize' },
                    { text: 'ORDER BY 排序优化：索引覆盖与 filesort', link: '/database/mysql/sql-optimize/orderby-optimize' },
                    { text: 'GROUP BY 优化：松散索引扫描 vs 紧凑索引扫描', link: '/database/mysql/sql-optimize/groupby-optimize' },
                ],
            },
            {
                text: '数据库架构',
                link: '/database/mysql/architecture/',
                collapsed: true,
                items: [
                    { text: '主从复制原理：binlog、relaylog、IO 线程、SQL 线程', link: '/database/mysql/architecture/replication' },
                    { text: '主从复制模式：异步复制、半同步复制、全同步复制', link: '/database/mysql/architecture/replication-mode' },
                    { text: '主从延迟原因与解决方案', link: '/database/mysql/architecture/replication-lag' },
                    { text: '读写分离架构与数据一致性', link: '/database/mysql/architecture/read-write-separation' },
                    { text: 'MySQL 高可用方案：主备切换、MGR、MHA、Galera', link: '/database/mysql/architecture/ha-solution' },
                    { text: '分库分表：垂直拆分与水平拆分', link: '/database/mysql/architecture/sharding' },
                    { text: '分片键选择与分片算法（取模、范围、哈希）', link: '/database/mysql/architecture/sharding-algorithm' },
                    { text: '分库分表后的跨节点查询与分布式事务', link: '/database/mysql/architecture/sharding-query' },
                    { text: 'ShardingSphere 实战', link: '/database/mysql/architecture/shardingsphere' },
                    { text: 'MySQL 三大日志：binlog、redo log、undo log', link: '/database/mysql/architecture/mysql-logs' },
                    { text: 'redo log 两阶段提交与崩溃恢复', link: '/database/mysql/architecture/redolog-commit' },
                ],
            },
            {
                text: '数据库设计',
                link: '/database/mysql/schema/',
                collapsed: true,
                items: [
                    { text: '数据库设计三范式与反范式设计', link: '/database/mysql/schema/nf-design' },
                    { text: '大表优化：分库分表、分区表、历史数据归档', link: '/database/mysql/schema/big-table' },
                    { text: '表结构设计优化：字段类型、冗余字段、拆分字段', link: '/database/mysql/schema/schema-optimize' },
                ],
            },
            { text: 'MySQL 面试高频问题汇总', link: '/database/mysql/interview-summary' },
        ],
    },
    {
        text: 'Redis',
        link: '/database/redis/',
        items: [
            {
                text: 'Redis 基础',
                link: '/database/redis/basic/',
                collapsed: true,
                items: [
                    { text: 'Redis 为什么要用单线程？', link: '/database/redis/basic/why-single-thread' },
                    { text: 'Redis 6.0 之后的多线程：I/O 多路复用与命令执行', link: '/database/redis/basic/multi-thread' },
                    { text: 'Redis 数据类型：String、Hash、List、Set、ZSet', link: '/database/redis/basic/data-type' },
                    { text: 'Redis 对象系统：SDS、ziplist、quicklist、intset、dict', link: '/database/redis/basic/object-system' },
                    { text: 'Redis 跳跃表（ZSet 底层实现）', link: '/database/redis/basic/skiplist' },
                    { text: 'RedisHyperLogLog、Bitmap、GIS 模块', link: '/database/redis/basic/bitmap-hll' },
                ],
            },
            {
                text: '持久化机制',
                link: '/database/redis/persistence/',
                collapsed: true,
                items: [
                    { text: 'RDB：快照持久化原理与配置', link: '/database/redis/persistence/rdb' },
                    { text: 'AOF：追加文件持久化原理与模式', link: '/database/redis/persistence/aof' },
                    { text: 'AOF 重写机制与 Rewrite', link: '/database/redis/persistence/aof-rewrite' },
                    { text: 'RDB vs AOF 对比与混合持久化', link: '/database/redis/persistence/rdb-aof-compare' },
                    { text: '数据恢复流程与优先顺序', link: '/database/redis/persistence/data-recovery' },
                ],
            },
            {
                text: '集群与高可用',
                link: '/database/redis/cluster/',
                collapsed: true,
                items: [
                    { text: '主从复制原理：全量同步（SYNC）与增量同步（PSYNC）', link: '/database/redis/cluster/replication' },
                    { text: '主从复制风暴与优化', link: '/database/redis/cluster/replication-storm' },
                    { text: '哨兵（Sentinel）机制：故障检测与自动切换', link: '/database/redis/cluster/sentinel' },
                    { text: 'Redis Cluster：槽分片与集群通信', link: '/database/redis/cluster/cluster' },
                    { text: 'Redis Cluster 故障转移与槽迁移', link: '/database/redis/cluster/cluster-failover' },
                    { text: 'Redis Cluster vs Codis vs Twemproxy vs 主从+哨兵对比', link: '/database/redis/cluster/cluster-compare' },
                    { text: 'Redis 脑裂问题与解决方案', link: '/database/redis/cluster/split-brain' },
                ],
            },
            {
                text: '缓存策略',
                link: '/database/redis/cache/',
                collapsed: true,
                items: [
                    { text: '缓存穿透：布隆过滤器 + 缓存空值', link: '/database/redis/cache/cache-penetration' },
                    { text: '缓存击穿：互斥锁 + 逻辑过期双检', link: '/database/redis/cache/cache-breakdown' },
                    { text: '缓存雪崩：过期时间随机化 + 多级缓存', link: '/database/redis/cache/cache-avalanche' },
                    { text: '缓存与数据库双写一致性', link: '/database/redis/cache/cache-consistency' },
                    { text: 'Cache Aside vs Read/Write Through vs Write Behind', link: '/database/redis/cache/cache-pattern' },
                    { text: '热点数据发现与处理', link: '/database/redis/cache/hot-key' },
                    { text: '大 key 发现与解决方案', link: '/database/redis/cache/big-key' },
                    { text: 'Redis 分布式锁：SETNX + Lua + Redisson', link: '/database/redis/cache/distributed-lock' },
                    { text: 'RedLock 算法与分布式锁安全性', link: '/database/redis/cache/redlock' },
                ],
            },
            {
                text: 'Redis 高级特性',
                link: '/database/redis/advanced/',
                collapsed: true,
                items: [
                    { text: 'I/O 模型：epoll 原理与事件循环', link: '/database/redis/advanced/io-model' },
                    { text: 'Redis 淘汰策略：noeviction ~ allkeys-lru', link: '/database/redis/advanced/eviction-policy' },
                    { text: 'LRU 算法实现：近似 LRU vs 精确 LRU', link: '/database/redis/advanced/lru' },
                    { text: 'Redis 慢查询日志分析', link: '/database/redis/advanced/slowlog' },
                    { text: 'Pipeline、事务（MULTI/EXEC）、Lua 脚本对比', link: '/database/redis/advanced/pipeline-transaction' },
                    { text: 'Redis 慢命令阻塞与处理', link: '/database/redis/advanced/slow-command' },
                    { text: 'Redis 监控：INFO、MONITOR、redis-cli stats', link: '/database/redis/advanced/monitor' },
                ],
            },
            {
                text: 'Redis 应用场景',
                link: '/database/redis/use-case/',
                collapsed: true,
                items: [
                    { text: '分布式 Session 管理', link: '/database/redis/use-case/session' },
                    { text: '延迟队列与定时任务', link: '/database/redis/use-case/delay-queue' },
                    { text: '排行榜与计数器（INCR）', link: '/database/redis/use-case/ranking' },
                    { text: '消息队列与粉丝关系（Set）', link: '/database/redis/use-case/message-queue' },
                    { text: '附近的人与地理围栏（GEO）', link: '/database/redis/use-case/geo' },
                    { text: '签到与连续签到统计（Bitmap）', link: '/database/redis/use-case/checkin' },
                    { text: 'UV 统计与去重（HyperLogLog）', link: '/database/redis/use-case/uv' },
                ],
            },
            { text: 'Redis 面试高频问题汇总', link: '/database/redis/interview-summary' },
        ],
    },
    {
        text: 'MongoDB',
        link: '/database/mongodb/',
        items: [
            {
                text: 'MongoDB 基础',
                link: '/database/mongodb/basic/',
                collapsed: true,
                items: [
                    { text: 'MongoDB 整体架构与适用场景', link: '/database/mongodb/basic/overview' },
                    { text: 'MongoDB 数据模型：文档、集合、数据库', link: '/database/mongodb/basic/data-model' },
                    { text: 'MongoDB CRUD 操作：insert、find、update、delete', link: '/database/mongodb/basic/crud' },
                    { text: 'MongoDB 数据类型与 BSON 规范', link: '/database/mongodb/basic/bson' },
                    { text: 'MongoDB SQL 对比：数据库、表 vs 集合、文档 vs 行', link: '/database/mongodb/basic/sql-compare' },
                ],
            },
            {
                text: '索引与查询',
                link: '/database/mongodb/index/',
                collapsed: true,
                items: [
                    { text: 'MongoDB 索引类型：单字段索引、复合索引、多键索引、地理空间索引、文本索引', link: '/database/mongodb/index/index-type' },
                    { text: 'MongoDB 索引管理：创建、查看、删除、执行计划分析', link: '/database/mongodb/index/index-manage' },
                    { text: 'MongoDB 慢查询分析与优化', link: '/database/mongodb/index/slow-query' },
                    { text: 'MongoDB 聚合管道（Aggregation Pipeline）', link: '/database/mongodb/index/aggregation' },
                    { text: 'MongoDB 聚合阶段：$match、$group、$sort、$lookup 关联查询', link: '/database/mongodb/index/aggregation-stage' },
                    { text: 'MongoDB $lookup 与关系型 JOIN 对比', link: '/database/mongodb/index/lookup' },
                ],
            },
            {
                text: '事务与并发',
                link: '/database/mongodb/transaction/',
                collapsed: true,
                items: [
                    { text: 'MongoDB 多文档事务：startSession 与 startTransaction', link: '/database/mongodb/transaction/transaction' },
                    { text: 'MongoDB 事务隔离级别与隔离保证', link: '/database/mongodb/transaction/transaction-isolation' },
                    { text: 'MongoDB 并发控制：乐观锁与版本字段', link: '/database/mongodb/transaction/concurrency' },
                    { text: 'MongoDB 锁机制：全局锁、数据库锁、集合锁、文档锁', link: '/database/mongodb/transaction/lock' },
                ],
            },
            {
                text: '集群与高可用',
                link: '/database/mongodb/cluster/',
                collapsed: true,
                items: [
                    { text: 'Replica Set 副本集：成员角色与选举机制', link: '/database/mongodb/cluster/replica-set' },
                    { text: 'Replica Set 副本集同步原理：oplog 同步', link: '/database/mongodb/cluster/oplog' },
                    { text: 'MongoDB Sharded Cluster 分片集群架构', link: '/database/mongodb/cluster/sharded-cluster' },
                    { text: 'MongoDB 分片策略：范围分片 vs 哈希分片', link: '/database/mongodb/cluster/sharding-strategy' },
                    { text: 'MongoDB 分片键选择原则与常见错误', link: '/database/mongodb/cluster/shard-key' },
                    { text: 'MongoDB 均衡器（Balancer）与 Chunk 迁移', link: '/database/mongodb/cluster/balancer' },
                    { text: 'MongoDB 高可用故障转移与选举原理', link: '/database/mongodb/cluster/failover' },
                ],
            },
            {
                text: '存储与性能',
                link: '/database/mongodb/storage/',
                collapsed: true,
                items: [
                    { text: 'MongoDB WiredTiger 存储引擎原理', link: '/database/mongodb/storage/wiredtiger' },
                    { text: 'MongoDB 压缩机制：snappy、zstd、zlib', link: '/database/mongodb/storage/compression' },
                    { text: 'MongoDB 内存管理：WiredTiger Cache 与内存配置', link: '/database/mongodb/storage/memory' },
                    { text: 'MongoDB Journal 日志与崩溃恢复', link: '/database/mongodb/storage/journal' },
                    { text: 'MongoDB 性能监控：mongostat、mongotop、Profiler', link: '/database/mongodb/storage/monitor' },
                    { text: 'MongoDB 常见性能瓶颈与优化思路', link: '/database/mongodb/storage/performance' },
                ],
            },
            {
                text: '应用与安全',
                link: '/database/mongodb/security/',
                collapsed: true,
                items: [
                    { text: 'MongoDB Spring Data MongoDB 集成', link: '/database/mongodb/security/spring-data' },
                    { text: 'MongoDB 认证与授权：SCRAM、x.509 证书、LDAP', link: '/database/mongodb/security/security' },
                    { text: 'MongoDB 用户角色与权限管理', link: '/database/mongodb/security/auth' },
                    { text: 'MongoDB 数据备份与恢复：mongodump、mongorestore', link: '/database/mongodb/security/backup' },
                    { text: 'MongoDB vs MySQL vs Redis 选型对比', link: '/database/mongodb/security/compare' },
                ],
            },
            { text: 'MongoDB 面试高频问题汇总', link: '/database/mongodb/interview-summary' },
        ],
    },
    {
        text: 'TiDB',
        link: '/database/tidb/',
        items: [
            {
                text: 'TiDB 基础',
                link: '/database/tidb/basic/',
                collapsed: true,
                items: [
                    { text: 'TiDB 分布式数据库：整体架构、核心特性', link: '/database/tidb/basic/index' },
                    { text: 'TiDB 整体架构：TiDB Server、TiKV、PD、TiFlash', link: '/database/tidb/basic/architecture' },
                    { text: 'TiDB 存储计算分离架构与 HTAP 能力', link: '/database/tidb/basic/htap' },
                    { text: 'TiDB 与 MySQL 兼容性：语法支持与迁移方案', link: '/database/tidb/basic/mysql-compatibility' },
                    { text: 'TiDB 应用场景：OLTP、OLAP 混合负载、实时数据分析', link: '/database/tidb/basic/use-case' },
                ],
            },
            {
                text: '存储引擎 TiKV',
                link: '/database/tidb/tikv/',
                collapsed: true,
                items: [
                    { text: 'TiKV 存储结构：Region 与 RocksDB', link: '/database/tidb/tikv/tikv-region' },
                    { text: 'Raft 一致性协议在 TiKV 中的实现', link: '/database/tidb/tikv/raft' },
                    { text: 'TiKV MVCC 机制与分布式事务模型', link: '/database/tidb/tikv/mvcc' },
                    { text: 'TiKV Leader 调度与热点数据分散', link: '/database/tidb/tikv/leader-schedule' },
                    { text: 'TiKV 与 TiDB 的协作机制', link: '/database/tidb/tikv/tikv-tidb' },
                ],
            },
            {
                text: 'SQL 引擎',
                link: '/database/tidb/sql/',
                collapsed: true,
                items: [
                    { text: 'TiDB SQL 执行引擎：火山模型与向量化执行', link: '/database/tidb/sql/sql-engine' },
                    { text: 'TiDB 分布式 SQL 执行：MPP 架构', link: '/database/tidb/sql/mpp' },
                    { text: 'TiDB DDL 实现：Online DDL 与 Schema 版本管理', link: '/database/tidb/sql/ddl' },
                    { text: 'TiDB 统计信息与查询优化器', link: '/database/tidb/sql/optimizer' },
                    { text: 'TiDB 事务模型：Percolator 分布式事务', link: '/database/tidb/sql/percolator' },
                ],
            },
            {
                text: '集群管理与运维',
                link: '/database/tidb/ops/',
                collapsed: true,
                items: [
                    { text: 'PD 调度组件：Region 调度与负载均衡', link: '/database/tidb/ops/pd-schedule' },
                    { text: 'TiDB 扩容与缩容：添加/删除节点', link: '/database/tidb/ops/scale' },
                    { text: 'TiDB Binlog 同步与数据迁移工具 DM', link: '/database/tidb/ops/binlog-dm' },
                    { text: 'TiDB 备份恢复：BR 工具与 Dumpling/Loader', link: '/database/tidb/ops/backup' },
                    { text: 'TiDB 性能监控：Dashboard 与 Metrics', link: '/database/tidb/ops/monitor' },
                    { text: 'TiDB 常见故障排查与优化', link: '/database/tidb/ops/troubleshoot' },
                ],
            },
            {
                text: 'TiFlash 与实时分析',
                link: '/database/tidb/analytics/',
                collapsed: true,
                items: [
                    { text: 'TiFlash 列式存储与 ClickHouse 列式引擎对比', link: '/database/tidb/analytics/tiflash' },
                    { text: 'TiDB HTAP 实战：行存与列存的智能选择', link: '/database/tidb/analytics/htap-practice' },
                    { text: 'TiSpark 与 Spark on TiDB', link: '/database/tidb/analytics/tispark' },
                ],
            },
            { text: 'TiDB 面试高频问题汇总', link: '/database/tidb/interview-summary' },
        ],
    },
    {
        text: '达梦数据库（DM）',
        link: '/database/dameng/',
        items: [
            {
                text: '达梦数据库基础',
                link: '/database/dameng/basic/',
                collapsed: true,
                items: [
                    { text: '达梦数据库（DM）概述与架构', link: '/database/dameng/basic/overview' },
                    { text: 'DM 数据库的物理结构：数据文件、日志文件、控制文件', link: '/database/dameng/basic/physical-structure' },
                    { text: 'DM 数据库的逻辑结构：表空间、段、区、页', link: '/database/dameng/basic/logical-structure' },
                    { text: 'DM 与 Oracle、MySQL 兼容性对比', link: '/database/dameng/basic/compatibility' },
                    { text: 'DM 数据库安装与配置', link: '/database/dameng/basic/install' },
                ],
            },
            {
                text: '存储引擎与索引',
                link: '/database/dameng/storage/',
                collapsed: true,
                items: [
                    { text: 'DM 堆表与索引组织表（HTSP）', link: '/database/dameng/storage/table-type' },
                    { text: 'DM 索引类型：BTREE、HASH、BITMAP、全文索引', link: '/database/dameng/storage/index-type' },
                    { text: 'DM 索引创建原则与使用建议', link: '/database/dameng/storage/index-design' },
                    { text: 'DM 表分区：范围分区、列表分区、哈希分区、组合分区', link: '/database/dameng/storage/partition' },
                ],
            },
            {
                text: '事务与并发控制',
                link: '/database/dameng/transaction/',
                collapsed: true,
                items: [
                    { text: 'DM 事务管理：MVCC 与两阶段提交', link: '/database/dameng/transaction/transaction' },
                    { text: 'DM 锁机制：行锁、表锁、死锁检测', link: '/database/dameng/transaction/lock' },
                    { text: 'DM 隔离级别与锁模式', link: '/database/dameng/transaction/isolation' },
                    { text: 'DM 多版本并发控制实现', link: '/database/dameng/transaction/mvcc' },
                ],
            },
            {
                text: '高可用与集群',
                link: '/database/dameng/cluster/',
                collapsed: true,
                items: [
                    { text: 'DM 数据守护（Data Guard）：主备同步原理', link: '/database/dameng/cluster/data-guard' },
                    { text: 'DM 实时主备与异步主备配置', link: '/database/dameng/cluster/primary-standby' },
                    { text: 'DM 读写分离集群架构', link: '/database/dameng/cluster/read-write-cluster' },
                    { text: 'DM  MPP 大规模并行处理集群', link: '/database/dameng/cluster/mpp' },
                    { text: 'DM 集群高可用故障切换与监控', link: '/database/dameng/cluster/ha' },
                ],
            },
            {
                text: '运维与安全',
                link: '/database/dameng/ops/',
                collapsed: true,
                items: [
                    { text: 'DM 备份与恢复：逻辑备份、物理备份、脱敏备份', link: '/database/dameng/ops/backup' },
                    { text: 'DM 作业调度与定时任务', link: '/database/dameng/ops/job' },
                    { text: 'DM 安全体系：用户、角色、权限管理', link: '/database/dameng/ops/security' },
                    { text: 'DM SQL 性能分析与执行计划查看', link: '/database/dameng/ops/sql-analyze' },
                    { text: 'DM 数据库迁移：从 Oracle/MySQL 迁移到达梦', link: '/database/dameng/ops/migration' },
                ],
            },
            { text: '达梦数据库面试高频问题汇总', link: '/database/dameng/interview-summary' },
        ],
    },
    {
        text: 'PostgreSQL',
        link: '/database/postgresql/',
        items: [
            {
                text: 'PostgreSQL 基础',
                link: '/database/postgresql/basic/',
                collapsed: true,
                items: [
                    { text: 'PostgreSQL 概述与核心特性', link: '/database/postgresql/basic/overview' },
                    { text: 'PostgreSQL 与 MySQL 核心差异对比', link: '/database/postgresql/basic/mysql-compare' },
                    { text: 'PostgreSQL 架构：连接管理器、查询引擎、存储引擎、索引机制', link: '/database/postgresql/basic/architecture' },
                    { text: 'PostgreSQL 常用数据类型与高级类型', link: '/database/postgresql/basic/data-type' },
                    { text: 'PostgreSQL 分页查询：OFFSET vs Keyset Cursor', link: '/database/postgresql/basic/pagination' },
                ],
            },
            {
                text: 'MVCC 与事务',
                link: '/database/postgresql/mvcc/',
                collapsed: true,
                items: [
                    { text: 'PostgreSQL MVCC 原理：xmin、xmax、tuple 可见性判断', link: '/database/postgresql/mvcc/mvcc' },
                    { text: 'PostgreSQL 事务隔离级别：Read Committed vs Repeatable Read vs Serializable', link: '/database/postgresql/mvcc/isolation' },
                    { text: 'PostgreSQL 多版本实现与 VACUUM 机制', link: '/database/postgresql/mvcc/vacuum' },
                    { text: 'PostgreSQL 锁机制：表级锁、行级锁、死锁检测', link: '/database/postgresql/mvcc/lock' },
                    { text: 'PostgreSQL 事务回滚与 savepoint', link: '/database/postgresql/mvcc/transaction' },
                ],
            },
            {
                text: '索引体系',
                link: '/database/postgresql/index/',
                collapsed: true,
                items: [
                    { text: 'PostgreSQL 索引类型：B-Tree、Hash、GIN、GiST、BRIN、Partial Index', link: '/database/postgresql/index/index-type' },
                    { text: 'PostgreSQL 复合索引与最左前缀原则', link: '/database/postgresql/index/composite-index' },
                    { text: 'PostgreSQL 表达式索引与函数索引', link: '/database/postgresql/index/expression-index' },
                    { text: 'PostgreSQL 索引失效场景与 EXPLAIN 分析', link: '/database/postgresql/index/index-invalid' },
                    { text: 'PostgreSQL 索引膨胀与 REINDEX 维护', link: '/database/postgresql/index/index-bloat' },
                    { text: 'PostgreSQL 全文检索：tsvector、tsquery 与全文索引', link: '/database/postgresql/index/fulltext' },
                ],
            },
            {
                text: '性能优化',
                link: '/database/postgresql/optimize/',
                collapsed: true,
                items: [
                    { text: 'PostgreSQL 执行计划分析：Seq Scan、Index Scan、Hash Join、Nested Loop', link: '/database/postgresql/optimize/explain' },
                    { text: 'PostgreSQL 慢查询分析与 pg_stat_statements', link: '/database/postgresql/optimize/slow-query' },
                    { text: 'PostgreSQL 统计信息与成本估算模型', link: '/database/postgresql/optimize/statistics' },
                    { text: 'PostgreSQL 连接池：PgBouncer vs Pgpool-II', link: '/database/postgresql/optimize/connection-pool' },
                    { text: 'PostgreSQL 分区表：Range、List、Hash 分区', link: '/database/postgresql/optimize/partition' },
                    { text: 'PostgreSQL 并行查询与多核利用', link: '/database/postgresql/optimize/parallel-query' },
                    { text: 'PostgreSQL 性能监控：pg_stat_activity、pg_stat_bgwriter', link: '/database/postgresql/optimize/monitor' },
                ],
            },
            {
                text: '高级特性',
                link: '/database/postgresql/advanced/',
                collapsed: true,
                items: [
                    { text: 'PostgreSQL 触发器与规则系统', link: '/database/postgresql/advanced/trigger' },
                    { text: 'PostgreSQL 存储过程：PL/pgSQL 入门', link: '/database/postgresql/advanced/plpgsql' },
                    { text: 'PostgreSQL 函数重载与操作符重载', link: '/database/postgresql/advanced/overload' },
                    { text: 'PostgreSQL 窗口函数：ROW_NUMBER、RANK、LAG、LEAD', link: '/database/postgresql/advanced/window-function' },
                    { text: 'PostgreSQL CTE 与递归查询', link: '/database/postgresql/advanced/cte' },
                    { text: 'PostgreSQL JSON/JSONB 数据类型与函数', link: '/database/postgresql/advanced/json' },
                    { text: 'PostgreSQL PostGIS 空间数据库扩展', link: '/database/postgresql/advanced/postgis' },
                ],
            },
            {
                text: '高可用与集群',
                link: '/database/postgresql/cluster/',
                collapsed: true,
                items: [
                    { text: 'PostgreSQL 流复制（Streaming Replication）原理', link: '/database/postgresql/cluster/streaming-replication' },
                    { text: 'PostgreSQL 主从切换与故障转移', link: '/database/postgresql/cluster/failover' },
                    { text: 'PostgreSQL 逻辑复制 vs 物理复制', link: '/database/postgresql/cluster/logical-replication' },
                    { text: 'PostgreSQL Citus 分布式集群扩展', link: '/database/postgresql/cluster/citus' },
                    { text: 'PostgreSQL 备份与恢复：pg_dump、pg_basebackup、PITR', link: '/database/postgresql/cluster/backup' },
                    { text: 'PostgreSQL 高可用方案：Patroni + etcd、PAF、Corosync', link: '/database/postgresql/cluster/ha-solution' },
                ],
            },
            { text: 'PostgreSQL 面试高频问题汇总', link: '/database/postgresql/interview-summary' },
        ],
    },
    {
        text: 'Oracle',
        link: '/database/oracle/',
        items: [
            {
                text: 'Oracle 基础',
                link: '/database/oracle/basic/',
                collapsed: true,
                items: [
                    { text: 'Oracle 数据库概述与架构总览', link: '/database/oracle/basic/overview' },
                    { text: 'Oracle 实例与数据库：Instance vs Database', link: '/database/oracle/basic/instance' },
                    { text: 'Oracle 物理结构：数据文件、日志文件、控制文件、参数文件', link: '/database/oracle/basic/physical-structure' },
                    { text: 'Oracle 逻辑结构：表空间、段、区、块', link: '/database/oracle/basic/logical-structure' },
                    { text: 'Oracle SGA 与 PGA 内存结构', link: '/database/oracle/basic/sga-pga' },
                    { text: 'Oracle 后台进程：DBWn、LGWR、CKPT、SMON、PMON', link: '/database/oracle/basic/background-process' },
                ],
            },
            {
                text: 'SQL 与 PL/SQL',
                link: '/database/oracle/sql/',
                collapsed: true,
                items: [
                    { text: 'Oracle SQL 基础：SELECT、DML、DDL', link: '/database/oracle/sql/sql-basics' },
                    { text: 'Oracle 常用函数：字符、数值、日期、转换函数', link: '/database/oracle/sql/functions' },
                    { text: 'Oracle 分页查询：ROWNUM 与 ROW_NUMBER', link: '/database/oracle/sql/pagination' },
                    { text: 'PL/SQL 块结构：DECLARE、BEGIN、EXCEPTION、END', link: '/database/oracle/sql/plsql-block' },
                    { text: 'PL/SQL 存储过程与函数：参数模式与返回类型', link: '/database/oracle/sql/procedure-function' },
                    { text: 'PL/SQL 触发器：DML 触发器、INSTEAD OF 触发器、系统触发器', link: '/database/oracle/sql/trigger' },
                    { text: 'PL/SQL 游标：显式游标与隐式游标', link: '/database/oracle/sql/cursor' },
                    { text: 'PL/SQL 集合类型：VARRAY、NESTED TABLE、关联数组（INDEX BY TABLE）', link: '/database/oracle/sql/collection' },
                    { text: 'PL/SQL 异常处理：预定义异常、用户自定义异常', link: '/database/oracle/sql/exception' },
                    { text: 'Oracle 序列与同义词', link: '/database/oracle/sql/sequence-synonym' },
                ],
            },
            {
                text: '存储与索引',
                link: '/database/oracle/storage/',
                collapsed: true,
                items: [
                    { text: 'Oracle 表类型：堆表、索引组织表（IOT）、聚簇表、外部表', link: '/database/oracle/storage/table-type' },
                    { text: 'Oracle 索引类型：B-Tree 索引、位图索引、函数索引、反向键索引', link: '/database/oracle/storage/index-type' },
                    { text: 'Oracle 索引组织表（IOT）与聚簇因子', link: '/database/oracle/storage/iot' },
                    { text: 'Oracle 分区表：Range、Hash、List、复合分区', link: '/database/oracle/storage/partition' },
                    { text: 'Oracle 表压缩：OLTP 压缩与 HCC 压缩', link: '/database/oracle/storage/compression' },
                ],
            },
            {
                text: '事务与并发',
                link: '/database/oracle/transaction/',
                collapsed: true,
                items: [
                    { text: 'Oracle 事务管理：COMMIT、ROLLBACK、SAVEPOINT', link: '/database/oracle/transaction/transaction' },
                    { text: 'Oracle 锁机制：TM 锁（表锁）与 TX 锁（行锁）', link: '/database/oracle/transaction/lock' },
                    { text: 'Oracle 隔离级别与多版本并发控制（MVCC）', link: '/database/oracle/transaction/isolation' },
                    { text: 'Oracle 闪回技术：Flashback Query、Flashback Table、Flashback Drop', link: '/database/oracle/transaction/flashback' },
                    { text: 'Oracle 乐观锁与悲观锁实现', link: '/database/oracle/transaction/optimistic-pessimistic' },
                ],
            },
            {
                text: '性能优化',
                link: '/database/oracle/optimize/',
                collapsed: true,
                items: [
                    { text: 'Oracle 执行计划分析：EXPLAIN PLAN 与 AUTOTRACE', link: '/database/oracle/optimize/explain' },
                    { text: 'Oracle SQL 性能分析：SQL Tuning Advisor 与 SQL Access Advisor', link: '/database/oracle/optimize/sql-tuning' },
                    { text: 'Oracle 统计信息：表统计、索引统计、系统统计', link: '/database/oracle/optimize/statistics' },
                    { text: 'Oracle 绑定变量与自适应游标共享（ACS）', link: '/database/oracle/optimize/bind-variable' },
                    { text: 'Oracle AWR、ASH、ADDM 性能报告分析', link: '/database/oracle/optimize/awr-ash' },
                    { text: 'Oracle 连接池与共享服务器模式', link: '/database/oracle/optimize/shared-server' },
                    { text: 'Oracle 并行查询与 DML 并行度', link: '/database/oracle/optimize/parallel' },
                ],
            },
            {
                text: '高可用与集群',
                link: '/database/oracle/cluster/',
                collapsed: true,
                items: [
                    { text: 'Oracle Data Guard：原理与三种保护模式', link: '/database/oracle/cluster/data-guard' },
                    { text: 'Oracle RAC 集群架构：Cache Fusion 与 GCS', link: '/database/oracle/cluster/rac' },
                    { text: 'Oracle RAC 高可用：VIP、SCAN IP、负载均衡', link: '/database/oracle/cluster/rac-ha' },
                    { text: 'Oracle ASM 存储管理', link: '/database/oracle/cluster/asm' },
                    { text: 'Oracle GoldenGate 数据同步', link: '/database/oracle/cluster/goldengate' },
                    { text: 'Oracle RMAN 备份与恢复', link: '/database/oracle/cluster/rman' },
                    { text: 'Oracle Exadata 一体机简介', link: '/database/oracle/cluster/exadata' },
                ],
            },
            { text: 'Oracle 面试高频问题汇总', link: '/database/oracle/interview-summary' },
        ],
    },
    {
        text: 'SQL Server',
        link: '/database/sqlserver/',
        items: [
            {
                text: 'SQL Server 基础',
                link: '/database/sqlserver/basic/',
                collapsed: true,
                items: [
                    { text: 'SQL Server 整体架构：关系引擎与存储引擎', link: '/database/sqlserver/basic/architecture' },
                    { text: 'SQL Server 页面与区（Page & Extent）存储结构', link: '/database/sqlserver/basic/page-extent' },
                    { text: 'SQL Server 数据库文件：主数据文件、日志文件、文件组', link: '/database/sqlserver/basic/file-group' },
                    { text: 'SQL Server 日志体系：LDF 与 Write-Ahead Logging', link: '/database/sqlserver/basic/transaction-log' },
                    { text: 'SQL Server T-SQL 基础与常用语法', link: '/database/sqlserver/basic/tsql-basics' },
                    { text: 'SQL Server 分页：OFFSET FETCH vs CTE 分页', link: '/database/sqlserver/basic/pagination' },
                ],
            },
            {
                text: '索引与查询',
                link: '/database/sqlserver/index/',
                collapsed: true,
                items: [
                    { text: 'SQL Server 索引结构：B-Tree 与聚集索引、非聚集索引', link: '/database/sqlserver/index/index-structure' },
                    { text: 'SQL Server 聚集索引 vs 非聚集索引设计原则', link: '/database/sqlserver/index/clustered-index' },
                    { text: 'SQL Server 索引类型：位图索引、包含列索引、过滤索引', link: '/database/sqlserver/index/index-type' },
                    { text: 'SQL Server 执行计划分析：SSMS 与 SET STATISTICS IO ON', link: '/database/sqlserver/index/explain' },
                    { text: 'SQL Server 慢查询优化实战', link: '/database/sqlserver/index/slow-query' },
                    { text: 'SQL Server 统计信息与执行计划重编译', link: '/database/sqlserver/index/statistics' },
                ],
            },
            {
                text: '事务与锁',
                link: '/database/sqlserver/transaction/',
                collapsed: true,
                items: [
                    { text: 'SQL Server 事务日志与 Write-Ahead Logging', link: '/database/sqlserver/transaction/wal' },
                    { text: 'SQL Server 隔离级别：脏读、不可重复读、幻读、快照隔离', link: '/database/sqlserver/transaction/isolation' },
                    { text: 'SQL Server 锁模式：共享锁、排他锁、更新锁、意向锁', link: '/database/sqlserver/transaction/lock-mode' },
                    { text: 'SQL Server 死锁产生条件与排查优化', link: '/database/sqlserver/transaction/deadlock' },
                    { text: 'SQL Server 乐观并发与行版本控制', link: '/database/sqlserver/transaction/optimistic-concurrency' },
                ],
            },
            {
                text: '性能与调优',
                link: '/database/sqlserver/optimize/',
                collapsed: true,
                items: [
                    { text: 'SQL Server 性能监控：DMV 与扩展事件（XEvent）', link: '/database/sqlserver/optimize/dmv' },
                    { text: 'SQL Server 查询优化器与计划指南', link: '/database/sqlserver/optimize/query-optimizer' },
                    { text: 'SQL Server 内存管理：Buffer Pool 与 Columnstore', link: '/database/sqlserver/optimize/memory' },
                    { text: 'SQL Server 表分区：分区函数与分区方案', link: '/database/sqlserver/optimize/partition' },
                    { text: 'SQL Server 内存优化表（In-Memory OLTP）', link: '/database/sqlserver/optimize/in-memory' },
                    { text: 'SQL Server 列存储索引与批处理模式', link: '/database/sqlserver/optimize/columnstore' },
                ],
            },
            {
                text: '高可用与集群',
                link: '/database/sqlserver/cluster/',
                collapsed: true,
                items: [
                    { text: 'SQL Server Always On 可用性组架构', link: '/database/sqlserver/cluster/always-on' },
                    { text: 'SQL Server 故障转移群集（FCI）', link: '/database/sqlserver/cluster/fci' },
                    { text: 'SQL Server 镜像（Database Mirroring）', link: '/database/sqlserver/cluster/mirroring' },
                    { text: 'SQL Server 复制：快照复制、事务复制、合并复制', link: '/database/sqlserver/cluster/replication' },
                    { text: 'SQL Server 备份策略与恢复模式', link: '/database/sqlserver/cluster/backup' },
                    { text: 'SQL Server 登台环境与数据库迁移', link: '/database/sqlserver/cluster/migration' },
                ],
            },
            { text: 'SQL Server 面试高频问题汇总', link: '/database/sqlserver/interview-summary' },
        ],
    },
    {
        text: 'SQLite',
        link: '/database/sqlite/',
        items: [
            { text: 'SQLite 概述与核心特性', link: '/database/sqlite/overview' },
            { text: 'SQLite 数据库文件结构：Page 与 B-Tree', link: '/database/sqlite/file-structure' },
            { text: 'SQLite 事务模型与 WAL 模式', link: '/database/sqlite/transaction' },
            { text: 'SQLite 索引与查询优化', link: '/database/sqlite/index' },
            { text: 'SQLite 的并发限制：写锁与数据库锁', link: '/database/sqlite/concurrency' },
            { text: 'SQLite 与 Android 嵌入式开发', link: '/database/sqlite/android' },
            { text: 'SQLite 适用场景与局限性', link: '/database/sqlite/limitation' },
        ],
    },
    {
        text: 'MariaDB',
        link: '/database/mariadb/',
        items: [
            {
                text: 'MariaDB 基础',
                link: '/database/mariadb/basic/',
                collapsed: true,
                items: [
                    { text: 'MariaDB 概述与 MySQL 分支发展史', link: '/database/mariadb/basic/overview' },
                    { text: 'MariaDB vs MySQL：核心差异对比', link: '/database/mariadb/basic/mysql-compare' },
                    { text: 'MariaDB 存储引擎：InnoDB、Aria、XtraDB、TokuDB', link: '/database/mariadb/basic/engine' },
                    { text: 'MariaDB 新增特性：系统版本表、Galera Cluster、Spider 存储引擎', link: '/database/mariadb/basic/new-feature' },
                ],
            },
            {
                text: 'MariaDB 高级特性',
                link: '/database/mariadb/advanced/',
                collapsed: true,
                items: [
                    { text: 'MariaDB 线程池（Thread Pool）插件', link: '/database/mariadb/advanced/thread-pool' },
                    { text: 'MariaDB CONNECT 存储引擎：访问多种外部数据源', link: '/database/mariadb/advanced/connect-engine' },
                    { text: 'MariaDB 虚拟列与序列（Sequence）', link: '/database/mariadb/advanced/virtual-column' },
                    { text: 'MariaDB 窗口函数与 CT（Common Table Expression）', link: '/database/mariadb/advanced/window-function' },
                    { text: 'MariaDB 审计插件与安全增强', link: '/database/mariadb/advanced/audit' },
                ],
            },
            {
                text: 'MariaDB 集群与高可用',
                link: '/database/mariadb/cluster/',
                collapsed: true,
                items: [
                    { text: 'MariaDB Galera Cluster 原理：同步多主复制', link: '/database/mariadb/cluster/galera' },
                    { text: 'MariaDB Galera Cluster 节点加入与故障恢复', link: '/database/mariadb/cluster/galera-node' },
                    { text: 'MariaDB 主从复制与 GTID', link: '/database/mariadb/cluster/replication' },
                    { text: 'MariaDB MaxScale 读写分离中间件', link: '/database/mariadb/cluster/maxscale' },
                    { text: 'MariaDB 备份与恢复：XtraBackup 集成', link: '/database/mariadb/cluster/backup' },
                ],
            },
            { text: 'MariaDB 面试高频问题汇总', link: '/database/mariadb/interview-summary' },
        ],
    },
    {
        text: '时序数据库',
        link: '/database/tsdb/',
        items: [
            {
                text: '时序数据库基础',
                link: '/database/tsdb/basic/',
                collapsed: true,
                items: [
                    { text: '时序数据库（TSDB）核心概念：时间线、度量、标签、数据点', link: '/database/tsdb/basic/concept' },
                    { text: '时序数据库 vs 关系数据库：核心差异', link: '/database/tsdb/basic/rdb-compare' },
                    { text: '时序数据库选型：InfluxDB vs TimescaleDB vs TDengine vs Prometheus', link: '/database/tsdb/basic/select' },
                ],
            },
            {
                text: 'InfluxDB',
                link: '/database/tsdb/influxdb/',
                collapsed: true,
                items: [
                    { text: 'InfluxDB 数据模型：Measurement、Tag、Field、Timestamp', link: '/database/tsdb/influxdb/data-model' },
                    { text: 'InfluxDB Line Protocol 与数据写入', link: '/database/tsdb/influxdb/line-protocol' },
                    { text: 'InfluxDB 连续查询（Continuous Query）与降采样', link: '/database/tsdb/influxdb/continuous-query' },
                    { text: 'InfluxDB 保留策略（Retention Policy）与数据过期', link: '/database/tsdb/influxdb/retention-policy' },
                    { text: 'InfluxDB 倒排索引与 TSM 存储引擎', link: '/database/tsdb/influxdb/tsm' },
                    { text: 'InfluxDB 查询语言 InfluxQL 与 Flux', link: '/database/tsdb/influxdb/influxql-flux' },
                    { text: 'Telegraf + InfluxDB + Grafana 监控技术栈', link: '/database/tsdb/influxdb/telegraf' },
                ],
            },
            {
                text: 'TDengine',
                link: '/database/tsdb/tdengine/',
                collapsed: true,
                items: [
                    { text: 'TDengine 超级表与子表设计', link: '/database/tsdb/tdengine/supertable' },
                    { text: 'TDengine 写入性能与集群架构', link: '/database/tsdb/tdengine/cluster' },
                    { text: 'TDengine 查询与降采样', link: '/database/tsdb/tdengine/query' },
                    { text: 'TDengine vs InfluxDB vs TimescaleDB 对比', link: '/database/tsdb/tdengine/compare' },
                ],
            },
            {
                text: 'Prometheus',
                link: '/database/tsdb/prometheus/',
                collapsed: true,
                items: [
                    { text: 'Prometheus 数据模型与 metrics 类型', link: '/database/tsdb/prometheus/data-model' },
                    { text: 'Prometheus Pull vs Push 采集模式', link: '/database/tsdb/prometheus/pull-push' },
                    { text: 'Prometheus 存储：TSDB 与远程存储', link: '/database/tsdb/prometheus/storage' },
                    { text: 'Prometheus PromQL 查询语言与函数', link: '/database/tsdb/prometheus/promql' },
                    { text: 'Prometheus 告警规则与 AlertManager', link: '/database/tsdb/prometheus/alert' },
                    { text: 'Prometheus 与 Kubernetes 服务发现', link: '/database/tsdb/prometheus/k8s-discovery' },
                ],
            },
        ],
    },
    {
        text: 'HBase',
        link: '/database/hbase/',
        items: [
            {
                text: 'HBase 基础',
                link: '/database/hbase/basic/',
                collapsed: true,
                items: [
                    { text: 'HBase 整体架构：Region Server、Master、ZooKeeper', link: '/database/hbase/basic/architecture' },
                    { text: 'HBase 数据模型：RowKey、Column Family、Column Qualifier、Timestamp', link: '/database/hbase/basic/data-model' },
                    { text: 'HBase 表设计与 RowKey 设计原则', link: '/database/hbase/basic/rowkey-design' },
                    { text: 'HBase CAP 权衡：一致性 vs 可用性', link: '/database/hbase/basic/cap' },
                    { text: 'HBase vs 关系数据库：何时选择 HBase', link: '/database/hbase/basic/rdb-compare' },
                ],
            },
            {
                text: 'HBase 存储原理',
                link: '/database/hbase/storage/',
                collapsed: true,
                items: [
                    { text: 'HBase 物理存储：MemStore 与 HFile', link: '/database/hbase/storage/hfile' },
                    { text: 'HBase 写流程：WAL + MemStore + Flush', link: '/database/hbase/storage/write-flow' },
                    { text: 'HBase 读流程：BlockCache + MemStore + HFile', link: '/database/hbase/storage/read-flow' },
                    { text: 'HBase Compaction：Minor Compaction vs Major Compaction', link: '/database/hbase/storage/compaction' },
                    { text: 'HBase Region 分裂机制与负载均衡', link: '/database/hbase/storage/region-split' },
                    { text: 'HBase 布隆过滤器（Bloom Filter）优化读性能', link: '/database/hbase/storage/bloom-filter' },
                ],
            },
            {
                text: 'HBase 集群与运维',
                link: '/database/hbase/ops/',
                collapsed: true,
                items: [
                    { text: 'HBase 预分区与 Region 热点问题处理', link: '/database/hbase/ops/hotspot' },
                    { text: 'HBase 协处理器（Coprocessor）：Observer 与 Endpoint', link: '/database/hbase/ops/coprocessor' },
                    { text: 'HBase 快照与备份恢复', link: '/database/hbase/ops/snapshot' },
                    { text: 'HBase 性能监控：Region Server 指标分析', link: '/database/hbase/ops/monitor' },
                    { text: 'HBase 常见故障排查与优化建议', link: '/database/hbase/ops/troubleshoot' },
                ],
            },
            {
                text: 'HBase 应用与生态',
                link: '/database/hbase/ecosystem/',
                collapsed: true,
                items: [
                    { text: 'HBase API 使用：Java API 与 Shell 操作', link: '/database/hbase/ecosystem/api' },
                    { text: 'HBase 与 Phoenix：SQL 层访问 HBase', link: '/database/hbase/ecosystem/phoenix' },
                    { text: 'HBase 与 Hive/Hadoop 生态集成', link: '/database/hbase/ecosystem/hive' },
                    { text: 'HBase 二级索引实现方案', link: '/database/hbase/ecosystem/secondary-index' },
                    { text: 'HBase 在大数据场景的应用：用户行为日志、实时分析', link: '/database/hbase/ecosystem/use-case' },
                ],
            },
            { text: 'HBase 面试高频问题汇总', link: '/database/hbase/interview-summary' },
        ],
    },
]
