export const databaseSidebar = [
    {
        text: 'MySQL',
        link: '/database/mysql/',
        items: [
            {
                text: 'MySQL 基础',
                link: '/database/mysql/basic/',
                collapsed: true,
                items: [
                    { text: 'MySQL 整体架构', link: '/database/mysql/basic/architecture' },
                    { text: 'MySQL 存储引擎对比', link: '/database/mysql/basic/engine-compare' },
                    { text: 'InnoDB 存储引擎特性', link: '/database/mysql/basic/innodb' },
                    { text: 'MySQL 数据类型选择', link: '/database/mysql/basic/data-type' },
                    { text: 'SQL 执行过程', link: '/database/mysql/basic/sql-execution' },
                ],
            },
            {
                text: '索引与数据结构',
                link: '/database/mysql/index/',
                collapsed: true,
                items: [
                    { text: 'MySQL 索引体系', link: '/database/mysql/index/index-type' },
                    { text: 'B+ 树索引结构', link: '/database/mysql/index/btree-index' },
                    { text: 'B+ 树 vs B 树 vs Hash', link: '/database/mysql/index/index-structure-compare' },
                    { text: '聚簇 vs 非聚簇索引', link: '/database/mysql/index/clustered-index' },
                    { text: '回表查询与覆盖索引', link: '/database/mysql/index/covering-index' },
                    { text: '联合索引与最左前缀', link: '/database/mysql/index/composite-index' },
                    { text: '索引下推 ICP', link: '/database/mysql/index/index-pushdown' },
                    { text: '索引失效的 11 种情况', link: '/database/mysql/index/index-invalid' },
                    { text: '索引创建原则', link: '/database/mysql/index/index-design' },
                    { text: '自适应哈希索引 AHI', link: '/database/mysql/index/ahi' },
                    { text: 'MRR 优化', link: '/database/mysql/index/mrr' },
                ],
            },
            {
                text: '事务与隔离级别',
                link: '/database/mysql/transaction/',
                collapsed: true,
                items: [
                    { text: '事务 ACID 特性', link: '/database/mysql/transaction/acid' },
                    { text: '并发事务问题', link: '/database/mysql/transaction/transaction-problem' },
                    { text: '四种隔离级别', link: '/database/mysql/transaction/isolation-level' },
                    { text: 'MVCC 原理', link: '/database/mysql/transaction/mvcc' },
                    { text: 'MVCC RC 和 RR 差异', link: '/database/mysql/transaction/mvcc-rc-rr' },
                    { text: '当前读与快照读', link: '/database/mysql/transaction/current-snapshot-read' },
                    { text: 'ReadView 生成时机', link: '/database/mysql/transaction/readview' },
                ],
            },
            {
                text: '锁机制',
                link: '/database/mysql/lock/',
                collapsed: true,
                items: [
                    { text: '全局锁与表级锁 MDL', link: '/database/mysql/lock/table-lock' },
                    { text: '行锁与 Next-Key Lock', link: '/database/mysql/lock/row-lock' },
                    { text: '意向锁 IX 与 IS', link: '/database/mysql/lock/intention-lock' },
                    { text: '两阶段锁协议', link: '/database/mysql/lock/two-phase-lock' },
                    { text: '死锁处理策略', link: '/database/mysql/lock/deadlock' },
                    { text: '乐观锁与悲观锁', link: '/database/mysql/lock/optimistic-pessimistic-lock' },
                ],
            },
            {
                text: 'SQL 优化',
                link: '/database/mysql/sql-optimize/',
                collapsed: true,
                items: [
                    { text: '慢查询定位', link: '/database/mysql/sql-optimize/slow-query' },
                    { text: 'EXPLAIN 执行计划', link: '/database/mysql/sql-optimize/explain' },
                    { text: 'filesort 与临时表', link: '/database/mysql/sql-optimize/filesort-temporary' },
                    { text: 'JOIN 原理 NLJ', link: '/database/mysql/sql-optimize/join-principle' },
                    { text: 'JOIN 优化', link: '/database/mysql/sql-optimize/join-optimize' },
                    { text: '子查询分类与优化', link: '/database/mysql/sql-optimize/subquery' },
                    { text: '分页查询优化', link: '/database/mysql/sql-optimize/pagination' },
                    { text: 'COUNT 性能对比', link: '/database/mysql/sql-optimize/count-performance' },
                    { text: 'DML 语句优化', link: '/database/mysql/sql-optimize/dml-optimize' },
                    { text: 'ORDER BY 排序优化', link: '/database/mysql/sql-optimize/orderby-optimize' },
                    { text: 'GROUP BY 优化', link: '/database/mysql/sql-optimize/groupby-optimize' },
                ],
            },
            {
                text: '数据库架构',
                link: '/database/mysql/architecture/',
                collapsed: true,
                items: [
                    { text: '主从复制原理', link: '/database/mysql/architecture/replication' },
                    { text: '主从复制模式', link: '/database/mysql/architecture/replication-mode' },
                    { text: '主从延迟与解决', link: '/database/mysql/architecture/replication-lag' },
                    { text: '读写分离架构', link: '/database/mysql/architecture/read-write-separation' },
                    { text: 'MySQL 高可用方案', link: '/database/mysql/architecture/ha-solution' },
                    { text: '分库分表', link: '/database/mysql/architecture/sharding' },
                    { text: '分片键与分片算法', link: '/database/mysql/architecture/sharding-algorithm' },
                    { text: '跨节点查询', link: '/database/mysql/architecture/sharding-query' },
                    { text: 'ShardingSphere 实战', link: '/database/mysql/architecture/shardingsphere' },
                    { text: 'MySQL 三大日志', link: '/database/mysql/architecture/mysql-logs' },
                    { text: 'redo log 两阶段提交', link: '/database/mysql/architecture/redolog-commit' },
                ],
            },
            {
                text: '数据库设计',
                link: '/database/mysql/schema/',
                collapsed: true,
                items: [
                    { text: '三范式与反范式', link: '/database/mysql/schema/nf-design' },
                    { text: '大表优化', link: '/database/mysql/schema/big-table' },
                    { text: '表结构设计优化', link: '/database/mysql/schema/schema-optimize' },
                ],
            },
            { text: 'MySQL 面试高频问题', link: '/database/mysql/interview-summary' },
        ],
    },
    {
        text: 'Redis',
        link: '/database/redis/',
        items: [
            {
                text: 'Redis 基础',
                link: '/database/redis/basic/',
                collapsed: true,
                items: [
                    { text: 'Redis 为什么要用单线程', link: '/database/redis/basic/why-single-thread' },
                    { text: 'Redis 6.0 多线程', link: '/database/redis/basic/multi-thread' },
                    { text: 'Redis 数据类型', link: '/database/redis/basic/data-type' },
                    { text: 'Redis 对象系统', link: '/database/redis/basic/object-system' },
                    { text: 'Redis 跳跃表 ZSet', link: '/database/redis/basic/skiplist' },
                    { text: 'HyperLogLog 等', link: '/database/redis/basic/bitmap-hll' },
                ],
            },
            {
                text: '持久化机制',
                link: '/database/redis/persistence/',
                collapsed: true,
                items: [
                    { text: 'RDB 快照持久化', link: '/database/redis/persistence/rdb' },
                    { text: 'AOF 追加文件持久化', link: '/database/redis/persistence/aof' },
                    { text: 'AOF 重写机制', link: '/database/redis/persistence/aof-rewrite' },
                    { text: 'RDB vs AOF 混合持久化', link: '/database/redis/persistence/rdb-aof-compare' },
                    { text: '数据恢复流程', link: '/database/redis/persistence/data-recovery' },
                ],
            },
            {
                text: '集群与高可用',
                link: '/database/redis/cluster/',
                collapsed: true,
                items: [
                    { text: '主从复制原理', link: '/database/redis/cluster/replication' },
                    { text: '主从复制风暴', link: '/database/redis/cluster/replication-storm' },
                    { text: '哨兵 Sentinel 机制', link: '/database/redis/cluster/sentinel' },
                    { text: 'Redis Cluster 槽分片', link: '/database/redis/cluster/cluster' },
                    { text: 'Redis Cluster 故障转移', link: '/database/redis/cluster/cluster-failover' },
                    { text: 'Redis Cluster 对比', link: '/database/redis/cluster/cluster-compare' },
                    { text: 'Redis 脑裂问题', link: '/database/redis/cluster/split-brain' },
                ],
            },
            {
                text: '缓存策略',
                link: '/database/redis/cache/',
                collapsed: true,
                items: [
                    { text: '缓存穿透', link: '/database/redis/cache/cache-penetration' },
                    { text: '缓存击穿', link: '/database/redis/cache/cache-breakdown' },
                    { text: '缓存雪崩', link: '/database/redis/cache/cache-avalanche' },
                    { text: '缓存双写一致性', link: '/database/redis/cache/cache-consistency' },
                    { text: '缓存模式对比', link: '/database/redis/cache/cache-pattern' },
                    { text: '热点数据处理', link: '/database/redis/cache/hot-key' },
                    { text: '大 key 发现与解决', link: '/database/redis/cache/big-key' },
                    { text: 'Redis 分布式锁', link: '/database/redis/cache/distributed-lock' },
                    { text: 'RedLock 算法', link: '/database/redis/cache/redlock' },
                ],
            },
            {
                text: 'Redis 高级特性',
                link: '/database/redis/advanced/',
                collapsed: true,
                items: [
                    { text: 'I/O 模型 epoll', link: '/database/redis/advanced/io-model' },
                    { text: 'Redis 淘汰策略', link: '/database/redis/advanced/eviction-policy' },
                    { text: 'LRU 算法实现', link: '/database/redis/advanced/lru' },
                    { text: 'Redis 慢查询日志', link: '/database/redis/advanced/slowlog' },
                    { text: 'Pipeline 事务对比', link: '/database/redis/advanced/pipeline-transaction' },
                    { text: 'Redis 慢命令阻塞', link: '/database/redis/advanced/slow-command' },
                    { text: 'Redis 监控', link: '/database/redis/advanced/monitor' },
                ],
            },
            {
                text: 'Redis 应用场景',
                link: '/database/redis/use-case/',
                collapsed: true,
                items: [
                    { text: '分布式 Session', link: '/database/redis/use-case/session' },
                    { text: '延迟队列与定时任务', link: '/database/redis/use-case/delay-queue' },
                    { text: '排行榜与计数器', link: '/database/redis/use-case/ranking' },
                    { text: '消息队列与粉丝关系', link: '/database/redis/use-case/message-queue' },
                    { text: '附近的人与地理围栏', link: '/database/redis/use-case/geo' },
                    { text: '签到与连续签到', link: '/database/redis/use-case/checkin' },
                    { text: 'UV 统计 HyperLogLog', link: '/database/redis/use-case/uv' },
                ],
            },
            { text: 'Redis 面试高频问题', link: '/database/redis/interview-summary' },
        ],
    },
    {
        text: 'MongoDB',
        link: '/database/mongodb/',
        items: [
            {
                text: 'MongoDB 基础',
                link: '/database/mongodb/basic/',
                collapsed: true,
                items: [
                    { text: 'MongoDB 整体架构', link: '/database/mongodb/basic/overview' },
                    { text: 'MongoDB 数据模型', link: '/database/mongodb/basic/data-model' },
                    { text: 'MongoDB CRUD 操作', link: '/database/mongodb/basic/crud' },
                    { text: 'MongoDB 数据类型', link: '/database/mongodb/basic/bson' },
                    { text: 'MongoDB vs SQL', link: '/database/mongodb/basic/sql-compare' },
                ],
            },
            {
                text: '索引与查询',
                link: '/database/mongodb/index/',
                collapsed: true,
                items: [
                    { text: 'MongoDB 索引类型', link: '/database/mongodb/index/index-type' },
                    { text: 'MongoDB 索引管理', link: '/database/mongodb/index/index-manage' },
                    { text: 'MongoDB 慢查询分析', link: '/database/mongodb/index/slow-query' },
                    { text: '聚合管道 Aggregation', link: '/database/mongodb/index/aggregation' },
                    { text: '聚合阶段详解', link: '/database/mongodb/index/aggregation-stage' },
                    { text: 'MongoDB $lookup', link: '/database/mongodb/index/lookup' },
                ],
            },
            {
                text: '事务与并发',
                link: '/database/mongodb/transaction/',
                collapsed: true,
                items: [
                    { text: 'MongoDB 多文档事务', link: '/database/mongodb/transaction/transaction' },
                    { text: '事务隔离级别', link: '/database/mongodb/transaction/transaction-isolation' },
                    { text: '并发控制乐观锁', link: '/database/mongodb/transaction/concurrency' },
                    { text: 'MongoDB 锁机制', link: '/database/mongodb/transaction/lock' },
                ],
            },
            {
                text: '集群与高可用',
                link: '/database/mongodb/cluster/',
                collapsed: true,
                items: [
                    { text: 'Replica Set 副本集', link: '/database/mongodb/cluster/replica-set' },
                    { text: '副本集同步 oplog', link: '/database/mongodb/cluster/oplog' },
                    { text: '分片集群', link: '/database/mongodb/cluster/sharded-cluster' },
                    { text: '分片策略对比', link: '/database/mongodb/cluster/sharding-strategy' },
                    { text: '分片键选择原则', link: '/database/mongodb/cluster/shard-key' },
                    { text: 'Balancer 与 Chunk', link: '/database/mongodb/cluster/balancer' },
                    { text: '高可用故障转移', link: '/database/mongodb/cluster/failover' },
                ],
            },
            {
                text: '存储与性能',
                link: '/database/mongodb/storage/',
                collapsed: true,
                items: [
                    { text: 'WiredTiger 存储引擎', link: '/database/mongodb/storage/wiredtiger' },
                    { text: 'MongoDB 压缩机制', link: '/database/mongodb/storage/compression' },
                    { text: '内存管理', link: '/database/mongodb/storage/memory' },
                    { text: 'Journal 日志', link: '/database/mongodb/storage/journal' },
                    { text: '性能监控', link: '/database/mongodb/storage/monitor' },
                    { text: '性能瓶颈与优化', link: '/database/mongodb/storage/performance' },
                ],
            },
            {
                text: '应用与安全',
                link: '/database/mongodb/security/',
                collapsed: true,
                items: [
                    { text: 'Spring MongoDB', link: '/database/mongodb/security/spring-data' },
                    { text: 'MongoDB 认证授权', link: '/database/mongodb/security/security' },
                    { text: '用户角色权限管理', link: '/database/mongodb/security/auth' },
                    { text: '数据备份与恢复', link: '/database/mongodb/security/backup' },
                    { text: 'MongoDB vs MySQL', link: '/database/mongodb/security/compare' },
                ],
            },
            { text: 'MongoDB 面试高频问题', link: '/database/mongodb/interview-summary' },
        ],
    },
    {
        text: 'TiDB',
        link: '/database/tidb/',
        items: [
            {
                text: 'TiDB 基础',
                link: '/database/tidb/basic/',
                collapsed: true,
                items: [
                    { text: 'TiDB 分布式数据库', link: '/database/tidb/basic/index' },
                    { text: 'TiDB 整体架构', link: '/database/tidb/basic/architecture' },
                    { text: '存储计算分离 HTAP', link: '/database/tidb/basic/htap' },
                    { text: '与 MySQL 兼容性', link: '/database/tidb/basic/mysql-compatibility' },
                    { text: 'TiDB 应用场景', link: '/database/tidb/basic/use-case' },
                ],
            },
            {
                text: '存储引擎 TiKV',
                link: '/database/tidb/tikv/',
                collapsed: true,
                items: [
                    { text: 'TiKV 存储结构', link: '/database/tidb/tikv/tikv-region' },
                    { text: 'Raft 一致性协议', link: '/database/tidb/tikv/raft' },
                    { text: 'TiKV MVCC 机制', link: '/database/tidb/tikv/mvcc' },
                    { text: 'Leader 调度热点分散', link: '/database/tidb/tikv/leader-schedule' },
                    { text: 'TiKV 与 TiDB 协作', link: '/database/tidb/tikv/tikv-tidb' },
                ],
            },
            {
                text: 'SQL 引擎',
                link: '/database/tidb/sql/',
                collapsed: true,
                items: [
                    { text: 'SQL 执行引擎', link: '/database/tidb/sql/sql-engine' },
                    { text: 'MPP 架构', link: '/database/tidb/sql/mpp' },
                    { text: 'DDL 实现', link: '/database/tidb/sql/ddl' },
                    { text: '统计信息与优化器', link: '/database/tidb/sql/optimizer' },
                    { text: 'Percolator 事务模型', link: '/database/tidb/sql/percolator' },
                ],
            },
            {
                text: '集群管理与运维',
                link: '/database/tidb/ops/',
                collapsed: true,
                items: [
                    { text: 'PD 调度组件', link: '/database/tidb/ops/pd-schedule' },
                    { text: 'TiDB 扩容与缩容', link: '/database/tidb/ops/scale' },
                    { text: 'Binlog 与 DM', link: '/database/tidb/ops/binlog-dm' },
                    { text: '备份恢复 BR', link: '/database/tidb/ops/backup' },
                    { text: '性能监控', link: '/database/tidb/ops/monitor' },
                    { text: '故障排查与优化', link: '/database/tidb/ops/troubleshoot' },
                ],
            },
            {
                text: 'TiFlash 与实时分析',
                link: '/database/tidb/analytics/',
                collapsed: true,
                items: [
                    { text: 'TiFlash 列式存储', link: '/database/tidb/analytics/tiflash' },
                    { text: 'HTAP 实战', link: '/database/tidb/analytics/htap-practice' },
                    { text: 'TiSpark', link: '/database/tidb/analytics/tispark' },
                ],
            },
            { text: 'TiDB 面试高频问题', link: '/database/tidb/interview-summary' },
        ],
    },
    {
        text: '达梦数据库',
        link: '/database/dameng/',
        items: [
            {
                text: '达梦数据库基础',
                link: '/database/dameng/basic/',
                collapsed: true,
                items: [
                    { text: 'DM 概述与架构', link: '/database/dameng/basic/overview' },
                    { text: 'DM 物理结构', link: '/database/dameng/basic/physical-structure' },
                    { text: 'DM 逻辑结构', link: '/database/dameng/basic/logical-structure' },
                    { text: 'DM 兼容性对比', link: '/database/dameng/basic/compatibility' },
                    { text: 'DM 安装与配置', link: '/database/dameng/basic/install' },
                ],
            },
            {
                text: '存储引擎与索引',
                link: '/database/dameng/storage/',
                collapsed: true,
                items: [
                    { text: 'DM 堆表与 HTSP', link: '/database/dameng/storage/table-type' },
                    { text: 'DM 索引类型', link: '/database/dameng/storage/index-type' },
                    { text: 'DM 索引创建原则', link: '/database/dameng/storage/index-design' },
                    { text: 'DM 表分区', link: '/database/dameng/storage/partition' },
                ],
            },
            {
                text: '事务与并发控制',
                link: '/database/dameng/transaction/',
                collapsed: true,
                items: [
                    { text: 'DM 事务管理 MVCC', link: '/database/dameng/transaction/transaction' },
                    { text: 'DM 锁机制', link: '/database/dameng/transaction/lock' },
                    { text: 'DM 隔离级别', link: '/database/dameng/transaction/isolation' },
                    { text: 'DM 多版本并发控制', link: '/database/dameng/transaction/mvcc' },
                ],
            },
            {
                text: '高可用与集群',
                link: '/database/dameng/cluster/',
                collapsed: true,
                items: [
                    { text: 'DM 数据守护', link: '/database/dameng/cluster/data-guard' },
                    { text: 'DM 主备配置', link: '/database/dameng/cluster/primary-standby' },
                    { text: 'DM 读写分离集群', link: '/database/dameng/cluster/read-write-cluster' },
                    { text: 'DM MPP 集群', link: '/database/dameng/cluster/mpp' },
                    { text: 'DM 高可用故障切换', link: '/database/dameng/cluster/ha' },
                ],
            },
            {
                text: '运维与安全',
                link: '/database/dameng/ops/',
                collapsed: true,
                items: [
                    { text: 'DM 备份与恢复', link: '/database/dameng/ops/backup' },
                    { text: 'DM 作业调度', link: '/database/dameng/ops/job' },
                    { text: 'DM 安全体系', link: '/database/dameng/ops/security' },
                    { text: 'DM SQL 性能分析', link: '/database/dameng/ops/sql-analyze' },
                    { text: 'DM 数据库迁移', link: '/database/dameng/ops/migration' },
                ],
            },
            { text: '达梦面试高频问题', link: '/database/dameng/interview-summary' },
        ],
    },
    {
        text: 'PostgreSQL',
        link: '/database/postgresql/',
        items: [
            {
                text: 'PostgreSQL 基础',
                link: '/database/postgresql/basic/',
                collapsed: true,
                items: [
                    { text: 'PostgreSQL 概述', link: '/database/postgresql/basic/overview' },
                    { text: 'vs MySQL 核心差异', link: '/database/postgresql/basic/mysql-compare' },
                    { text: 'PostgreSQL 架构', link: '/database/postgresql/basic/architecture' },
                    { text: '常用数据类型', link: '/database/postgresql/basic/data-type' },
                    { text: '分页查询', link: '/database/postgresql/basic/pagination' },
                ],
            },
            {
                text: 'MVCC 与事务',
                link: '/database/postgresql/mvcc/',
                collapsed: true,
                items: [
                    { text: 'MVCC 原理', link: '/database/postgresql/mvcc/mvcc' },
                    { text: '事务隔离级别', link: '/database/postgresql/mvcc/isolation' },
                    { text: '多版本实现 VACUUM', link: '/database/postgresql/mvcc/vacuum' },
                    { text: '锁机制', link: '/database/postgresql/mvcc/lock' },
                    { text: '事务回滚 savepoint', link: '/database/postgresql/mvcc/transaction' },
                ],
            },
            {
                text: '索引体系',
                link: '/database/postgresql/index/',
                collapsed: true,
                items: [
                    { text: '索引类型', link: '/database/postgresql/index/index-type' },
                    { text: '复合索引与最左前缀', link: '/database/postgresql/index/composite-index' },
                    { text: '表达式索引函数索引', link: '/database/postgresql/index/expression-index' },
                    { text: '索引失效与 EXPLAIN', link: '/database/postgresql/index/index-invalid' },
                    { text: '索引膨胀与 REINDEX', link: '/database/postgresql/index/index-bloat' },
                    { text: '全文检索', link: '/database/postgresql/index/fulltext' },
                ],
            },
            {
                text: '性能优化',
                link: '/database/postgresql/optimize/',
                collapsed: true,
                items: [
                    { text: '执行计划分析', link: '/database/postgresql/optimize/explain' },
                    { text: '慢查询分析', link: '/database/postgresql/optimize/slow-query' },
                    { text: '统计信息与成本估算', link: '/database/postgresql/optimize/statistics' },
                    { text: '连接池 PgBouncer', link: '/database/postgresql/optimize/connection-pool' },
                    { text: '分区表类型', link: '/database/postgresql/optimize/partition' },
                    { text: '并行查询', link: '/database/postgresql/optimize/parallel-query' },
                    { text: '性能监控', link: '/database/postgresql/optimize/monitor' },
                ],
            },
            {
                text: '高级特性',
                link: '/database/postgresql/advanced/',
                collapsed: true,
                items: [
                    { text: '触发器与规则系统', link: '/database/postgresql/advanced/trigger' },
                    { text: '存储过程 PL/pgSQL', link: '/database/postgresql/advanced/plpgsql' },
                    { text: '函数重载与操作符', link: '/database/postgresql/advanced/overload' },
                    { text: '窗口函数', link: '/database/postgresql/advanced/window-function' },
                    { text: 'CTE 与递归查询', link: '/database/postgresql/advanced/cte' },
                    { text: 'JSON 数据类型', link: '/database/postgresql/advanced/json' },
                    { text: '空间数据库', link: '/database/postgresql/advanced/postgis' },
                ],
            },
            {
                text: '高可用与集群',
                link: '/database/postgresql/cluster/',
                collapsed: true,
                items: [
                    { text: '流复制原理', link: '/database/postgresql/cluster/streaming-replication' },
                    { text: '主从切换故障转移', link: '/database/postgresql/cluster/failover' },
                    { text: '逻辑复制 vs 物理复制', link: '/database/postgresql/cluster/logical-replication' },
                    { text: 'Citus 分布式集群', link: '/database/postgresql/cluster/citus' },
                    { text: '备份与恢复', link: '/database/postgresql/cluster/backup' },
                    { text: '高可用方案', link: '/database/postgresql/cluster/ha-solution' },
                ],
            },
            { text: 'PostgreSQL 面试题', link: '/database/postgresql/interview-summary' },
        ],
    },
    {
        text: 'Oracle',
        link: '/database/oracle/',
        items: [
            {
                text: 'Oracle 基础',
                link: '/database/oracle/basic/',
                collapsed: true,
                items: [
                    { text: 'Oracle 数据库概述', link: '/database/oracle/basic/overview' },
                    { text: 'Oracle 实例与数据库', link: '/database/oracle/basic/instance' },
                    { text: 'Oracle 物理结构', link: '/database/oracle/basic/physical-structure' },
                    { text: 'Oracle 逻辑结构', link: '/database/oracle/basic/logical-structure' },
                    { text: 'Oracle SGA 与 PGA', link: '/database/oracle/basic/sga-pga' },
                    { text: 'Oracle 后台进程', link: '/database/oracle/basic/background-process' },
                ],
            },
            {
                text: 'SQL 与 PL/SQL',
                link: '/database/oracle/sql/',
                collapsed: true,
                items: [
                    { text: 'Oracle SQL 基础', link: '/database/oracle/sql/sql-basics' },
                    { text: 'Oracle 常用函数', link: '/database/oracle/sql/functions' },
                    { text: '分页查询', link: '/database/oracle/sql/pagination' },
                    { text: 'PL/SQL 块结构', link: '/database/oracle/sql/plsql-block' },
                    { text: '存储过程与函数', link: '/database/oracle/sql/procedure-function' },
                    { text: 'PL/SQL 触发器', link: '/database/oracle/sql/trigger' },
                    { text: 'PL/SQL 游标', link: '/database/oracle/sql/cursor' },
                    { text: 'PL/SQL 集合类型', link: '/database/oracle/sql/collection' },
                    { text: 'PL/SQL 异常处理', link: '/database/oracle/sql/exception' },
                    { text: 'Oracle 序列与同义词', link: '/database/oracle/sql/sequence-synonym' },
                ],
            },
            {
                text: '存储与索引',
                link: '/database/oracle/storage/',
                collapsed: true,
                items: [
                    { text: 'Oracle 表类型', link: '/database/oracle/storage/table-type' },
                    { text: 'Oracle 索引类型', link: '/database/oracle/storage/index-type' },
                    { text: '索引组织表 IOT', link: '/database/oracle/storage/iot' },
                    { text: '分区表', link: '/database/oracle/storage/partition' },
                    { text: '表压缩', link: '/database/oracle/storage/compression' },
                ],
            },
            {
                text: '事务与并发',
                link: '/database/oracle/transaction/',
                collapsed: true,
                items: [
                    { text: 'Oracle 事务管理', link: '/database/oracle/transaction/transaction' },
                    { text: 'Oracle 锁机制', link: '/database/oracle/transaction/lock' },
                    { text: '隔离级别 MVCC', link: '/database/oracle/transaction/isolation' },
                    { text: '闪回技术', link: '/database/oracle/transaction/flashback' },
                    { text: '乐观锁与悲观锁', link: '/database/oracle/transaction/optimistic-pessimistic' },
                ],
            },
            {
                text: '性能优化',
                link: '/database/oracle/optimize/',
                collapsed: true,
                items: [
                    { text: '执行计划分析', link: '/database/oracle/optimize/explain' },
                    { text: 'SQL 性能分析', link: '/database/oracle/optimize/sql-tuning' },
                    { text: '统计信息', link: '/database/oracle/optimize/statistics' },
                    { text: '绑定变量 ACS', link: '/database/oracle/optimize/bind-variable' },
                    { text: 'AWR ASH ADDM', link: '/database/oracle/optimize/awr-ash' },
                    { text: '连接池与共享服务器', link: '/database/oracle/optimize/shared-server' },
                    { text: '并行查询 DML', link: '/database/oracle/optimize/parallel' },
                ],
            },
            {
                text: '高可用与集群',
                link: '/database/oracle/cluster/',
                collapsed: true,
                items: [
                    { text: 'Data Guard 原理', link: '/database/oracle/cluster/data-guard' },
                    { text: 'Oracle RAC 集群', link: '/database/oracle/cluster/rac' },
                    { text: 'Oracle RAC 高可用', link: '/database/oracle/cluster/rac-ha' },
                    { text: 'ASM 存储管理', link: '/database/oracle/cluster/asm' },
                    { text: 'GoldenGate 同步', link: '/database/oracle/cluster/goldengate' },
                    { text: 'RMAN 备份恢复', link: '/database/oracle/cluster/rman' },
                    { text: 'Exadata 一体机', link: '/database/oracle/cluster/exadata' },
                ],
            },
            { text: 'Oracle 面试高频问题', link: '/database/oracle/interview-summary' },
        ],
    },
    {
        text: 'SQL Server',
        link: '/database/sqlserver/',
        items: [
            {
                text: 'SQL Server 基础',
                link: '/database/sqlserver/basic/',
                collapsed: true,
                items: [
                    { text: 'SQL Server 架构', link: '/database/sqlserver/basic/architecture' },
                    { text: 'Page 与 Extent', link: '/database/sqlserver/basic/page-extent' },
                    { text: '数据库文件', link: '/database/sqlserver/basic/file-group' },
                    { text: '事务日志 WAL', link: '/database/sqlserver/basic/transaction-log' },
                    { text: 'T-SQL 基础', link: '/database/sqlserver/basic/tsql-basics' },
                    { text: '分页 OFFSET FETCH', link: '/database/sqlserver/basic/pagination' },
                ],
            },
            {
                text: '索引与查询',
                link: '/database/sqlserver/index/',
                collapsed: true,
                items: [
                    { text: 'B-Tree 索引结构', link: '/database/sqlserver/index/index-structure' },
                    { text: '聚集 vs 非聚集索引', link: '/database/sqlserver/index/clustered-index' },
                    { text: '索引类型', link: '/database/sqlserver/index/index-type' },
                    { text: '执行计划分析', link: '/database/sqlserver/index/explain' },
                    { text: '慢查询优化', link: '/database/sqlserver/index/slow-query' },
                    { text: '统计信息重编译', link: '/database/sqlserver/index/statistics' },
                ],
            },
            {
                text: '事务与锁',
                link: '/database/sqlserver/transaction/',
                collapsed: true,
                items: [
                    { text: '事务日志 WAL', link: '/database/sqlserver/transaction/wal' },
                    { text: '隔离级别', link: '/database/sqlserver/transaction/isolation' },
                    { text: '锁模式', link: '/database/sqlserver/transaction/lock-mode' },
                    { text: '死锁排查优化', link: '/database/sqlserver/transaction/deadlock' },
                    { text: '乐观并发', link: '/database/sqlserver/transaction/optimistic-concurrency' },
                ],
            },
            {
                text: '性能与调优',
                link: '/database/sqlserver/optimize/',
                collapsed: true,
                items: [
                    { text: '性能监控 DMV XEvent', link: '/database/sqlserver/optimize/dmv' },
                    { text: '查询优化器', link: '/database/sqlserver/optimize/query-optimizer' },
                    { text: '内存管理', link: '/database/sqlserver/optimize/memory' },
                    { text: '表分区', link: '/database/sqlserver/optimize/partition' },
                    { text: '内存优化表', link: '/database/sqlserver/optimize/in-memory' },
                    { text: '列存储索引', link: '/database/sqlserver/optimize/columnstore' },
                ],
            },
            {
                text: '高可用与集群',
                link: '/database/sqlserver/cluster/',
                collapsed: true,
                items: [
                    { text: 'Always On 可用性组', link: '/database/sqlserver/cluster/always-on' },
                    { text: '故障转移群集 FCI', link: '/database/sqlserver/cluster/fci' },
                    { text: '数据库镜像', link: '/database/sqlserver/cluster/mirroring' },
                    { text: '复制：快照事务合并', link: '/database/sqlserver/cluster/replication' },
                    { text: '备份策略', link: '/database/sqlserver/cluster/backup' },
                    { text: '数据库迁移', link: '/database/sqlserver/cluster/migration' },
                ],
            },
            { text: 'SQL Server 面试题', link: '/database/sqlserver/interview-summary' },
        ],
    },
    {
        text: 'SQLite',
        link: '/database/sqlite/',
        items: [
            { text: 'SQLite 概述', link: '/database/sqlite/overview' },
            { text: 'SQLite 文件结构', link: '/database/sqlite/file-structure' },
            { text: '事务模型与 WAL', link: '/database/sqlite/transaction' },
            { text: '索引与查询优化', link: '/database/sqlite/index' },
            { text: '并发限制', link: '/database/sqlite/concurrency' },
            { text: 'SQLite 与 Android', link: '/database/sqlite/android' },
            { text: '适用场景与局限', link: '/database/sqlite/limitation' },
            { text: 'SQLite 面试题', link: '/database/sqlite/interview-summary' },
        ],
    },
    {
        text: 'MariaDB',
        link: '/database/mariadb/',
        items: [
            {
                text: 'MariaDB 基础',
                link: '/database/mariadb/basic/',
                collapsed: true,
                items: [
                    { text: 'MariaDB 概述', link: '/database/mariadb/basic/overview' },
                    { text: 'vs MySQL 核心差异', link: '/database/mariadb/basic/mysql-compare' },
                    { text: '存储引擎', link: '/database/mariadb/basic/engine' },
                    { text: '新增特性', link: '/database/mariadb/basic/new-feature' },
                ],
            },
            {
                text: 'MariaDB 高级特性',
                link: '/database/mariadb/advanced/',
                collapsed: true,
                items: [
                    { text: '线程池插件', link: '/database/mariadb/advanced/thread-pool' },
                    { text: 'CONNECT 存储引擎', link: '/database/mariadb/advanced/connect-engine' },
                    { text: '虚拟列与序列', link: '/database/mariadb/advanced/virtual-column' },
                    { text: '窗口函数与 CTE', link: '/database/mariadb/advanced/window-function' },
                    { text: '审计插件', link: '/database/mariadb/advanced/audit' },
                ],
            },
            {
                text: '集群与高可用',
                link: '/database/mariadb/cluster/',
                collapsed: true,
                items: [
                    { text: 'Galera Cluster 原理', link: '/database/mariadb/cluster/galera' },
                    { text: 'Galera 节点故障恢复', link: '/database/mariadb/cluster/galera-node' },
                    { text: '主从复制与 GTID', link: '/database/mariadb/cluster/replication' },
                    { text: 'MaxScale 读写分离', link: '/database/mariadb/cluster/maxscale' },
                    { text: '备份与恢复', link: '/database/mariadb/cluster/backup' },
                ],
            },
            { text: 'MariaDB 面试题', link: '/database/mariadb/interview-summary' },
        ],
    },
    {
        text: '时序数据库',
        link: '/database/tsdb/',
        items: [
            {
                text: '时序数据库基础',
                link: '/database/tsdb/basic/',
                collapsed: true,
                items: [
                    { text: 'TSDB 核心概念', link: '/database/tsdb/basic/concept' },
                    { text: 'vs 关系数据库', link: '/database/tsdb/basic/rdb-compare' },
                    { text: '时序数据库选型', link: '/database/tsdb/basic/select' },
                ],
            },
            {
                text: 'InfluxDB',
                link: '/database/tsdb/influxdb/',
                collapsed: true,
                items: [
                    { text: 'InfluxDB 数据模型', link: '/database/tsdb/influxdb/data-model' },
                    { text: 'Line Protocol', link: '/database/tsdb/influxdb/line-protocol' },
                    { text: '连续查询与降采样', link: '/database/tsdb/influxdb/continuous-query' },
                    { text: '保留策略', link: '/database/tsdb/influxdb/retention-policy' },
                    { text: '倒排索引 TSM', link: '/database/tsdb/influxdb/tsm' },
                    { text: 'InfluxQL 与 Flux', link: '/database/tsdb/influxdb/influxql-flux' },
                    { text: 'TIG 技术栈', link: '/database/tsdb/influxdb/telegraf' },
                ],
            },
            {
                text: 'TDengine',
                link: '/database/tsdb/tdengine/',
                collapsed: true,
                items: [
                    { text: '超级表与子表设计', link: '/database/tsdb/tdengine/supertable' },
                    { text: '写入性能与集群', link: '/database/tsdb/tdengine/cluster' },
                    { text: '查询与降采样', link: '/database/tsdb/tdengine/query' },
                    { text: 'vs InfluxDB', link: '/database/tsdb/tdengine/compare' },
                ],
            },
            {
                text: 'Prometheus',
                link: '/database/tsdb/prometheus/',
                collapsed: true,
                items: [
                    { text: '数据模型 metrics', link: '/database/tsdb/prometheus/data-model' },
                    { text: 'Pull vs Push 采集', link: '/database/tsdb/prometheus/pull-push' },
                    { text: 'TSDB 与远程存储', link: '/database/tsdb/prometheus/storage' },
                    { text: 'PromQL 查询', link: '/database/tsdb/prometheus/promql' },
                    { text: '告警规则 AlertManager', link: '/database/tsdb/prometheus/alert' },
                    { text: 'K8s 服务发现', link: '/database/tsdb/prometheus/k8s-discovery' },
                ],
            },
        ],
    },
    {
        text: 'HBase',
        link: '/database/hbase/',
        items: [
            {
                text: 'HBase 基础',
                link: '/database/hbase/basic/',
                collapsed: true,
                items: [
                    { text: 'HBase 整体架构', link: '/database/hbase/basic/architecture' },
                    { text: 'HBase 数据模型', link: '/database/hbase/basic/data-model' },
                    { text: 'RowKey 设计原则', link: '/database/hbase/basic/rowkey-design' },
                    { text: 'CAP 权衡', link: '/database/hbase/basic/cap' },
                    { text: 'vs 关系数据库', link: '/database/hbase/basic/rdb-compare' },
                ],
            },
            {
                text: 'HBase 存储原理',
                link: '/database/hbase/storage/',
                collapsed: true,
                items: [
                    { text: '物理存储 HFile', link: '/database/hbase/storage/hfile' },
                    { text: '写流程 WAL', link: '/database/hbase/storage/write-flow' },
                    { text: '读流程 BlockCache', link: '/database/hbase/storage/read-flow' },
                    { text: 'Compaction', link: '/database/hbase/storage/compaction' },
                    { text: 'Region 分裂负载均衡', link: '/database/hbase/storage/region-split' },
                    { text: '布隆过滤器', link: '/database/hbase/storage/bloom-filter' },
                ],
            },
            {
                text: 'HBase 集群与运维',
                link: '/database/hbase/ops/',
                collapsed: true,
                items: [
                    { text: '预分区与热点问题', link: '/database/hbase/ops/hotspot' },
                    { text: '协处理器', link: '/database/hbase/ops/coprocessor' },
                    { text: '快照与备份恢复', link: '/database/hbase/ops/snapshot' },
                    { text: '性能监控', link: '/database/hbase/ops/monitor' },
                    { text: '故障排查优化', link: '/database/hbase/ops/troubleshoot' },
                ],
            },
            {
                text: 'HBase 应用与生态',
                link: '/database/hbase/ecosystem/',
                collapsed: true,
                items: [
                    { text: 'HBase API', link: '/database/hbase/ecosystem/api' },
                    { text: 'Phoenix SQL 层', link: '/database/hbase/ecosystem/phoenix' },
                    { text: 'Hive/Hadoop 集成', link: '/database/hbase/ecosystem/hive' },
                    { text: '二级索引', link: '/database/hbase/ecosystem/secondary-index' },
                    { text: '大数据场景应用', link: '/database/hbase/ecosystem/use-case' },
                ],
            },
            { text: 'HBase 面试题', link: '/database/hbase/interview-summary' },
        ],
    },
]
