export const designSidebar = [
    {
        text: "设计模式",
        link: "/design/patterns/",
        items: [
            { text: "设计模式六大原则", link: "/design/patterns/principles" },
            { text: "单例模式（所有写法对比）", link: "/design/patterns/singleton" },
            { text: "单例模式线程安全与序列化问题", link: "/design/patterns/singleton-security" },
            { text: "工厂模式（简单工厂/工厂方法/抽象工厂）", link: "/design/patterns/factory" },
            { text: "建造者模式", link: "/design/patterns/builder" },
            { text: "原型模式", link: "/design/patterns/prototype" },
            { text: "代理模式（静态/动态/CGLIB）", link: "/design/patterns/proxy" },
            { text: "适配器模式", link: "/design/patterns/adapter" },
            { text: "装饰器模式", link: "/design/patterns/decorator" },
            { text: "外观模式", link: "/design/patterns/facade" },
            { text: "策略模式", link: "/design/patterns/strategy" },
            { text: "模板方法模式", link: "/design/patterns/template" },
            { text: "观察者模式", link: "/design/patterns/observer" },
            { text: "责任链模式", link: "/design/patterns/chain" },
            { text: "状态模式", link: "/design/patterns/state" },
            { text: "命令模式", link: "/design/patterns/command" },
            { text: "迭代器模式", link: "/design/patterns/iterator" },
            { text: "访问者模式", link: "/design/patterns/visitor" },
            { text: "设计模式在框架源码中的应用", link: "/design/patterns/in-frameworks" },
        ],
    },
    {
        text: "架构模式",
        link: "/design/architectural/",
        items: [
            { text: "MVC 模式", link: "/design/architectural/mvc" },
            { text: "MVP 与 MVVM 模式", link: "/design/architectural/mvp-mvvm" },
            { text: "分层架构", link: "/design/architectural/layered" },
            { text: "六边形架构（端口与适配器）", link: "/design/architectural/hexagonal" },
            { text: "洋葱架构", link: "/design/architectural/onion" },
            { text: "整洁架构（Clean Architecture）", link: "/design/architectural/clean" },
            { text: "DDD 领域驱动设计", link: "/design/architectural/ddd" },
            { text: "DDD 核心概念（实体/值对象/聚合/领域事件）", link: "/design/architectural/ddd-concepts" },
            { text: "CQRS 命令查询职责分离", link: "/design/architectural/cqrs" },
            { text: "CQRS 与 DDD 结合", link: "/design/architectural/cqrs-ddd" },
            { text: "事件驱动架构（EDA）", link: "/design/architectural/eda" },
            { text: "事件溯源（Event Sourcing）", link: "/design/architectural/event-sourcing" },
            { text: "CQRS + Event Sourcing 实战", link: "/design/architectural/cqrs-es" },
            { text: "微内核架构", link: "/design/architectural/microkernel" },
            { text: "管道-过滤器架构", link: "/design/architectural/pipe-filter" },
            { text: "架构模式选型对比", link: "/design/architectural/comparison" },
        ],
    },
    {
        text: "系统设计",
        link: "/design/system-design/",
        items: [
            { text: "系统设计方法论", link: "/design/system-design/methodology" },
            { text: "系统设计面试解题框架", link: "/design/system-design/interview-framework" },
            { text: "容量估算与延迟数据", link: "/design/system-design/capacity-planning" },
            { text: "秒杀系统设计", link: "/design/system-design/seckill" },
            { text: "秒杀系统热点问题处理", link: "/design/system-design/seckill-hotspot" },
            { text: "短链系统设计", link: "/design/system-design/short-url" },
            { text: "短链系统发号器设计", link: "/design/system-design/short-url-id" },
            { text: "IM 即时通讯系统设计", link: "/design/system-design/im" },
            { text: "IM 消息可靠性保证", link: "/design/system-design/im-reliability" },
            { text: "支付系统设计", link: "/design/system-design/payment" },
            { text: "支付系统对账设计", link: "/design/system-design/payment-reconciliation" },
            { text: "附近的人（LBS）系统设计", link: "/design/system-design/lbs" },
            { text: "Feed 流系统设计", link: "/design/system-design/feed" },
            { text: "Feed 流推拉模式对比", link: "/design/system-design/feed-push-pull" },
            { text: "评论系统设计", link: "/design/system-design/comment" },
            { text: "排行榜系统设计", link: "/design/system-design/leaderboard" },
            { text: "分布式 ID 生成器设计", link: "/design/system-design/distributed-id" },
            { text: "配置中心设计", link: "/design/system-design/config-center" },
            { text: "定时任务调度系统设计", link: "/design/system-design/scheduler" },
            { text: "系统设计核心组件选型", link: "/design/system-design/component-selection" },
        ],
    },
];