export const devopsSidebar = [
  {
    text: 'Docker',
    link: '/devops/docker/',
    items: [
      {
        text: 'Docker 基础',
        link: '/devops/docker/basic/',
        collapsed: true,
        items: [
          { text: 'Docker vs 虚拟机', link: '/devops/docker/basic/vm-vs-docker' },
          { text: 'Docker 核心概念', link: '/devops/docker/basic/core-concept' },
          { text: 'Dockerfile 指令详解', link: '/devops/docker/basic/dockerfile' },
          { text: 'Docker 镜像分层与 COW', link: '/devops/docker/basic/image-layer' },
          { text: 'Dockerfile 最佳实践', link: '/devops/docker/basic/dockerfile-best' },
          { text: 'Dockerfile .dockerignore', link: '/devops/docker/basic/dockerignore' },
          { text: 'Docker 数据持久化', link: '/devops/docker/basic/volume' },
          { text: 'Docker 网络模式', link: '/devops/docker/basic/network' },
          { text: 'Docker Compose 编排', link: '/devops/docker/basic/compose' },
          { text: 'Docker Registry 私有仓库', link: '/devops/docker/basic/registry' },
          { text: 'Harbor 企业级镜像仓库', link: '/devops/docker/basic/harbor' },
        ],
      },
      {
        text: 'Docker 进阶',
        link: '/devops/docker/advanced/',
        collapsed: true,
        items: [
          { text: '容器通信原理', link: '/devops/docker/advanced/container-communication' },
          { text: 'Docker 存储驱动', link: '/devops/docker/advanced/storage-driver' },
          { text: '容器资源限制', link: '/devops/docker/advanced/resource-limit' },
          { text: 'Docker 安全配置', link: '/devops/docker/advanced/security' },
          { text: 'Docker 健康检查', link: '/devops/docker/advanced/healthcheck' },
          { text: 'Docker 构建缓存', link: '/devops/docker/advanced/build-cache' },
        ],
      },
      {
        text: 'Docker Swarm',
        link: '/devops/docker/swarm/',
        collapsed: true,
        items: [
          { text: 'Docker Swarm 架构', link: '/devops/docker/swarm/swarm-architecture' },
          { text: 'Docker Swarm 服务部署', link: '/devops/docker/swarm/swarm-deploy' },
          { text: 'Docker Swarm 负载均衡', link: '/devops/docker/swarm/swarm-lb' },
        ],
      },
      { text: 'Docker 面试高频问题', link: '/devops/docker/interview-summary' },
    ],
  },
  {
    text: 'K8s',
    link: '/devops/k8s/',
    items: [
      {
        text: 'Kubernetes 基础',
        link: '/devops/k8s/basic/',
        collapsed: true,
        items: [
          { text: 'Kubernetes 架构', link: '/devops/k8s/basic/architecture' },
          { text: 'Kubernetes 核心概念', link: '/devops/k8s/basic/core-concept' },
          { text: 'Pod 生命周期', link: '/devops/k8s/basic/pod-lifecycle' },
          { text: 'Pod 资源配置', link: '/devops/k8s/basic/pod-resource' },
          { text: 'Pod 调度机制', link: '/devops/k8s/basic/pod-scheduling' },
          { text: 'Pod 健康检查', link: '/devops/k8s/basic/probe' },
        ],
      },
      {
        text: 'Kubernetes 核心资源',
        link: '/devops/k8s/workload/',
        collapsed: true,
        items: [
          { text: 'Deployment 部署策略', link: '/devops/k8s/workload/deployment' },
          { text: 'Deployment 扩缩容', link: '/devops/k8s/workload/hpa' },
          { text: 'StatefulSet 有状态应用', link: '/devops/k8s/workload/statefulset' },
          { text: 'StatefulSet 存储与网络', link: '/devops/k8s/workload/statefulset-stable' },
          { text: 'DaemonSet 守护进程集', link: '/devops/k8s/workload/daemonset' },
          { text: 'Job 与 CronJob 批任务', link: '/devops/k8s/workload/job-cronjob' },
        ],
      },
      {
        text: 'Kubernetes 网络',
        link: '/devops/k8s/network/',
        collapsed: true,
        items: [
          { text: 'Kubernetes 网络模型', link: '/devops/k8s/network/network-model' },
          { text: 'Service 类型对比', link: '/devops/k8s/network/service-type' },
          { text: 'Ingress 七层路由', link: '/devops/k8s/network/ingress' },
          { text: 'CNI 网络插件对比', link: '/devops/k8s/network/cni' },
          { text: 'Service 负载均衡实现', link: '/devops/k8s/network/service-lb' },
          { text: 'Pod 网络通信', link: '/devops/k8s/network/pod-communication' },
        ],
      },
      {
        text: 'Kubernetes 存储',
        link: '/devops/k8s/storage/',
        collapsed: true,
        items: [
          { text: 'Volume 类型对比', link: '/devops/k8s/storage/volume' },
          { text: 'PV 与 PVC', link: '/devops/k8s/storage/pv-pvc' },
          { text: 'StorageClass 动态供给', link: '/devops/k8s/storage/storage-class' },
          { text: 'ConfigMap 与 Secret', link: '/devops/k8s/storage/configmap-secret' },
          { text: 'Secret 类型详解', link: '/devops/k8s/storage/secret-type' },
        ],
      },
      {
        text: 'Kubernetes 安全',
        link: '/devops/k8s/security/',
        collapsed: true,
        items: [
          { text: 'RBAC 权限控制', link: '/devops/k8s/security/rbac' },
          { text: 'Security Context 配置', link: '/devops/k8s/security/security-context' },
          { text: 'ServiceAccount 配置', link: '/devops/k8s/security/serviceaccount' },
          { text: 'NetworkPolicy 网络隔离', link: '/devops/k8s/security/network-policy-security' },
        ],
      },
      {
        text: 'Kubernetes 运维',
        link: '/devops/k8s/ops/',
        collapsed: true,
        items: [
          { text: 'kubectl 命令速查', link: '/devops/k8s/ops/kubectl' },
          { text: 'K8s Dashboard 可视化', link: '/devops/k8s/ops/dashboard' },
          { text: 'K8s 集群高可用部署', link: '/devops/k8s/ops/ha-deployment' },
          { text: 'HPA 进阶：自定义指标', link: '/devops/k8s/ops/hpa-advanced' },
          { text: 'VPA 垂直扩缩容', link: '/devops/k8s/ops/vpa' },
          { text: '监控与可视化', link: '/devops/k8s/ops/prometheus' },
        ],
      },
      {
        text: 'Helm',
        link: '/devops/k8s/helm/',
        collapsed: true,
        items: [
          { text: 'Helm 概念', link: '/devops/k8s/helm/helm' },
          { text: 'Helm 模板语法', link: '/devops/k8s/helm/helm-template' },
          { text: 'Helm Hook 生命周期', link: '/devops/k8s/helm/helm-hook' },
          { text: 'Helmfile 与 GitOps', link: '/devops/k8s/helm/helmfile' },
        ],
      },
      {
        text: '云原生生态',
        link: '/devops/k8s/cloud-native/',
        collapsed: true,
        items: [
          { text: '云原生核心概念', link: '/devops/k8s/cloud-native/cloud-native' },
          { text: 'Service Mesh 架构', link: '/devops/k8s/cloud-native/service-mesh' },
          { text: 'K8s 部署策略对比', link: '/devops/k8s/cloud-native/deployment-strategy' },
          { text: 'GitOps 工具对比', link: '/devops/k8s/cloud-native/kustomize-gitops' },
        ],
      },
      { text: 'Kubernetes 面试高频问题', link: '/devops/k8s/interview-summary' },
    ],
  },
  {
    text: '构建工具',
    link: '/devops/build-tool/',
    items: [
      {
        text: '构建工具基础',
        link: '/devops/build-tool/basic/',
        collapsed: true,
        items: [
          { text: '构建工具发展历程', link: '/devops/build-tool/basic/history' },
          { text: 'Maven vs Gradle 选型', link: '/devops/build-tool/basic/maven-vs-gradle' },
        ],
      },
      {
        text: 'Maven',
        link: '/devops/build-tool/maven/',
        collapsed: true,
        items: [
          { text: 'Maven 核心概念', link: '/devops/build-tool/maven/maven-concept' },
          { text: 'Maven 依赖冲突解决', link: '/devops/build-tool/maven/maven-dependency' },
          { text: 'Maven 依赖作用域', link: '/devops/build-tool/maven/maven-scope' },
          { text: 'Maven 生命周期', link: '/devops/build-tool/maven/maven-lifecycle' },
          { text: 'Maven 插件机制', link: '/devops/build-tool/maven/maven-plugin' },
          { text: 'Maven pom.xml 核心配置', link: '/devops/build-tool/maven/maven-pom' },
          { text: 'Maven 多模块项目', link: '/devops/build-tool/maven/maven-multi-module' },
          { text: 'Maven 仓库配置', link: '/devops/build-tool/maven/maven-repository' },
          { text: 'Maven BOM 用法', link: '/devops/build-tool/maven/maven-bom' },
          { text: 'Maven 常用命令', link: '/devops/build-tool/maven/maven-command' },
          { text: 'Maven 构建性能优化', link: '/devops/build-tool/maven/maven-performance' },
        ],
      },
      {
        text: 'Gradle',
        link: '/devops/build-tool/gradle/',
        collapsed: true,
        items: [
          { text: 'Gradle 核心优势', link: '/devops/build-tool/gradle/gradle-concept' },
          { text: 'Gradle 构建脚本', link: '/devops/build-tool/gradle/gradle-script' },
          { text: 'Gradle 依赖管理', link: '/devops/build-tool/gradle/gradle-dependency' },
          { text: 'Gradle DSL 语法', link: '/devops/build-tool/gradle/gradle-dsl' },
          { text: 'Gradle 增量构建', link: '/devops/build-tool/gradle/gradle-incremental' },
          { text: 'Gradle 多项目构建', link: '/devops/build-tool/gradle/gradle-multi-project' },
          { text: 'Gradle 插件机制', link: '/devops/build-tool/gradle/gradle-plugin' },
          { text: 'Gradle 与 Maven 互操作', link: '/devops/build-tool/gradle/gradle-maven-interop' },
          { text: 'Gradle 守护进程', link: '/devops/build-tool/gradle/gradle-daemon' },
          { text: 'Gradle 常用命令', link: '/devops/build-tool/gradle/gradle-command' },
        ],
      },
      {
        text: '构建最佳实践',
        link: '/devops/build-tool/best-practice/',
        collapsed: true,
        items: [
          { text: '依赖版本管理规范', link: '/devops/build-tool/best-practice/dependency-version' },
          { text: '多环境构建', link: '/devops/build-tool/best-practice/multi-env' },
          { text: '构建产物管理', link: '/devops/build-tool/best-practice/fat-jar' },
          { text: '构建安全：依赖漏洞扫描', link: '/devops/build-tool/best-practice/security' },
          { text: '构建工具面试高频问题', link: '/devops/build-tool/best-practice/interview-summary' },
        ],
      },
    ],
  },
  {
    text: 'CI/CD',
    link: '/devops/cicd/',
    items: [
      {
        text: 'Git 与版本控制',
        link: '/devops/cicd/git/',
        collapsed: true,
        items: [
          { text: 'Git 工作流对比', link: '/devops/cicd/git/git-workflow' },
          { text: 'Git 常用命令与原理', link: '/devops/cicd/git/git-command' },
          { text: 'Git 分支管理策略', link: '/devops/cicd/git/git-branch' },
          { text: 'Git 提交规范', link: '/devops/cicd/git/git-commit' },
          { text: 'Git Hooks 与 CI 集成', link: '/devops/cicd/git/git-hook' },
        ],
      },
      {
        text: 'Jenkins',
        link: '/devops/cicd/jenkins/',
        collapsed: true,
        items: [
          { text: 'Jenkins 架构', link: '/devops/cicd/jenkins/jenkins-architecture' },
          { text: 'Jenkinsfile 声明式流水线', link: '/devops/cicd/jenkins/jenkinsfile' },
          { text: 'Jenkins 插件生态', link: '/devops/cicd/jenkins/jenkins-plugin' },
          { text: 'Jenkins 与 K8s 集成', link: '/devops/cicd/jenkins/jenkins-k8s' },
          { text: 'Jenkins Blue Ocean', link: '/devops/cicd/jenkins/blue-ocean' },
        ],
      },
      {
        text: '现代 CI/CD 工具',
        link: '/devops/cicd/modern/',
        collapsed: true,
        items: [
          { text: 'GitLab CI/CD 流水线', link: '/devops/cicd/modern/gitlab-ci' },
          { text: 'GitHub Actions 工作流', link: '/devops/cicd/modern/github-actions' },
          { text: 'ArgoCD GitOps 工具', link: '/devops/cicd/modern/argocd' },
          { text: 'Tekton K8s 原生 CI/CD', link: '/devops/cicd/modern/tekton' },
          { text: 'Spinnaker 多云交付', link: '/devops/cicd/modern/spinnaker' },
          { text: 'CI/CD 工具对比', link: '/devops/cicd/modern/compare' },
        ],
      },
      {
        text: 'CI/CD 最佳实践',
        link: '/devops/cicd/best-practice/',
        collapsed: true,
        items: [
          { text: 'CI/CD 流水线设计原则', link: '/devops/cicd/best-practice/pipeline-design' },
          { text: 'SonarQube 质量检查', link: '/devops/cicd/best-practice/sonarqube' },
          { text: '容器镜像安全扫描', link: '/devops/cicd/best-practice/image-scan' },
          { text: '制品库方案', link: '/devops/cicd/best-practice/artifact' },
          { text: '蓝绿部署与金丝雀发布', link: '/devops/cicd/best-practice/blue-green' },
        ],
      },
    ],
  },
  {
    text: '容器编排对比',
    link: '/devops/orchestration/',
    items: [
      { text: '编排工具对比', link: '/devops/orchestration/compare' },
      { text: 'K8s vs Docker Compose', link: '/devops/orchestration/k8s-vs-compose' },
      { text: 'K3s 轻量级 K8s', link: '/devops/orchestration/k3s' },
      { text: 'K0s 与 MicroK8s', link: '/devops/orchestration/k0s-microk8s' },
    ],
  },
  {
    text: '自动化运维',
    link: '/devops/ops/',
    items: [
      {
        text: 'Ansible',
        link: '/devops/ops/ansible/',
        collapsed: true,
        items: [
          { text: 'Ansible 架构', link: '/devops/ops/ansible/architecture' },
          { text: 'Ansible Playbook 语法', link: '/devops/ops/ansible/playbook' },
          { text: 'Ansible Roles 与 Galaxy', link: '/devops/ops/ansible/roles' },
          { text: 'Ansible 与 K8s 集成', link: '/devops/ops/ansible/integration' },
        ],
      },
      {
        text: 'Prometheus + Grafana',
        link: '/devops/ops/monitor/',
        collapsed: true,
        items: [
          { text: 'Prometheus 架构', link: '/devops/ops/monitor/prometheus-architecture' },
          { text: 'Prometheus 服务发现', link: '/devops/ops/monitor/service-discovery' },
          { text: 'PromQL 查询语法', link: '/devops/ops/monitor/promql' },
          { text: 'Grafana 可视化与告警', link: '/devops/ops/monitor/grafana' },
          { text: 'Exporter 常用类型', link: '/devops/ops/monitor/exporter' },
          { text: 'K8s 监控方案', link: '/devops/ops/monitor/k8s-monitoring' },
        ],
      },
      {
        text: '日志系统',
        link: '/devops/ops/log/',
        collapsed: true,
        items: [
          { text: 'ELK Stack 架构', link: '/devops/ops/log/elk' },
          { text: 'EFK Stack', link: '/devops/ops/log/efk' },
          { text: 'Loki 日志聚合', link: '/devops/ops/log/loki' },
          { text: '日志收集方案对比', link: '/devops/ops/log/log-collector' },
          { text: '分布式日志追踪', link: '/devops/ops/log/distributed-log' },
        ],
      },
      { text: 'SRE 与可观测性', link: '/devops/ops/sre' },
      { text: '链路追踪对比', link: '/devops/ops/tracing' },
    ],
  },
  {
    text: 'KubeSphere',
    link: '/devops/kubesphere/',
    items: [
      {
        text: 'KubeSphere 基础',
        link: '/devops/kubesphere/basic/',
        collapsed: true,
        items: [
          { text: 'KubeSphere 概述', link: '/devops/kubesphere/basic/overview' },
          { text: 'KubeSphere 架构', link: '/devops/kubesphere/basic/architecture' },
          { text: 'KubeSphere 多租户体系', link: '/devops/kubesphere/basic/multi-tenant' },
          { text: 'KubeSphere 安装部署', link: '/devops/kubesphere/basic/install' },
        ],
      },
      {
        text: 'KubeSphere 核心功能',
        link: '/devops/kubesphere/core/',
        collapsed: true,
        items: [
          { text: 'KubeSphere 应用商店', link: '/devops/kubesphere/core/app-store' },
          { text: 'KubeSphere 流水线', link: '/devops/kubesphere/core/pipeline' },
          { text: 'KubeSphere 告警系统', link: '/devops/kubesphere/core/alerting' },
          { text: 'KubeSphere 日志收集', link: '/devops/kubesphere/core/logging' },
          { text: 'KubeSphere 审计日志', link: '/devops/kubesphere/core/audit' },
          { text: 'KubeSphere 服务网格', link: '/devops/kubesphere/core/service-mesh' },
          { text: 'KubeSphere 多租户监控', link: '/devops/kubesphere/core/monitoring' },
        ],
      },
      {
        text: 'KubeSphere DevOps',
        link: '/devops/kubesphere/devops/',
        collapsed: true,
        items: [
          { text: 'KubeSphere 流水线语法', link: '/devops/kubesphere/devops/pipeline-syntax' },
          { text: 'KubeSphere 制品仓库', link: '/devops/kubesphere/devops/registry' },
          { text: 'KubeSphere 自动化构建', link: '/devops/kubesphere/devops/build-push' },
          { text: 'KubeSphere 部署策略', link: '/devops/kubesphere/devops/deploy-strategy' },
          { text: 'KubeSphere GitOps', link: '/devops/kubesphere/devops/gitops' },
        ],
      },
      {
        text: 'KubeSphere 运维管理',
        link: '/devops/kubesphere/admin/',
        collapsed: true,
        items: [
          { text: 'KubeSphere 节点管理', link: '/devops/kubesphere/admin/node-management' },
          { text: 'KubeSphere 存储管理', link: '/devops/kubesphere/admin/storage' },
          { text: 'KubeSphere 网络管理', link: '/devops/kubesphere/admin/network' },
          { text: 'KubeSphere 集群升级', link: '/devops/kubesphere/admin/upgrade' },
          { text: 'KubeSphere 权限管理', link: '/devops/kubesphere/admin/rbac' },
          { text: 'KubeSphere 故障排查', link: '/devops/kubesphere/admin/troubleshoot' },
        ],
      },
      { text: 'KubeSphere 面试高频问题', link: '/devops/kubesphere/interview-summary' },
    ],
  },
  {
    text: '基础设施即代码（IaC）',
    link: '/devops/iac/',
    items: [
      { text: 'Terraform 基础', link: '/devops/iac/terraform' },
      { text: 'Terraform 模块化', link: '/devops/iac/terraform-module' },
      { text: 'Pulumi 云资源管理', link: '/devops/iac/pulumi' },
      { text: 'IaC 工具对比', link: '/devops/iac/compare' },
    ],
  },
]
