export const devopsSidebar = [
  {
    text: 'Docker',
    link: '/devops/docker/',
    items: [
      {
        text: 'Docker 基础',
        link: '/devops/docker/basic/',
        collapsed: true,
        items: [
          { text: 'Docker 与虚拟机的区别：轻量化与性能', link: '/devops/docker/basic/vm-vs-docker' },
          { text: 'Docker 核心概念：镜像、容器、仓库', link: '/devops/docker/basic/core-concept' },
          { text: 'Dockerfile 指令详解：FROM、RUN、COPY、CMD、ENTRYPOINT、ENV、WORKDIR、VOLUME', link: '/devops/docker/basic/dockerfile' },
          { text: 'Docker 镜像分层与 COPY-on-Write 机制', link: '/devops/docker/basic/image-layer' },
          { text: 'Dockerfile 最佳实践：多阶段构建、镜像大小优化、安全加固', link: '/devops/docker/basic/dockerfile-best' },
          { text: 'Dockerfile .dockerignore 文件', link: '/devops/docker/basic/dockerignore' },
          { text: 'Docker 数据持久化：Volume、Bind Mount、tmpfs', link: '/devops/docker/basic/volume' },
          { text: 'Docker 网络模式：bridge、host、container、none、自定义网络', link: '/devops/docker/basic/network' },
          { text: 'Docker Compose 多容器编排', link: '/devops/docker/basic/compose' },
          { text: 'Docker Registry 私有仓库搭建', link: '/devops/docker/basic/registry' },
          { text: 'Harbor 企业级镜像仓库', link: '/devops/docker/basic/harbor' },
        ],
      },
      {
        text: 'Docker 进阶',
        link: '/devops/docker/advanced/',
        collapsed: true,
        items: [
          { text: '容器通信原理：veth-pair、docker0 网桥、iptables', link: '/devops/docker/advanced/container-communication' },
          { text: 'Docker 存储驱动：overlay2、devicemapper、btrfs、zfs', link: '/devops/docker/advanced/storage-driver' },
          { text: '容器资源限制：CPU、内存、IO 限制', link: '/devops/docker/advanced/resource-limit' },
          { text: 'Docker 安全：用户命名空间隔离、seccomp、capability、AppArmor', link: '/devops/docker/advanced/security' },
          { text: 'Docker 日志驱动与日志管理', link: '/devops/docker/advanced/logging' },
          { text: 'Docker 健康检查：HEALTHCHECK 指令', link: '/devops/docker/advanced/healthcheck' },
          { text: 'Docker 性能优化建议', link: '/devops/docker/advanced/performance' },
          { text: 'Docker 构建缓存机制与最佳实践', link: '/devops/docker/advanced/build-cache' },
        ],
      },
      {
        text: 'Docker Swarm',
        link: '/devops/docker/swarm/',
        collapsed: true,
        items: [
          { text: 'Docker Swarm 架构：Manager 节点与 Worker 节点', link: '/devops/docker/swarm/swarm-architecture' },
          { text: 'Docker Swarm 服务部署与滚动更新', link: '/devops/docker/swarm/swarm-deploy' },
          { text: 'Docker Swarm 负载均衡与 DNS 服务发现', link: '/devops/docker/swarm/swarm-lb' },
        ],
      },
      { text: 'Docker 面试高频问题汇总', link: '/devops/docker/interview-summary' },
    ],
  },
  {
    text: 'Kubernetes（K8s）',
    link: '/devops/k8s/',
    items: [
      {
        text: 'Kubernetes 基础',
        link: '/devops/k8s/basic/',
        collapsed: true,
        items: [
          { text: 'Kubernetes 架构：Control Plane（Master）与 Worker Node', link: '/devops/k8s/basic/architecture' },
          { text: 'Kubernetes 核心概念：Pod、ReplicaSet、Deployment、StatefulSet、DaemonSet', link: '/devops/k8s/basic/core-concept' },
          { text: 'Pod 生命周期与容器状态', link: '/devops/k8s/basic/pod-lifecycle' },
          { text: 'Pod 资源配置：Limit 与 Request', link: '/devops/k8s/basic/pod-resource' },
          { text: 'Pod 调度机制：NodeSelector、Affinity、Taint 与 Toleration', link: '/devops/k8s/basic/pod-scheduling' },
          { text: 'Pod 驱逐策略与优先级', link: '/devops/k8s/basic/pod-eviction' },
          { text: 'Pod 健康检查：Liveness Probe、Readiness Probe、Startup Probe', link: '/devops/k8s/basic/probe' },
          { text: 'Init Container 与 Sidecar 模式', link: '/devops/k8s/basic/init-container' },
        ],
      },
      {
        text: 'Kubernetes 核心资源',
        link: '/devops/k8s/workload/',
        collapsed: true,
        items: [
          { text: 'Deployment：滚动更新、回滚、金丝雀发布', link: '/devops/k8s/workload/deployment' },
          { text: 'Deployment 扩缩容：HPA（Horizontal Pod Autoscaler）', link: '/devops/k8s/workload/hpa' },
          { text: 'StatefulSet：有状态应用管理', link: '/devops/k8s/workload/statefulset' },
          { text: 'StatefulSet 稳定网络标识与持久存储', link: '/devops/k8s/workload/statefulset-stable' },
          { text: 'DaemonSet：每个节点运行一个 Pod', link: '/devops/k8s/workload/daemonset' },
          { text: 'Job 与 CronJob：批处理任务与定时任务', link: '/devops/k8s/workload/job-cronjob' },
        ],
      },
      {
        text: 'Kubernetes 网络',
        link: '/devops/k8s/network/',
        collapsed: true,
        items: [
          { text: 'Kubernetes 网络模型：Pod IP 与 Service IP', link: '/devops/k8s/network/network-model' },
          { text: 'Kubernetes DNS 服务发现原理', link: '/devops/k8s/network/dns' },
          { text: 'Service 类型：ClusterIP、NodePort、LoadBalancer、ExternalName', link: '/devops/k8s/network/service-type' },
          { text: 'Ingress：HTTP/HTTPS 路由与七层负载均衡', link: '/devops/k8s/network/ingress' },
          { text: 'NetworkPolicy：Pod 网络隔离策略', link: '/devops/k8s/network/network-policy' },
          { text: 'CNI 网络插件：Flannel、Calico、Cilium 对比', link: '/devops/k8s/network/cni' },
          { text: 'Service 负载均衡实现：iptables vs IPVS', link: '/devops/k8s/network/service-lb' },
          { text: 'Pod 网络通信：同一 Node 内与跨 Node 通信', link: '/devops/k8s/network/pod-communication' },
        ],
      },
      {
        text: 'Kubernetes 存储',
        link: '/devops/k8s/storage/',
        collapsed: true,
        items: [
          { text: 'Volume 类型：emptyDir、hostPath、nfs、persistentVolumeClaim', link: '/devops/k8s/storage/volume' },
          { text: 'PersistentVolume（PV）与 PersistentVolumeClaim（PVC）', link: '/devops/k8s/storage/pv-pvc' },
          { text: 'StorageClass 与动态存储供给', link: '/devops/k8s/storage/storage-class' },
          { text: 'ConfigMap 与 Secret：应用配置', link: '/devops/k8s/storage/configmap-secret' },
          { text: 'Secret 类型：Opaque、kubernetes.io/dockerconfigjson、tls', link: '/devops/k8s/storage/secret-type' },
        ],
      },
      {
        text: 'Kubernetes 安全',
        link: '/devops/k8s/security/',
        collapsed: true,
        items: [
          { text: 'RBAC：Role、ClusterRole、RoleBinding、ClusterRoleBinding', link: '/devops/k8s/security/rbac' },
          { text: 'Security Context 与 Pod Security Policy/Standards', link: '/devops/k8s/security/security-context' },
          { text: 'ServiceAccount 与 Pod 安全上下文', link: '/devops/k8s/security/serviceaccount' },
          { text: 'NetworkPolicy 网络隔离策略', link: '/devops/k8s/security/network-policy-security' },
        ],
      },
      {
        text: 'Kubernetes 运维',
        link: '/devops/k8s/ops/',
        collapsed: true,
        items: [
          { text: 'kubectl 常用命令速查', link: '/devops/k8s/ops/kubectl' },
          { text: 'Kubernetes Dashboard 与 Lens 可视化工具', link: '/devops/k8s/ops/dashboard' },
          { text: 'Kubernetes 集群高可用部署方案', link: '/devops/k8s/ops/ha-deployment' },
          { text: 'etcd 备份与恢复', link: '/devops/k8s/ops/etcd-backup' },
          { text: '集群升级：滚动升级与版本兼容性', link: '/devops/k8s/ops/upgrade' },
          { text: '资源配额：ResourceQuota、LimitRange', link: '/devops/k8s/ops/resource-quota' },
          { text: 'HPA 进阶：自定义指标与 External Metrics', link: '/devops/k8s/ops/hpa-advanced' },
          { text: 'VPA（垂直 Pod 自动扩缩容）与 CronJob HPA', link: '/devops/k8s/ops/vpa' },
          { text: 'Prometheus + Grafana 监控体系', link: '/devops/k8s/ops/prometheus' },
          { text: 'Kubebuilder 与 Operator 开发', link: '/devops/k8s/ops/operator' },
        ],
      },
      {
        text: 'Helm',
        link: '/devops/k8s/helm/',
        collapsed: true,
        items: [
          { text: 'Helm 概念：Chart、Repository、Release', link: '/devops/k8s/helm/helm' },
          { text: 'Helm 模板语法与 values.yaml', link: '/devops/k8s/helm/helm-template' },
          { text: 'Helm Hook 生命周期管理', link: '/devops/k8s/helm/helm-hook' },
          { text: 'Helmfile 与 GitOps 工作流', link: '/devops/k8s/helm/helmfile' },
        ],
      },
      {
        text: '云原生生态',
        link: '/devops/k8s/cloud-native/',
        collapsed: true,
        items: [
          { text: '云原生概念：容器、微服务、不可变基础设施、声明式 API', link: '/devops/k8s/cloud-native/cloud-native' },
          { text: 'Service Mesh：Istio、Linkerd、Envoy 架构', link: '/devops/k8s/cloud-native/service-mesh' },
          { text: 'K8s 部署策略：滚动部署、蓝绿部署、金丝雀发布、灰度发布', link: '/devops/k8s/cloud-native/deployment-strategy' },
          { text: 'Kustomize vs Helm vs GitOps（ArgoCD）', link: '/devops/k8s/cloud-native/kustomize-gitops' },
        ],
      },
      { text: 'Kubernetes 面试高频问题汇总', link: '/devops/k8s/interview-summary' },
    ],
  },
  {
    text: '构建工具',
    link: '/devops/build-tool/',
    items: [
      {
        text: '构建工具基础',
        link: '/devops/build-tool/basic/',
        collapsed: true,
        items: [
          { text: '构建工具发展历程：Ant → Maven → Gradle', link: '/devops/build-tool/basic/history' },
          { text: 'Maven vs Gradle：核心差异与选型建议', link: '/devops/build-tool/basic/maven-vs-gradle' },
        ],
      },
      {
        text: 'Maven',
        link: '/devops/build-tool/maven/',
        collapsed: true,
        items: [
          { text: 'Maven 核心概念：坐标（GroupId、ArtifactId、Version）、仓库（Local、Remote、Central）', link: '/devops/build-tool/maven/maven-concept' },
          { text: 'Maven 依赖传递与依赖冲突解决：依赖调解（就近原则）与 exclusions 排除', link: '/devops/build-tool/maven/maven-dependency' },
          { text: 'Maven 依赖作用域（Scope）：compile、provided、runtime、test、system', link: '/devops/build-tool/maven/maven-scope' },
          { text: 'Maven 生命周期：clean、default、site 三套生命周期与阶段（Phase）', link: '/devops/build-tool/maven/maven-lifecycle' },
          { text: 'Maven 插件机制：插件目标（Goal）与绑定到生命周期阶段', link: '/devops/build-tool/maven/maven-plugin' },
          { text: 'Maven pom.xml 核心配置：dependencies、dependencyManagement、build、profiles', link: '/devops/build-tool/maven/maven-pom' },
          { text: 'Maven 多模块项目聚合（父 POM）与依赖管理（dependencyManagement）', link: '/devops/build-tool/maven/maven-multi-module' },
          { text: 'Maven 仓库配置：私有仓库 Nexus/Artifactory 搭建与镜像加速', link: '/devops/build-tool/maven/maven-repository' },
          { text: 'Maven BOM（Bill of Materials）：统一管理依赖版本', link: '/devops/build-tool/maven/maven-bom' },
          { text: 'Maven 常用命令：mvn install、package、deploy、dependency:tree、dependency:analyze', link: '/devops/build-tool/maven/maven-command' },
          { text: 'Maven 构建性能优化：并行构建、增量构建、本地仓库缓存', link: '/devops/build-tool/maven/maven-performance' },
        ],
      },
      {
        text: 'Gradle',
        link: '/devops/build-tool/gradle/',
        collapsed: true,
        items: [
          { text: 'Gradle 核心优势：DSL 语法、Groovy/Kotlin 脚本、增量构建', link: '/devops/build-tool/gradle/gradle-concept' },
          { text: 'Gradle 构建脚本：Project 与 Task 概念、任务依赖链', link: '/devops/build-tool/gradle/gradle-script' },
          { text: 'Gradle 依赖管理：configurations、dependencies、API vs Implementation 隔离', link: '/devops/build-tool/gradle/gradle-dependency' },
          { text: 'Gradle DSL：build.gradle（Groovy DSL）与 build.gradle.kts（Kotlin DSL）', link: '/devops/build-tool/gradle/gradle-dsl' },
          { text: 'Gradle 增量构建与任务缓存：输入输出配置、构建缓存（Build Cache）', link: '/devops/build-tool/gradle/gradle-incremental' },
          { text: 'Gradle 多项目构建：根项目与子项目配置、跨项目依赖', link: '/devops/build-tool/gradle/gradle-multi-project' },
          { text: 'Gradle 插件机制：核心插件、社区插件、自定义插件开发', link: '/devops/build-tool/gradle/gradle-plugin' },
          { text: 'Gradle 与 Maven 互操作：导入 pom.xml、maven-publish 插件', link: '/devops/build-tool/gradle/gradle-maven-interop' },
          { text: 'Gradle 守护进程（Daemon）与配置缓存、构建缓存', link: '/devops/build-tool/gradle/gradle-daemon' },
          { text: 'Gradle 常用命令：gradle build、dependencies、--scan、--parallel', link: '/devops/build-tool/gradle/gradle-command' },
        ],
      },
      {
        text: '构建最佳实践',
        link: '/devops/build-tool/best-practice/',
        collapsed: true,
        items: [
          { text: '依赖版本管理规范：统一版本管理、禁止 SNAPSHOT 上线', link: '/devops/build-tool/best-practice/dependency-version' },
          { text: '多环境构建：Maven Profile 与 Gradle ProductFlavors', link: '/devops/build-tool/best-practice/multi-env' },
          { text: '构建产物管理：FatJar、Shade、Shadow、Spring Boot Jar 包结构', link: '/devops/build-tool/best-practice/fat-jar' },
          { text: '构建安全：依赖漏洞扫描（OWASP Dependency-Check）', link: '/devops/build-tool/best-practice/security' },
          { text: '构建工具面试高频问题汇总', link: '/devops/build-tool/best-practice/interview-summary' },
        ],
      },
    ],
  },
  {
    text: 'CI/CD',
    link: '/devops/cicd/',
    items: [
      {
        text: 'Git 与版本控制',
        link: '/devops/cicd/git/',
        collapsed: true,
        items: [
          { text: 'Git 工作流：Git Flow、GitHub Flow、Trunk-Based Development', link: '/devops/cicd/git/git-workflow' },
          { text: 'Git 常用命令与原理：merge、rebase、cherry-pick、stash', link: '/devops/cicd/git/git-command' },
          { text: 'Git 分支管理策略', link: '/devops/cicd/git/git-branch' },
          { text: 'Git 提交规范：Conventional Commits', link: '/devops/cicd/git/git-commit' },
          { text: 'Git Hooks 与 CI 集成', link: '/devops/cicd/git/git-hook' },
        ],
      },
      {
        text: 'Jenkins',
        link: '/devops/cicd/jenkins/',
        collapsed: true,
        items: [
          { text: 'Jenkins 架构：Master-Slave 分布式构建', link: '/devops/cicd/jenkins/jenkins-architecture' },
          { text: 'Jenkinsfile 声明式流水线语法', link: '/devops/cicd/jenkins/jenkinsfile' },
          { text: 'Jenkins 插件生态与常用插件', link: '/devops/cicd/jenkins/jenkins-plugin' },
          { text: 'Jenkins 与 Docker、Kubernetes 集成', link: '/devops/cicd/jenkins/jenkins-k8s' },
          { text: 'Jenkins Blue Ocean 可视化流水线', link: '/devops/cicd/jenkins/blue-ocean' },
        ],
      },
      {
        text: '现代 CI/CD 工具',
        link: '/devops/cicd/modern/',
        collapsed: true,
        items: [
          { text: 'GitLab CI/CD 流水线语法', link: '/devops/cicd/modern/gitlab-ci' },
          { text: 'GitHub Actions 工作流配置', link: '/devops/cicd/modern/github-actions' },
          { text: 'ArgoCD：GitOps 持续交付工具', link: '/devops/cicd/modern/argocd' },
          { text: 'Tekton：Kubernetes 原生 CI/CD 框架', link: '/devops/cicd/modern/tekton' },
          { text: 'Spinnaker：多云持续交付平台', link: '/devops/cicd/modern/spinnaker' },
          { text: 'Jenkins vs GitLab CI vs GitHub Actions vs Tekton 对比', link: '/devops/cicd/modern/compare' },
        ],
      },
      {
        text: 'CI/CD 最佳实践',
        link: '/devops/cicd/best-practice/',
        collapsed: true,
        items: [
          { text: 'CI/CD 流水线设计原则', link: '/devops/cicd/best-practice/pipeline-design' },
          { text: 'SonarQube 代码质量检查集成', link: '/devops/cicd/best-practice/sonarqube' },
          { text: '容器镜像构建与安全扫描：Trivy、Clair', link: '/devops/cicd/best-practice/image-scan' },
          { text: '制品库：Nexus、Harbor、Artifactory', link: '/devops/cicd/best-practice/artifact' },
          { text: '蓝绿部署与金丝雀发布流水线', link: '/devops/cicd/best-practice/blue-green' },
        ],
      },
    ],
  },
  {
    text: '容器编排对比',
    link: '/devops/orchestration/',
    items: [
      { text: 'Docker Swarm vs Kubernetes vs Mesos 对比', link: '/devops/orchestration/compare' },
      { text: 'Kubernetes vs Docker Compose：何时用哪个', link: '/devops/orchestration/k8s-vs-compose' },
      { text: 'K3s：轻量级 Kubernetes 发行版', link: '/devops/orchestration/k3s' },
      { text: 'K0s 与 MicroK8s', link: '/devops/orchestration/k0s-microk8s' },
    ],
  },
  {
    text: '自动化运维',
    link: '/devops/ops/',
    items: [
      {
        text: 'Ansible',
        link: '/devops/ops/ansible/',
        collapsed: true,
        items: [
          { text: 'Ansible 架构：控制节点、被管节点、Inventory、Playbook', link: '/devops/ops/ansible/architecture' },
          { text: 'Ansible Playbook 语法与模块', link: '/devops/ops/ansible/playbook' },
          { text: 'Ansible Roles 与 Galaxy', link: '/devops/ops/ansible/roles' },
          { text: 'Ansible 与 Docker、Kubernetes 集成', link: '/devops/ops/ansible/integration' },
        ],
      },
      {
        text: 'Prometheus + Grafana',
        link: '/devops/ops/monitor/',
        collapsed: true,
        items: [
          { text: 'Prometheus 数据模型与指标类型：Counter、Gauge、Histogram、Summary', link: '/devops/ops/monitor/prometheus-data' },
          { text: 'Prometheus 架构：PromQL、Exporter、AlertManager', link: '/devops/ops/monitor/prometheus-architecture' },
          { text: 'Prometheus 服务发现：K8s、Consul、文件', link: '/devops/ops/monitor/service-discovery' },
          { text: 'PromQL 查询语法与常用函数', link: '/devops/ops/monitor/promql' },
          { text: 'Grafana 可视化仪表盘与告警', link: '/devops/ops/monitor/grafana' },
          { text: 'Node Exporter、MySQL Exporter、Blackbox Exporter', link: '/devops/ops/monitor/exporter' },
          { text: 'Kubernetes 监控方案：kube-prometheus-stack', link: '/devops/ops/monitor/k8s-monitoring' },
          { text: 'Prometheus vs Zabbix vs Datadog 对比', link: '/devops/ops/monitor/compare' },
        ],
      },
      {
        text: '日志系统',
        link: '/devops/ops/log/',
        collapsed: true,
        items: [
          { text: 'ELK Stack 架构：Elasticsearch + Logstash + Kibana + Beats', link: '/devops/ops/log/elk' },
          { text: 'EFK Stack：Fluentd/Fluent Bit 替代 Logstash', link: '/devops/ops/log/efk' },
          { text: 'Loki：日志聚合系统（Prometheus 团队出品）', link: '/devops/ops/log/loki' },
          { text: '日志收集方案：Filebeat、Logstash、Fluentd 对比', link: '/devops/ops/log/log-collector' },
          { text: '分布式日志追踪：ELK + Zipkin/Jaeger 集成', link: '/devops/ops/log/distributed-log' },
        ],
      },
      { text: 'SRE 与可观测性', link: '/devops/ops/sre' },
      { text: '链路追踪：SkyWalking、Zipkin、Jaeger 对比', link: '/devops/ops/tracing' },
    ],
  },
  {
    text: 'KubeSphere',
    link: '/devops/kubesphere/',
    items: [
      {
        text: 'KubeSphere 基础',
        link: '/devops/kubesphere/basic/',
        collapsed: true,
        items: [
          { text: 'KubeSphere 概述：企业级容器平台定位', link: '/devops/kubesphere/basic/overview' },
          { text: 'KubeSphere vs OpenShift vs Rancher 对比', link: '/devops/kubesphere/basic/compare' },
          { text: 'KubeSphere 架构：前端、核心服务、Agent 组件', link: '/devops/kubesphere/basic/architecture' },
          { text: 'KubeSphere 多租户体系：Workspace、Namespace、Project 层级', link: '/devops/kubesphere/basic/multi-tenant' },
          { text: 'KubeSphere 安装部署：All-in-One 与多节点模式', link: '/devops/kubesphere/basic/install' },
        ],
      },
      {
        text: 'KubeSphere 核心功能',
        link: '/devops/kubesphere/core/',
        collapsed: true,
        items: [
          { text: 'KubeSphere 应用管理：基于 OpenPitrix 的应用商店', link: '/devops/kubesphere/core/app-store' },
          { text: 'KubeSphere 流水线（Pipeline）：基于 Jenkins 的 CI/CD', link: '/devops/kubesphere/core/pipeline' },
          { text: 'KubeSphere 告警与通知系统', link: '/devops/kubesphere/core/alerting' },
          { text: 'KubeSphere 日志收集与查询：Elasticsearch + FluentBit', link: '/devops/kubesphere/core/logging' },
          { text: 'KubeSphere 事件与审计日志', link: '/devops/kubesphere/core/audit' },
          { text: 'KubeSphere 服务网格：基于 Istio 的可视化治理', link: '/devops/kubesphere/core/service-mesh' },
          { text: 'KubeSphere 多租户监控：MetrisServer 与自定义监控', link: '/devops/kubesphere/core/monitoring' },
        ],
      },
      {
        text: 'KubeSphere DevOps',
        link: '/devops/kubesphere/devops/',
        collapsed: true,
        items: [
          { text: 'KubeSphere 流水线语法：Jenkinsfile in SCM vs 图形化编辑', link: '/devops/kubesphere/devops/pipeline-syntax' },
          { text: 'KubeSphere 二进制制品仓库与镜像仓库集成', link: '/devops/kubesphere/devops/registry' },
          { text: 'KubeSphere 自动化构建与镜像推送流程', link: '/devops/kubesphere/devops/build-push' },
          { text: 'KubeSphere 蓝绿部署与滚动更新配置', link: '/devops/kubesphere/devops/deploy-strategy' },
          { text: 'KubeSphere GitOps 工作流集成', link: '/devops/kubesphere/devops/gitops' },
        ],
      },
      {
        text: 'KubeSphere 运维管理',
        link: '/devops/kubesphere/admin/',
        collapsed: true,
        items: [
          { text: 'KubeSphere 节点管理：添加、角色设置、污点管理', link: '/devops/kubesphere/admin/node-management' },
          { text: 'KubeSphere 存储管理：存储类型（StorageClass）与持久卷', link: '/devops/kubesphere/admin/storage' },
          { text: 'KubeSphere 网络管理：Porter 与负载均衡器', link: '/devops/kubesphere/admin/network' },
          { text: 'KubeSphere 集群升级与版本管理', link: '/devops/kubesphere/admin/upgrade' },
          { text: 'KubeSphere 权限管理：用户、角色、ClusterRoleBinding', link: '/devops/kubesphere/admin/rbac' },
          { text: 'KubeSphere 运维常用工具与故障排查', link: '/devops/kubesphere/admin/troubleshoot' },
        ],
      },
      { text: 'KubeSphere 面试高频问题汇总', link: '/devops/kubesphere/interview-summary' },
    ],
  },
  {
    text: '基础设施即代码（IaC）',
    link: '/devops/iac/',
    items: [
      { text: 'Terraform 基础与 HCL 语法', link: '/devops/iac/terraform' },
      { text: 'Terraform 模块化与状态管理', link: '/devops/iac/terraform-module' },
      { text: 'Pulumi：用代码管理云资源', link: '/devops/iac/pulumi' },
      { text: 'Ansible vs Terraform vs Pulumi 对比', link: '/devops/iac/compare' },
    ],
  },
]
