export const distributedSidebar = [
  {
    text: '分布式理论',
    link: '/distributed/theory/',
    items: [
      {
        text: '一致性理论基础',
        link: '/distributed/theory/consistency/',
        collapsed: true,
        items: [
          { text: 'CAP 理论', link: '/distributed/theory/consistency/cap' },
          { text: 'CAP 权衡：CP 与 AP', link: '/distributed/theory/consistency/cap-tradeoff' },
          { text: 'BASE 理论', link: '/distributed/theory/consistency/base' },
          { text: '一致性模型', link: '/distributed/theory/consistency/consistency-model' },
          { text: 'ACID vs BASE', link: '/distributed/theory/consistency/acid-vs-base' },
          { text: 'FLP 不可能性原理', link: '/distributed/theory/consistency/flp' },
        ],
      },
      {
        text: '分布式系统核心问题',
        link: '/distributed/theory/core/',
        collapsed: true,
        items: [
          { text: '分布式互斥', link: '/distributed/theory/core/mutual-exclusion' },
          { text: '分布式选举算法', link: '/distributed/theory/core/leader-election' },
          { text: '分布式共识算法', link: '/distributed/theory/core/consensus-algorithm' },
          { text: 'Paxos 算法', link: '/distributed/theory/core/paxos' },
          { text: 'Raft 算法', link: '/distributed/theory/core/raft' },
          { text: 'ZAB 协议', link: '/distributed/theory/core/zab' },
          { text: '一致性哈希', link: '/distributed/theory/core/consistent-hash' },
          { text: '拜占庭将军问题', link: '/distributed/theory/core/byzantine' },
        ],
      },
      {
        text: '分布式协调',
        link: '/distributed/theory/coordination/',
        collapsed: true,
        items: [
          { text: '时钟与事件顺序', link: '/distributed/theory/coordination/logical-clock' },
          { text: '分布式 ID 算法', link: '/distributed/theory/coordination/distributed-id' },
          { text: 'Gossip 协议', link: '/distributed/theory/coordination/gossip' },
          { text: 'Lease 机制', link: '/distributed/theory/coordination/lease' },
          { text: '二阶段提交 2PC', link: '/distributed/theory/coordination/2pc' },
          { text: '三阶段提交 3PC', link: '/distributed/theory/coordination/3pc' },
          { text: '2PC vs 3PC', link: '/distributed/theory/coordination/2pc-vs-3pc' },
        ],
      },
      { text: '微服务架构设计', link: '/distributed/theory/microservices' },
      { text: 'SOA vs 微服务', link: '/distributed/theory/soa-vs-microservices' },
      { text: '康威定律', link: '/distributed/theory/conways-law' },
      { text: '分布式性能指标', link: '/distributed/theory/performance-metrics' },
    ],
  },
  {
    text: '分布式事务',
    link: '/distributed/transaction/',
    items: [
      {
        text: '分布式事务解决方案',
        link: '/distributed/transaction/solution/',
        collapsed: true,
        items: [
          { text: '分布式事务方案总览', link: '/distributed/transaction/solution/overview' },
          { text: 'Seata AT 模式', link: '/distributed/transaction/solution/seata-at' },
          { text: 'Seata TCC 模式', link: '/distributed/transaction/solution/seata-tcc' },
          { text: 'Seata SAGA 模式', link: '/distributed/transaction/solution/seata-saga' },
          { text: '可靠消息最终一致性', link: '/distributed/transaction/solution/reliable-message' },
          { text: '最大努力通知', link: '/distributed/transaction/solution/best-effort-notify' },
          { text: 'AT vs TCC vs SAGA', link: '/distributed/transaction/solution/mode-compare' },
        ],
      },
      {
        text: '分布式事务原理',
        link: '/distributed/transaction/principle/',
        collapsed: true,
        items: [
          { text: 'XA 规范', link: '/distributed/transaction/principle/xa' },
          { text: 'Seata 整体架构', link: '/distributed/transaction/principle/seata-architecture' },
          { text: 'Seata 全局事务', link: '/distributed/transaction/principle/seata-global' },
          { text: 'Seata 高可用', link: '/distributed/transaction/principle/seata-ha' },
          { text: 'TCC 问题处理', link: '/distributed/transaction/principle/tcc-problem' },
        ],
      },
      { text: '分布式事务面试题', link: '/distributed/transaction/interview-summary' },
    ],
  },
  {
    text: '分布式锁',
    link: '/distributed/lock/',
    items: [
      { text: '分布式锁条件', link: '/distributed/lock/requirements' },
      { text: 'Redis 分布式锁', link: '/distributed/lock/redis-lock' },
      { text: 'Redisson 分布式锁', link: '/distributed/lock/redisson' },
      { text: 'Redisson 可重入锁', link: '/distributed/lock/redisson-reentrant' },
      { text: 'Redisson 公平锁', link: '/distributed/lock/redisson-fair' },
      { text: 'Redisson 读写锁', link: '/distributed/lock/redisson-readwrite' },
      { text: 'Redisson 信号量', link: '/distributed/lock/redisson-semaphore' },
      { text: 'Redisson 联锁', link: '/distributed/lock/redisson-multilock' },
      { text: '分布式锁超时', link: '/distributed/lock/timeout-clock' },
      { text: 'MySQL 分布式锁', link: '/distributed/lock/mysql-lock' },
      { text: 'ZooKeeper 分布式锁', link: '/distributed/lock/zookeeper-lock' },
      { text: '分布式锁对比', link: '/distributed/lock/lock-compare' },
    ],
  },
  {
    text: '分布式协调服务',
    link: '/distributed/coordination/',
    items: [
      {
        text: 'ZooKeeper',
        link: '/distributed/coordination/zookeeper/',
        collapsed: true,
        items: [
          { text: 'ZooKeeper 数据模型', link: '/distributed/coordination/zookeeper/data-model' },
          { text: 'ZooKeeper 监听机制', link: '/distributed/coordination/zookeeper/watch' },
          { text: 'ZooKeeper 会话', link: '/distributed/coordination/zookeeper/session' },
          { text: 'ZooKeeper Leader 选举', link: '/distributed/coordination/zookeeper/leader-election' },
          { text: 'ZooKeeper ACL', link: '/distributed/coordination/zookeeper/acl' },
          { text: 'ZooKeeper 应用场景', link: '/distributed/coordination/zookeeper/use-case' },
          { text: 'ZooKeeper 典型应用', link: '/distributed/coordination/zookeeper/kafka-dubbo' },
          { text: 'ZooKeeper vs etcd', link: '/distributed/coordination/zookeeper/zookeeper-vs-etcd' },
        ],
      },
      {
        text: 'etcd',
        link: '/distributed/coordination/etcd/',
        collapsed: true,
        items: [
          { text: 'etcd 架构', link: '/distributed/coordination/etcd/architecture' },
          { text: 'etcd vs ZooKeeper', link: '/distributed/coordination/etcd/compare' },
          { text: 'etcd 在 K8s 中应用', link: '/distributed/coordination/etcd/kubernetes' },
        ],
      },
      {
        text: 'Nacos',
        link: '/distributed/coordination/nacos/',
        collapsed: true,
        items: [
          { text: 'Nacos 架构', link: '/distributed/coordination/nacos/architecture' },
          { text: 'Nacos 服务注册', link: '/distributed/coordination/nacos/service-registry' },
          { text: 'Nacos 配置管理', link: '/distributed/coordination/nacos/config' },
          { text: 'Nacos 集群模式', link: '/distributed/coordination/nacos/cluster' },
          { text: 'Nacos 实例类型', link: '/distributed/coordination/nacos/instance' },
        ],
      },
    ],
  },
  {
    text: '服务治理',
    link: '/distributed/governance/',
    items: [
      { text: '服务发现', link: '/distributed/governance/service-discovery' },
      { text: '服务健康检查', link: '/distributed/governance/health-check' },
      { text: '负载均衡策略', link: '/distributed/governance/load-balancing' },
      { text: '客户端 vs 服务端 LB', link: '/distributed/governance/client-vs-server-lb' },
      { text: '服务熔断', link: '/distributed/governance/circuit-breaker' },
      { text: '服务降级', link: '/distributed/governance/degradation' },
      { text: '服务限流', link: '/distributed/governance/rate-limit' },
      { text: '服务超时', link: '/distributed/governance/timeout' },
      { text: '服务重试', link: '/distributed/governance/retry' },
      { text: '幂等性设计', link: '/distributed/governance/idempotency' },
      { text: '接口安全', link: '/distributed/governance/interface-security' },
    ],
  },
  {
    text: '服务调用',
    link: '/distributed/rpc/',
    items: [
      {
        text: 'Dubbo',
        link: '/distributed/rpc/dubbo/',
        collapsed: true,
        items: [
          { text: 'Dubbo 整体架构', link: '/distributed/rpc/dubbo/architecture' },
          { text: 'Dubbo 协议', link: '/distributed/rpc/dubbo/protocol' },
          { text: 'Dubbo 负载均衡', link: '/distributed/rpc/dubbo/loadbalance' },
          { text: 'Dubbo 路由机制', link: '/distributed/rpc/dubbo/routing' },
          { text: 'Dubbo 集群容错', link: '/distributed/rpc/dubbo/cluster' },
          { text: 'Dubbo 线程模型', link: '/distributed/rpc/dubbo/thread-model' },
          { text: 'Dubbo 服务导出引用', link: '/distributed/rpc/dubbo/export-refer' },
          { text: 'Dubbo 过滤器链', link: '/distributed/rpc/dubbo/spi' },
          { text: 'Dubbo 链路追踪', link: '/distributed/rpc/dubbo/tracing' },
        ],
      },
      {
        text: 'Feign 与 OpenFeign',
        link: '/distributed/rpc/feign/',
        collapsed: true,
        items: [
          { text: 'Feign 原理', link: '/distributed/rpc/feign/principle' },
          { text: 'OpenFeign 集成', link: '/distributed/rpc/feign/springboot' },
          { text: 'Feign 负载均衡', link: '/distributed/rpc/feign/ribbon' },
          { text: 'Feign 拦截器', link: '/distributed/rpc/feign/interceptor' },
          { text: 'Feign 压缩配置', link: '/distributed/rpc/feign/compression' },
        ],
      },
      { text: 'gRPC', link: '/distributed/rpc/grpc' },
      { text: 'REST vs RPC vs gRPC', link: '/distributed/rpc/rest-rpc' },
    ],
  },
  {
    text: '典型分布式场景方案',
    link: '/distributed/scenario/',
    items: [
      {
        text: '统一认证与 SSO',
        link: '/distributed/scenario/auth/',
        collapsed: true,
        items: [
          { text: '微服务统一认证', link: '/distributed/scenario/auth/unified-auth' },
          { text: 'CAS 单点登录', link: '/distributed/scenario/auth/cas-sso' },
          { text: 'OAuth 2.0 使用', link: '/distributed/scenario/auth/oauth2-microservice' },
          { text: '分布式 Session', link: '/distributed/scenario/auth/distributed-session' },
          { text: 'JWT 无状态 Token', link: '/distributed/scenario/auth/jwt-stateless' },
        ],
      },
      {
        text: '多级缓存架构',
        link: '/distributed/scenario/cache/',
        collapsed: true,
        items: [
          { text: '多级缓存模式', link: '/distributed/scenario/cache/multi-level-cache' },
          { text: '缓存双写一致性', link: '/distributed/scenario/cache/cache-db-consistency' },
          { text: '缓存穿透', link: '/distributed/scenario/cache/cache-penetration' },
          { text: '缓存击穿', link: '/distributed/scenario/cache/cache-breakdown' },
          { text: '缓存雪崩', link: '/distributed/scenario/cache/cache-avalanche' },
          { text: '热点数据探测', link: '/distributed/scenario/cache/hot-data-detection' },
        ],
      },
      {
        text: '分布式文件存储',
        link: '/distributed/scenario/storage/',
        collapsed: true,
        items: [
          { text: 'MinIO 分布式存储', link: '/distributed/scenario/storage/minio' },
          { text: 'FastDFS 原理', link: '/distributed/scenario/storage/fastdfs' },
          { text: '文件分片上传', link: '/distributed/scenario/storage/file-sharding' },
          { text: 'CDN + OSS 加速', link: '/distributed/scenario/storage/cdn-oss' },
        ],
      },
      {
        text: '多机房与数据同步',
        link: '/distributed/scenario/datacenter/',
        collapsed: true,
        items: [
          { text: '同城双活架构', link: '/distributed/scenario/datacenter/active-active' },
          { text: '异地多活架构', link: '/distributed/scenario/datacenter/multi-region' },
          { text: '跨机房数据同步', link: '/distributed/scenario/datacenter/cross-datacenter-sync' },
          { text: '分库分表全局 ID', link: '/distributed/scenario/datacenter/sharding-id' },
        ],
      },
      {
        text: '流量控制与弹性',
        link: '/distributed/scenario/flow/',
        collapsed: true,
        items: [
          { text: '全链路限流', link: '/distributed/scenario/flow/full-link-rate-limit' },
          { text: '流量削峰', link: '/distributed/scenario/flow/peak-shaving' },
          { text: '服务弹性降级', link: '/distributed/scenario/flow/elastic-degradation' },
          { text: '重试风暴治理', link: '/distributed/scenario/flow/retry-storm' },
          { text: '自适应限流', link: '/distributed/scenario/flow/self-adaptive-limit' },
        ],
      },
      {
        text: '数据处理与批任务',
        link: '/distributed/scenario/batch/',
        collapsed: true,
        items: [
          { text: '分布式批量任务', link: '/distributed/scenario/batch/batch-task' },
          { text: '数据同步任务', link: '/distributed/scenario/batch/data-sync-task' },
          { text: '唯一任务执行', link: '/distributed/scenario/batch/unique-task' },
          { text: '定时任务分布式化', link: '/distributed/scenario/batch/distributed-cron' },
        ],
      },
      {
        text: '统一异常与日志',
        link: '/distributed/scenario/log/',
        collapsed: true,
        items: [
          { text: '统一异常处理', link: '/distributed/scenario/log/unified-exception' },
          { text: '分布式日志追踪', link: '/distributed/scenario/log/distributed-trace' },
          { text: '日志聚合方案', link: '/distributed/scenario/log/log-aggregation' },
          { text: '业务链路监控', link: '/distributed/scenario/log/observability' },
        ],
      },
      { text: '分布式面试题', link: '/distributed/scenario/interview-summary' },
    ],
  },
]
