export const distributedSidebar = [
  {
    text: '分布式理论',
    link: '/distributed/theory/',
    items: [
      {
        text: '一致性理论基础',
        link: '/distributed/theory/consistency/',
        collapsed: true,
        items: [
          { text: 'CAP 理论：C一致性、A可用性、P分区容错性', link: '/distributed/theory/consistency/cap' },
          { text: 'CAP 权衡：CP 与 AP 的选择', link: '/distributed/theory/consistency/cap-tradeoff' },
          { text: 'BASE 理论：基本可用、软状态、最终一致性', link: '/distributed/theory/consistency/base' },
          { text: '一致性模型：强一致性、弱一致性、最终一致性、因果一致性', link: '/distributed/theory/consistency/consistency-model' },
          { text: 'ACID vs BASE：对立统一的哲学', link: '/distributed/theory/consistency/acid-vs-base' },
          { text: 'FLP 不可能性原理', link: '/distributed/theory/consistency/flp' },
        ],
      },
      {
        text: '分布式系统核心问题',
        link: '/distributed/theory/core/',
        collapsed: true,
        items: [
          { text: '分布式互斥：集中式算法、分布式算法、令牌环算法', link: '/distributed/theory/core/mutual-exclusion' },
          { text: '分布式选举算法：Bully、Raft、ZAB', link: '/distributed/theory/core/leader-election' },
          { text: '分布式共识算法：Paxos、Raft、ZAB 对比', link: '/distributed/theory/core/consensus-algorithm' },
          { text: 'Paxos 算法：Basic Paxos 与 Multi-Paxos', link: '/distributed/theory/core/paxos' },
          { text: 'Raft 算法：Leader 选举、日志复制、安全性', link: '/distributed/theory/core/raft' },
          { text: 'ZAB 协议：ZooKeeper 原子广播协议', link: '/distributed/theory/core/zab' },
          { text: '一致性哈希（Consistent Hash）与虚拟节点', link: '/distributed/theory/core/consistent-hash' },
          { text: '拜占庭将军问题与 PBFT 算法', link: '/distributed/theory/core/byzantine' },
        ],
      },
      {
        text: '分布式协调',
        link: '/distributed/theory/coordination/',
        collapsed: true,
        items: [
          { text: '时钟与事件顺序：Lamport 时钟与向量时钟', link: '/distributed/theory/coordination/logical-clock' },
          { text: '分布式 ID 生成算法：UUID、雪花算法（Snowflake）、Tweedie', link: '/distributed/theory/coordination/distributed-id' },
          { text: 'Gossip 协议：最终一致性广播', link: '/distributed/theory/coordination/gossip' },
          { text: 'Lease 机制与租约', link: '/distributed/theory/coordination/lease' },
          { text: '二阶段提交（2PC）：流程与缺陷', link: '/distributed/theory/coordination/2pc' },
          { text: '三阶段提交（3PC）：CanCommit、PreCommit、DoCommit', link: '/distributed/theory/coordination/3pc' },
          { text: '2PC vs 3PC 对比', link: '/distributed/theory/coordination/2pc-vs-3pc' },
        ],
      },
      { text: '微服务架构设计', link: '/distributed/theory/microservices' },
      { text: 'SOA vs 微服务：架构演进之路', link: '/distributed/theory/soa-vs-microservices' },
      { text: '康威定律与微服务拆分原则', link: '/distributed/theory/conways-law' },
      { text: '分布式系统性能指标：QPS、RT、并发数、TPS', link: '/distributed/theory/performance-metrics' },
    ],
  },
  {
    text: '分布式事务',
    link: '/distributed/transaction/',
    items: [
      {
        text: '分布式事务解决方案',
        link: '/distributed/transaction/solution/',
        collapsed: true,
        items: [
          { text: '分布式事务常见解决方案总览', link: '/distributed/transaction/solution/overview' },
          { text: 'Seata AT 模式：自动补偿与全局锁', link: '/distributed/transaction/solution/seata-at' },
          { text: 'Seata TCC 模式：Try-Confirm-Cancel 三阶段', link: '/distributed/transaction/solution/seata-tcc' },
          { text: 'Seata SAGA 模式：长事务编排', link: '/distributed/transaction/solution/seata-saga' },
          { text: '可靠消息最终一致性方案', link: '/distributed/transaction/solution/reliable-message' },
          { text: '最大努力通知方案', link: '/distributed/transaction/solution/best-effort-notify' },
          { text: 'AT vs TCC vs SAGA 对比与选型', link: '/distributed/transaction/solution/mode-compare' },
        ],
      },
      {
        text: '分布式事务原理',
        link: '/distributed/transaction/principle/',
        collapsed: true,
        items: [
          { text: 'XA 规范与两阶段提交', link: '/distributed/transaction/principle/xa' },
          { text: 'Seata 整体架构：TC、TM、RM 角色', link: '/distributed/transaction/principle/seata-architecture' },
          { text: 'Seata 全局事务与分支事务原理', link: '/distributed/transaction/principle/seata-global' },
          { text: 'Seata 高可用与 session 管理', link: '/distributed/transaction/principle/seata-ha' },
          { text: 'TCC 空回滚、悬挂、幂等问题', link: '/distributed/transaction/principle/tcc-problem' },
        ],
      },
      { text: '分布式事务面试高频问题汇总', link: '/distributed/transaction/interview-summary' },
    ],
  },
  {
    text: '分布式锁',
    link: '/distributed/lock/',
    items: [
      { text: '分布式锁应满足的条件：互斥、可重入、死锁避免、高性能', link: '/distributed/lock/requirements' },
      { text: 'Redis 分布式锁：SETNX + EXPIRE 的原子性问题', link: '/distributed/lock/redis-lock' },
      { text: 'Redisson 分布式锁实现：RLock 与看门狗机制', link: '/distributed/lock/redisson' },
      { text: 'Redisson 可重入锁原理', link: '/distributed/lock/redisson-reentrant' },
      { text: 'Redisson 公平锁 vs 非公平锁', link: '/distributed/lock/redisson-fair' },
      { text: 'Redisson 读写锁实现', link: '/distributed/lock/redisson-readwrite' },
      { text: 'Redisson 信号量（Semaphore）与CountDownLatch', link: '/distributed/lock/redisson-semaphore' },
      { text: 'Redisson 联锁（MultiLock）与红锁（RedLock）', link: '/distributed/lock/redisson-multilock' },
      { text: '分布式锁超时与时钟漂移问题', link: '/distributed/lock/timeout-clock' },
      { text: 'MySQL 分布式锁实现：唯一索引与悲观锁', link: '/distributed/lock/mysql-lock' },
      { text: 'ZooKeeper 分布式锁实现：临时顺序节点', link: '/distributed/lock/zookeeper-lock' },
      { text: 'Redis vs ZooKeeper vs etcd 分布式锁对比', link: '/distributed/lock/lock-compare' },
    ],
  },
  {
    text: '分布式协调服务',
    link: '/distributed/coordination/',
    items: [
      {
        text: 'ZooKeeper',
        link: '/distributed/coordination/zookeeper/',
        collapsed: true,
        items: [
          { text: 'ZooKeeper 数据模型：ZNode 与版本号', link: '/distributed/coordination/zookeeper/data-model' },
          { text: 'ZooKeeper 监听机制（Watch）：一次性触发原理', link: '/distributed/coordination/zookeeper/watch' },
          { text: 'ZooKeeper 会话机制与会话恢复', link: '/distributed/coordination/zookeeper/session' },
          { text: 'ZooKeeper Leader 选举：FastLeaderElection 算法', link: '/distributed/coordination/zookeeper/leader-election' },
          { text: 'ZooKeeper ACL 权限控制', link: '/distributed/coordination/zookeeper/acl' },
          { text: 'ZooKeeper 应用场景：配置管理、命名服务、分布式锁、Master 选举', link: '/distributed/coordination/zookeeper/use-case' },
          { text: 'ZooKeeper 典型应用：Kafka 控制器、Dubbo 注册中心', link: '/distributed/coordination/zookeeper/kafka-dubbo' },
          { text: 'ZooKeeper 与 etcd 对比', link: '/distributed/coordination/zookeeper/zookeeper-vs-etcd' },
        ],
      },
      {
        text: 'etcd',
        link: '/distributed/coordination/etcd/',
        collapsed: true,
        items: [
          { text: 'etcd 架构：Raft 共识 + MVCC + BoltDB', link: '/distributed/coordination/etcd/architecture' },
          { text: 'etcd vs ZooKeeper vs Consul 对比', link: '/distributed/coordination/etcd/compare' },
          { text: 'etcd 在 Kubernetes 中的应用：API Server 存储后端', link: '/distributed/coordination/etcd/kubernetes' },
        ],
      },
      {
        text: 'Nacos',
        link: '/distributed/coordination/nacos/',
        collapsed: true,
        items: [
          { text: 'Nacos 架构：注册中心与配置中心', link: '/distributed/coordination/nacos/architecture' },
          { text: 'Nacos 服务注册与心跳机制', link: '/distributed/coordination/nacos/service-registry' },
          { text: 'Nacos 配置管理：热更新与命名空间隔离', link: '/distributed/coordination/nacos/config' },
          { text: 'Nacos 集群模式与一致性协议', link: '/distributed/coordination/nacos/cluster' },
          { text: 'Nacos 临时实例与持久实例', link: '/distributed/coordination/nacos/instance' },
        ],
      },
    ],
  },
  {
    text: '服务治理',
    link: '/distributed/governance/',
    items: [
      { text: '服务发现：客户端发现 vs 服务端发现', link: '/distributed/governance/service-discovery' },
      { text: '服务注册与健康检查：心跳机制与故障剔除', link: '/distributed/governance/health-check' },
      { text: '负载均衡策略：轮询、随机、哈希、最小连接、加权', link: '/distributed/governance/load-balancing' },
      { text: '客户端负载均衡 vs 服务端负载均衡', link: '/distributed/governance/client-vs-server-lb' },
      { text: '服务熔断：断路器模式与状态转换', link: '/distributed/governance/circuit-breaker' },
      { text: '服务降级：多级降级策略与兜底方案', link: '/distributed/governance/degradation' },
      { text: '服务限流：单机限流与分布式限流', link: '/distributed/governance/rate-limit' },
      { text: '服务超时：超时传递与最佳实践', link: '/distributed/governance/timeout' },
      { text: '服务重试：重试策略与幂等性保证', link: '/distributed/governance/retry' },
      { text: '幂等性设计：接口幂等实现方案', link: '/distributed/governance/idempotency' },
      { text: '接口安全：签名验签、Token 认证、参数校验', link: '/distributed/governance/interface-security' },
    ],
  },
  {
    text: '服务调用',
    link: '/distributed/rpc/',
    items: [
      {
        text: 'Dubbo',
        link: '/distributed/rpc/dubbo/',
        collapsed: true,
        items: [
          { text: 'Dubbo 整体架构：Provider、Consumer、Registry、Monitor、Container', link: '/distributed/rpc/dubbo/architecture' },
          { text: 'Dubbo 协议：dubbo://、rmi://、http://、hessian://、gRPC', link: '/distributed/rpc/dubbo/protocol' },
          { text: 'Dubbo 负载均衡策略：Random、RoundRobin、LeastActive、一致性哈希', link: '/distributed/rpc/dubbo/loadbalance' },
          { text: 'Dubbo 路由机制：条件路由与脚本路由', link: '/distributed/rpc/dubbo/routing' },
          { text: 'Dubbo 集群容错：Failover、Failfast、Failsafe、Failback、Forking', link: '/distributed/rpc/dubbo/cluster' },
          { text: 'Dubbo 线程模型：IO 线程与业务线程分离', link: '/distributed/rpc/dubbo/thread-model' },
          { text: 'Dubbo 服务导出（Export）与引用（Refer）流程', link: '/distributed/rpc/dubbo/export-refer' },
          { text: 'Dubbo 过滤器链与扩展机制（SPI）', link: '/distributed/rpc/dubbo/spi' },
          { text: 'Dubbo 链路追踪：Traces、Spans、 baggage', link: '/distributed/rpc/dubbo/tracing' },
        ],
      },
      {
        text: 'Feign 与 OpenFeign',
        link: '/distributed/rpc/feign/',
        collapsed: true,
        items: [
          { text: 'Feign 声明式 HTTP 客户端原理', link: '/distributed/rpc/feign/principle' },
          { text: 'OpenFeign 集成 Spring Boot 与超时配置', link: '/distributed/rpc/feign/springboot' },
          { text: 'Feign 负载均衡：Ribbon 集成', link: '/distributed/rpc/feign/ribbon' },
          { text: 'Feign 拦截器与请求拦截', link: '/distributed/rpc/feign/interceptor' },
          { text: 'Feign 压缩与连接池配置', link: '/distributed/rpc/feign/compression' },
        ],
      },
      { text: 'gRPC', link: '/distributed/rpc/grpc' },
      { text: 'RESTful vs RPC vs gRPC 对比', link: '/distributed/rpc/rest-rpc' },
    ],
  },
  {
    text: '典型分布式场景方案',
    link: '/distributed/scenario/',
    items: [
      {
        text: '统一认证与 SSO',
        link: '/distributed/scenario/auth/',
        collapsed: true,
        items: [
          { text: '微服务统一认证方案：Session 共享 vs Token 方案', link: '/distributed/scenario/auth/unified-auth' },
          { text: 'CAS 单点登录原理与流程', link: '/distributed/scenario/auth/cas-sso' },
          { text: 'OAuth 2.0 在微服务中的使用：授权服务与资源服务分离', link: '/distributed/scenario/auth/oauth2-microservice' },
          { text: '分布式 Session：Spring Session + Redis 方案', link: '/distributed/scenario/auth/distributed-session' },
          { text: '无状态 Token 方案：JWT 生成、刷新、注销与黑名单', link: '/distributed/scenario/auth/jwt-stateless' },
        ],
      },
      {
        text: '多级缓存架构',
        link: '/distributed/scenario/cache/',
        collapsed: true,
        items: [
          { text: '多级缓存模式：本地缓存（Caffeine/Guava）→ 分布式缓存（Redis）→ 数据库', link: '/distributed/scenario/cache/multi-level-cache' },
          { text: '缓存与数据库双写一致性：Cache Aside、Read Through、Write Through、Write Behind', link: '/distributed/scenario/cache/cache-db-consistency' },
          { text: '缓存穿透：布隆过滤器 + 空值缓存方案', link: '/distributed/scenario/cache/cache-penetration' },
          { text: '缓存击穿：互斥锁 + 逻辑过期双检方案', link: '/distributed/scenario/cache/cache-breakdown' },
          { text: '缓存雪崩：过期时间打散 + 熔断降级方案', link: '/distributed/scenario/cache/cache-avalanche' },
          { text: '热点数据探测与自动扩容', link: '/distributed/scenario/cache/hot-data-detection' },
        ],
      },
      {
        text: '分布式文件与对象存储',
        link: '/distributed/scenario/storage/',
        collapsed: true,
        items: [
          { text: 'MinIO 分布式对象存储架构与 S3 兼容', link: '/distributed/scenario/storage/minio' },
          { text: 'FastDFS 分布式文件系统原理', link: '/distributed/scenario/storage/fastdfs' },
          { text: '文件分片上传与断点续传实现', link: '/distributed/scenario/storage/file-sharding' },
          { text: 'CDN + OSS 分发加速架构设计', link: '/distributed/scenario/storage/cdn-oss' },
        ],
      },
      {
        text: '多机房与数据同步',
        link: '/distributed/scenario/datacenter/',
        collapsed: true,
        items: [
          { text: '同城双活架构设计：流量分配与数据同步', link: '/distributed/scenario/datacenter/active-active' },
          { text: '异地多活架构：单元化部署与数据同步方案', link: '/distributed/scenario/datacenter/multi-region' },
          { text: '跨机房数据同步方案：MySQL binlog + Canal + Kafka', link: '/distributed/scenario/datacenter/cross-datacenter-sync' },
          { text: '全局递增 ID 在分库分表中的实现', link: '/distributed/scenario/datacenter/sharding-id' },
        ],
      },
      {
        text: '流量控制与弹性策略',
        link: '/distributed/scenario/flow/',
        collapsed: true,
        items: [
          { text: '全链路限流：网关层 → 应用层 → 资源层限流方案', link: '/distributed/scenario/flow/full-link-rate-limit' },
          { text: '接口流量削峰：消息队列 + 令牌桶 / 漏桶算法', link: '/distributed/scenario/flow/peak-shaving' },
          { text: '服务弹性降级：核心链路识别与降级策略', link: '/distributed/scenario/flow/elastic-degradation' },
          { text: '超时重试风暴治理：重试策略与熔断降级组合', link: '/distributed/scenario/flow/retry-storm' },
          { text: '系统自适应限流：Sentinel 与 Prometheus 联动', link: '/distributed/scenario/flow/self-adaptive-limit' },
        ],
      },
      {
        text: '数据处理与批任务',
        link: '/distributed/scenario/batch/',
        collapsed: true,
        items: [
          { text: '分布式批量任务框架设计：分片任务与结果聚合', link: '/distributed/scenario/batch/batch-task' },
          { text: '数据同步任务：全量同步与增量同步方案', link: '/distributed/scenario/batch/data-sync-task' },
          { text: '分布式唯一任务执行：乐观锁 + 分布式锁双保险', link: '/distributed/scenario/batch/unique-task' },
          { text: '定时任务的分布式化：广播模式与分片模式', link: '/distributed/scenario/batch/distributed-cron' },
        ],
      },
      {
        text: '统一异常与日志',
        link: '/distributed/scenario/log/',
        collapsed: true,
        items: [
          { text: '微服务统一异常处理：全局异常码 + 标准化响应体', link: '/distributed/scenario/log/unified-exception' },
          { text: '分布式日志追踪：TraceId + SpanId 全链路串联', link: '/distributed/scenario/log/distributed-trace' },
          { text: '日志聚合方案：ELK + Kafka 分流架构', link: '/distributed/scenario/log/log-aggregation' },
          { text: '业务链路黑白盒监控：Metrics + Tracing + Logging', link: '/distributed/scenario/log/observability' },
        ],
      },
      { text: '分布式场景面试高频问题汇总', link: '/distributed/scenario/interview-summary' },
    ],
  },
]
