export const frameworkSidebar = [
    {
        text: "Spring",
        link: "/framework/spring/",
        items: [
            { text: "Spring IoC 容器（BeanFactory vs ApplicationContext）", link: "/framework/spring/ioc-container" },
            { text: "Bean 生命周期", link: "/framework/spring/bean-lifecycle" },
            { text: "BeanPostProcessor 原理", link: "/framework/spring/bean-post-processor" },
            { text: "循环依赖三级缓存", link: "/framework/spring/circular-dependency" },
            { text: "为什么需要三级缓存", link: "/framework/spring/three-level-cache" },
            { text: "构造器注入无法解决循环依赖", link: "/framework/spring/constructor-circular" },
            { text: "Spring AOP 原理", link: "/framework/spring/aop" },
            { text: "JDK 动态代理 vs CGLIB", link: "/framework/spring/proxy-comparison" },
            { text: "通知执行顺序", link: "/framework/spring/advice-order" },
            { text: "Spring 事务管理", link: "/framework/spring/transaction" },
            { text: "事务传播行为（7种）", link: "/framework/spring/transaction-propagation" },
            { text: "@Transactional 失效场景", link: "/framework/spring/transaction-failure" },
            { text: "Spring 事件监听机制", link: "/framework/spring/event-listener" },
            { text: "FactoryBean vs BeanFactory", link: "/framework/spring/factory-bean" },
            { text: "Spring 设计模式总结", link: "/framework/spring/design-patterns" },
        ],
    },
    {
        text: "Spring Boot",
        link: "/framework/springboot/",
        items: [
            { text: "Spring Boot 自动配置原理", link: "/framework/springboot/auto-configuration" },
            { text: "@SpringBootApplication 注解解析", link: "/framework/springboot/springboot-application" },
            { text: "Spring Boot Starter 原理", link: "/framework/springboot/starter" },
            { text: "自定义 Starter 实现", link: "/framework/springboot/custom-starter" },
            { text: "Spring Boot 配置文件加载顺序", link: "/framework/springboot/config-order" },
            { text: "Spring Boot Actuator 监控端点", link: "/framework/springboot/actuator" },
            { text: "Spring Boot 启动流程", link: "/framework/springboot/startup-process" },
            { text: "嵌入式 Web 容器原理", link: "/framework/springboot/embedded-container" },
            { text: "Spring Boot 条件注解", link: "/framework/springboot/conditional-annotations" },
        ],
    },
    {
        text: "MyBatis",
        link: "/framework/mybatis/",
        items: [
            { text: "MyBatis 核心组件", link: "/framework/mybatis/components" },
            { text: "MyBatis 执行流程", link: "/framework/mybatis/execution-flow" },
            { text: "一级缓存与二级缓存", link: "/framework/mybatis/cache" },
            { text: "二级缓存问题与解决", link: "/framework/mybatis/cache-issues" },
            { text: "动态 SQL 原理", link: "/framework/mybatis/dynamic-sql" },
            { text: "Mapper 代理原理", link: "/framework/mybatis/mapper-proxy" },
            { text: "MyBatis 与 Spring 整合原理", link: "/framework/mybatis/spring-integration" },
            { text: "MyBatis 插件机制", link: "/framework/mybatis/plugin" },
            { text: "MyBatis-Plus 常用特性", link: "/framework/mybatis/mybatis-plus" },
        ],
    },
    {
        text: "Spring Cloud",
        link: "/framework/springcloud/",
        items: [
            { text: "Spring Cloud 生态组件概览", link: "/framework/springcloud/overview" },
            { text: "服务注册与发现（Eureka/Nacos）", link: "/framework/springcloud/service-discovery" },
            { text: "Eureka 自我保护机制", link: "/framework/springcloud/eureka-self-preservation" },
            { text: "配置中心（Config/Nacos）", link: "/framework/springcloud/config-center" },
            { text: "配置热刷新原理", link: "/framework/springcloud/config-refresh" },
            { text: "服务网关（Gateway vs Zuul）", link: "/framework/springcloud/gateway" },
            { text: "Gateway 路由断言与过滤器", link: "/framework/springcloud/gateway-filters" },
            { text: "服务调用（Feign）原理", link: "/framework/springcloud/feign" },
            { text: "Feign 重试与降级", link: "/framework/springcloud/feign-retry" },
            { text: "负载均衡（Ribbon/LoadBalancer）", link: "/framework/springcloud/loadbalancer" },
            { text: "服务熔断（Hystrix/Sentinel）", link: "/framework/springcloud/circuit-breaker" },
            { text: "Sentinel 限流规则", link: "/framework/springcloud/sentinel" },
            { text: "分布式链路追踪（Sleuth+Zipkin）", link: "/framework/springcloud/tracing" },
            { text: "Nacos 服务发现与配置管理", link: "/framework/springcloud/nacos" },
        ],
    },
    {
        text: "消息队列",
        link: "/framework/mq/",
        items: [
            { text: "消息队列应用场景", link: "/framework/mq/scenarios" },
            { text: "Kafka 架构深度解析", link: "/framework/mq/kafka-architecture" },
            { text: "Kafka 分区与消费者组", link: "/framework/mq/kafka-partition" },
            { text: "Kafka 消息可靠性保证", link: "/framework/mq/kafka-reliability" },
            { text: "Kafka 顺序消息实现", link: "/framework/mq/kafka-ordering" },
            { text: "Kafka 消息丢失与重复消费", link: "/framework/mq/kafka-message-loss" },
            { text: "RocketMQ 架构深度解析", link: "/framework/mq/rocketmq-architecture" },
            { text: "RocketMQ 事务消息", link: "/framework/mq/rocketmq-transaction" },
            { text: "RocketMQ 顺序消息", link: "/framework/mq/rocketmq-ordering" },
            { text: "Kafka vs RocketMQ vs RabbitMQ", link: "/framework/mq/comparison" },
            { text: "消息队列选型矩阵", link: "/framework/mq/selection" },
            { text: "消息积压处理策略", link: "/framework/mq/backlog" },
        ],
    },
    {
        text: "RPC 与注册中心",
        link: "/framework/rpc/",
        items: [
            { text: "RPC 调用原理", link: "/framework/rpc/rpc-principle" },
            { text: "Dubbo 架构深度解析", link: "/framework/rpc/dubbo-architecture" },
            { text: "Dubbo 服务暴露与引用", link: "/framework/rpc/dubbo-export" },
            { text: "Dubbo 负载均衡策略", link: "/framework/rpc/dubbo-loadbalance" },
            { text: "Dubbo 容错机制", link: "/framework/rpc/dubbo-fault-tolerance" },
            { text: "Dubbo 泛化调用", link: "/framework/rpc/dubbo-generic" },
            { text: "gRPC 与 Protocol Buffers", link: "/framework/rpc/grpc" },
            { text: "gRPC 四种通信模式", link: "/framework/rpc/grpc-modes" },
            { text: "Dubbo vs gRPC vs Feign", link: "/framework/rpc/rpc-comparison" },
            { text: "ZooKeeper 核心概念", link: "/framework/rpc/zookeeper" },
            { text: "ZooKeeper 数据模型与 ZAB 协议", link: "/framework/rpc/zookeeper-zab" },
            { text: "ZooKeeper 应用场景", link: "/framework/rpc/zookeeper-scenarios" },
            { text: "Nacos 架构解析", link: "/framework/rpc/nacos" },
            { text: "ZooKeeper vs Nacos vs Eureka", link: "/framework/rpc/registry-comparison" },
        ],
    },
    {
        text: "搜索引擎",
        link: "/framework/search/",
        items: [
            { text: "Elasticsearch 核心概念（索引/分片/副本）", link: "/framework/search/es-concepts" },
            { text: "Elasticsearch 写入流程", link: "/framework/search/es-write" },
            { text: "Elasticsearch 查询流程", link: "/framework/search/es-query" },
            { text: "Elasticsearch 倒排索引原理", link: "/framework/search/inverted-index" },
            { text: "ES 分词器与中文分词", link: "/framework/search/analyzer" },
            { text: "ES 集群与分片分配", link: "/framework/search/cluster" },
            { text: "Elasticsearch vs Solr", link: "/framework/search/es-vs-solr" },
        ],
    },
    {
        text: "其他中间件",
        link: "/framework/other/",
        items: [
            { text: "Quartz 定时任务调度", link: "/framework/other/quartz" },
            { text: "XXL-JOB 分布式调度", link: "/framework/other/xxl-job" },
            { text: "ElasticJob 原理", link: "/framework/other/elastic-job" },
            { text: "ShardingSphere 分库分表", link: "/framework/other/shardingsphere" },
            { text: "Apollo 配置中心", link: "/framework/other/apollo" },
            { text: "Nacos 配置中心", link: "/framework/other/nacos-config" },
        ],
    }
];