export const frameworkSidebar = [
  {
    text: 'Spring Framework',
    link: '/framework/spring/',
    items: [
      {
        text: 'Spring 核心概念',
        link: '/framework/spring/core/',
        collapsed: true,
        items: [
          { text: 'Spring 架构总览', link: '/framework/spring/core/architecture' },
          { text: 'Spring IoC 容器', link: '/framework/spring/core/ioc' },
          { text: 'IoC 容器对比', link: '/framework/spring/core/beanfactory-context' },
          { text: 'Spring Bean 生命周期', link: '/framework/spring/core/bean-lifecycle' },
          { text: 'Spring Bean 作用域', link: '/framework/spring/core/bean-scope' },
          { text: 'Bean 循环依赖', link: '/framework/spring/core/circular-dependency' },
          { text: '构造器注入 vs Setter', link: '/framework/spring/core/injection-type' },
          { text: '注入方式对比', link: '/framework/spring/core/autowired-resource' },
        ],
      },
      {
        text: 'IoC 容器原理',
        link: '/framework/spring/ioc-principle/',
        collapsed: true,
        items: [
          { text: 'Spring 启动流程', link: '/framework/spring/ioc-principle/startup-flow' },
          { text: 'Bean 创建流程', link: '/framework/spring/ioc-principle/bean-create' },
          { text: 'BeanPostProcessor 原理', link: '/framework/spring/ioc-principle/bean-post-processor' },
          { text: 'BeanFactory 后置处理器', link: '/framework/spring/ioc-principle/bfpp' },
          { text: 'FactoryBean', link: '/framework/spring/ioc-principle/factory-bean' },
          { text: '依赖注入源码', link: '/framework/spring/ioc-principle/di-source' },
        ],
      },
      {
        text: 'Spring AOP',
        link: '/framework/spring/aop/',
        collapsed: true,
        items: [
          { text: 'AOP 核心概念', link: '/framework/spring/aop/aop-concept' },
          { text: '动态代理 vs CGLIB', link: '/framework/spring/aop/jdk-cglib' },
          { text: 'Spring AOP 代理选择', link: '/framework/spring/aop/aop-proxy-select' },
          { text: 'AOP 源码解析', link: '/framework/spring/aop/aop-source' },
          { text: 'AspectJ vs AOP', link: '/framework/spring/aop/aspectj-vs-aop' },
          { text: '@AspectJ 注解配置', link: '/framework/spring/aop/aspectj-annotation' },
          { text: 'AOP 应用场景', link: '/framework/spring/aop/aop-usecase' },
          { text: 'Spring 事务管理', link: '/framework/spring/aop/transaction' },
          { text: '事务传播行为', link: '/framework/spring/aop/transaction-propagation' },
          { text: '事务失效场景', link: '/framework/spring/aop/transaction-fail' },
        ],
      },
      {
        text: 'Spring MVC',
        link: '/framework/spring/mvc/',
        collapsed: true,
        items: [
          { text: 'Spring MVC 请求处理流程', link: '/framework/spring/mvc/flow' },
          { text: 'DispatcherServlet 源码', link: '/framework/spring/mvc/dispatcher-servlet' },
          { text: 'HandlerMapping 与 Handler', link: '/framework/spring/mvc/handler-mapping' },
          { text: '拦截器 vs 过滤器', link: '/framework/spring/mvc/interceptor-filter' },
          { text: '参数绑定', link: '/framework/spring/mvc/param-binding' },
          { text: '视图解析与视图技术', link: '/framework/spring/mvc/view-resolver' },
          { text: '异常处理', link: '/framework/spring/mvc/exception-handler' },
          { text: '文件上传与下载', link: '/framework/spring/mvc/file-upload' },
          { text: 'REST 设计', link: '/framework/spring/mvc/restful' },
        ],
      },
      {
        text: 'Spring 注解与配置',
        link: '/framework/spring/annotation/',
        collapsed: true,
        items: [
          { text: '@Configuration', link: '/framework/spring/annotation/configuration' },
          { text: 'ComponentScan', link: '/framework/spring/annotation/component-scan' },
          { text: '@Conditional 条件装配', link: '/framework/spring/annotation/conditional' },
          { text: '@Import 导入器', link: '/framework/spring/annotation/import' },
          { text: 'Spring 属性注入', link: '/framework/spring/annotation/property-source' },
          { text: '@Profile 环境隔离', link: '/framework/spring/annotation/profile' },
          { text: 'Spring 5 @Indexed', link: '/framework/spring/annotation/indexed' },
        ],
      },
      {
        text: 'Spring 高级特性',
        link: '/framework/spring/advanced/',
        collapsed: true,
        items: [
          { text: 'Spring 事件机制', link: '/framework/spring/advanced/event' },
          { text: 'Spring 资源加载', link: '/framework/spring/advanced/resource' },
          { text: 'Spring 国际化', link: '/framework/spring/advanced/i18n' },
          { text: 'Spring 类型转换', link: '/framework/spring/advanced/type-converter' },
          { text: 'Spring 格式化', link: '/framework/spring/advanced/formatter' },
          { text: 'Spring 验证', link: '/framework/spring/advanced/validation' },
          { text: '动态注册 Bean', link: '/framework/spring/advanced/bean-registry' },
          { text: 'Spring 扩展点', link: '/framework/spring/advanced/extension-point' },
        ],
      },
    ],
  },
  {
    text: 'Spring Boot',
    link: '/framework/springboot/',
    items: [
      {
        text: 'Spring Boot 核心',
        link: '/framework/springboot/core/',
        collapsed: true,
        items: [
          { text: 'SB vs Spring', link: '/framework/springboot/core/springboot-vs-spring' },
          { text: 'Spring Boot 启动流程', link: '/framework/springboot/core/startup-flow' },
          { text: 'SpringBoot 注解', link: '/framework/springboot/core/application-annotation' },
          { text: '自动配置原理', link: '/framework/springboot/core/autoconfig' },
          { text: '自动配置文件', link: '/framework/springboot/core/auto-config-imports' },
          { text: '条件注解详解', link: '/framework/springboot/core/condition-annotation' },
          { text: 'Spring Boot 外部化配置', link: '/framework/springboot/core/external-config' },
          { text: 'Bootstrap.yml 加载顺序', link: '/framework/springboot/core/bootstrap' },
        ],
      },
      {
        text: 'Spring Boot Starter',
        link: '/framework/springboot/starter/',
        collapsed: true,
        items: [
          { text: '自定义 Starter 流程', link: '/framework/springboot/starter/custom-starter' },
          { text: 'Starter 自动配置原理', link: '/framework/springboot/starter/starter-autoconfig' },
          { text: 'SB Actuator', link: '/framework/springboot/starter/actuator' },
          { text: 'Spring Boot Banner', link: '/framework/springboot/starter/banner' },
        ],
      },
      {
        text: 'Spring Boot 常用功能',
        link: '/framework/springboot/feature/',
        collapsed: true,
        items: [
          { text: 'Spring Boot 日志配置', link: '/framework/springboot/feature/logging' },
          { text: 'Spring Boot 异常处理', link: '/framework/springboot/feature/error-handler' },
          { text: 'Spring Boot 静态资源', link: '/framework/springboot/feature/static-resource' },
          { text: 'CORS 跨域配置', link: '/framework/springboot/feature/cors' },
          { text: 'SB 拦截器', link: '/framework/springboot/feature/interceptor-filter' },
          { text: 'SB WebSocket', link: '/framework/springboot/feature/websocket' },
          { text: 'SB GraphQL', link: '/framework/springboot/feature/graphql' },
        ],
      },
      { text: 'Spring Boot 面试高频问题', link: '/framework/springboot/interview-summary' },
    ],
  },
  {
    text: 'MyBatis',
    link: '/framework/mybatis/',
    items: [
      {
        text: 'MyBatis 核心原理',
        link: '/framework/mybatis/core/',
        collapsed: true,
        items: [
          { text: 'MyBatis 整体架构', link: '/framework/mybatis/core/architecture' },
          { text: 'MyBatis 初始化流程', link: '/framework/mybatis/core/init-flow' },
          { text: 'SessionFactory', link: '/framework/mybatis/core/sqlsessionfactory' },
          { text: '获取 Mapper', link: '/framework/mybatis/core/sqlsession-mapper' },
          { text: 'Mapper 代理对象生成', link: '/framework/mybatis/core/mapper-proxy' },
        ],
      },
      {
        text: 'MyBatis SQL 执行流程',
        link: '/framework/mybatis/sql/',
        collapsed: true,
        items: [
          { text: 'Executor 执行器类型', link: '/framework/mybatis/sql/executor' },
          { text: 'StatementHandler 原理', link: '/framework/mybatis/sql/statement-handler' },
          { text: 'ParameterHandler', link: '/framework/mybatis/sql/parameter-handler' },
          { text: 'ResultSetHandler', link: '/framework/mybatis/sql/resultset-handler' },
          { text: 'TypeHandler', link: '/framework/mybatis/sql/type-handler' },
          { text: 'MyBatis 一级缓存', link: '/framework/mybatis/sql/cache' },
          { text: 'MyBatis 二级缓存失效', link: '/framework/mybatis/sql/cache-invalid' },
        ],
      },
      {
        text: 'MyBatis XML 映射',
        link: '/framework/mybatis/xml/',
        collapsed: true,
        items: [
          { text: 'MyBatis XML mapper', link: '/framework/mybatis/xml/xml-mapper' },
          { text: 'resultMap 配置', link: '/framework/mybatis/xml/resultmap' },
          { text: '嵌套查询与 N+1', link: '/framework/mybatis/xml/nested-query' },
          { text: '动态 SQL', link: '/framework/mybatis/xml/dynamic-sql' },
          { text: '注解 vs XML', link: '/framework/mybatis/xml/annotation-vs-xml' },
        ],
      },
      {
        text: 'MyBatis Plus 进阶',
        link: '/framework/mybatis-plus/',
        collapsed: true,
        items: [
          { text: 'MyBatis Plus 快速上手', link: '/framework/mybatis-plus/quickstart' },
          { text: 'CRUD 与 Wrapper', link: '/framework/mybatis-plus/wrapper' },
          { text: '分页插件', link: '/framework/mybatis-plus/pagination' },
          { text: '自动填充', link: '/framework/mybatis-plus/auto-fill' },
          { text: '逻辑删除', link: '/framework/mybatis-plus/logic-delete' },
          { text: '乐观锁', link: '/framework/mybatis-plus/optimistic-lock' },
          { text: '多租户插件', link: '/framework/mybatis-plus/tenant' },
          { text: 'SQL 性能分析', link: '/framework/mybatis-plus/sql-analyze' },
        ],
      },
      { text: 'MyBatis 面试高频问题', link: '/framework/mybatis/interview-summary' },
    ],
  },
  {
    text: 'ORM 与数据库访问',
    link: '/framework/orm/',
    items: [
      { text: 'ORM 框架对比', link: '/framework/orm/orm-compare' },
      { text: 'JDBC 执行流程', link: '/framework/orm/jdbc' },
      { text: '数据库连接池对比', link: '/framework/orm/connection-pool' },
      { text: 'HikariCP 原理', link: '/framework/orm/hikaricp' },
          { text: 'JdbcTemplate', link: '/framework/orm/jdbc-template' },
    ],
  },
  {
    text: 'Spring Cloud 全家桶',
    link: '/framework/springcloud/',
    items: [
      {
        text: 'Spring Cloud 基础',
        link: '/framework/springcloud/basic/',
        collapsed: true,
        items: [
          { text: 'Spring Cloud 版本命名', link: '/framework/springcloud/basic/version' },
          { text: 'SC 与 SB 版本', link: '/framework/springcloud/basic/boot-version' },
          { text: 'Spring Cloud 组件总览', link: '/framework/springcloud/basic/overview' },
          { text: 'SCA vs SCN 对比', link: '/framework/springcloud/basic/alibaba-vs-netflix' },
        ],
      },
      {
        text: '服务注册与配置',
        link: '/framework/springcloud/registry/',
        collapsed: true,
        items: [
          { text: 'Nacos 服务注册', link: '/framework/springcloud/registry/nacos-discovery' },
          { text: 'Nacos 配置中心', link: '/framework/springcloud/registry/nacos-config' },
          { text: 'Nacos 热更新', link: '/framework/springcloud/registry/nacos-refresh' },
          { text: 'Nacos 集群与持久化', link: '/framework/springcloud/registry/nacos-cluster' },
        ],
      },
      {
        text: '服务调用与网关',
        link: '/framework/springcloud/gateway/',
        collapsed: true,
        items: [
          { text: 'OpenFeign 客户端', link: '/framework/springcloud/gateway/openfeign' },
          { text: 'Feign 传参与继承', link: '/framework/springcloud/gateway/feign-advanced' },
          { text: 'Gateway 路由配置', link: '/framework/springcloud/gateway/gateway-route' },
          { text: 'Gateway 过滤器', link: '/framework/springcloud/gateway/gateway-filter' },
          { text: 'Gateway 限流', link: '/framework/springcloud/gateway/gateway-rate-limit' },
          { text: 'Gateway 熔断降级', link: '/framework/springcloud/gateway/gateway-circuit-breaker' },
        ],
      },
      {
        text: '服务容错与治理',
        link: '/framework/springcloud/resilience/',
        collapsed: true,
        items: [
          { text: 'Sentinel 流量控制', link: '/framework/springcloud/resilience/sentinel-flow' },
          { text: 'Sentinel 注解', link: '/framework/springcloud/resilience/sentinel-resource' },
          { text: 'Sentinel 规则持久化', link: '/framework/springcloud/resilience/sentinel-persist' },
          { text: '熔断器对比', link: '/framework/springcloud/resilience/sentinel-vs-hystrix' },
          { text: 'Sleuth 链路追踪', link: '/framework/springcloud/resilience/sleuth-zipkin' },
        ],
      },
      {
        text: '消息与异步',
        link: '/framework/springcloud/message/',
        collapsed: true,
        items: [
          { text: 'SC Stream', link: '/framework/springcloud/message/stream' },
          { text: 'Spring Cloud Bus', link: '/framework/springcloud/message/bus' },
          { text: 'Bus + Nacos 刷新', link: '/framework/springcloud/message/bus-nacos' },
        ],
      },
      {
        text: '微服务实战',
        link: '/framework/springcloud/practice/',
        collapsed: true,
        items: [
          { text: 'Seata AT 模式', link: '/framework/springcloud/practice/seata' },
          { text: '统一认证方案', link: '/framework/springcloud/practice/oauth2-jwt' },
          { text: '多环境配置', link: '/framework/springcloud/practice/multi-env' },
          { text: 'Spring Cloud 面试高频', link: '/framework/springcloud/practice/interview-summary' },
        ],
      },
    ],
  },
  {
    text: 'Spring Security',
    link: '/framework/springsecurity/',
    items: [
      {
        text: 'Security 核心概念',
        link: '/framework/springsecurity/core/',
        collapsed: true,
        items: [
          { text: '认证与授权流程', link: '/framework/springsecurity/core/flow' },
          { text: 'Security 过滤器链', link: '/framework/springsecurity/core/filter-chain' },
          { text: 'WebSecurityConfig', link: '/framework/springsecurity/core/config-adapter' },
          { text: '用户详情服务', link: '/framework/springsecurity/core/userdetails' },
          { text: 'BCrypt 密码加密', link: '/framework/springsecurity/core/password-encoder' },
        ],
      },
      {
        text: '认证机制',
        link: '/framework/springsecurity/auth/',
        collapsed: true,
        items: [
          { text: '表单登录流程', link: '/framework/springsecurity/auth/form-login' },
          { text: 'Session 会话管理', link: '/framework/springsecurity/auth/session' },
          { text: 'Remember-Me', link: '/framework/springsecurity/auth/remember-me' },
          { text: '短信验证码登录', link: '/framework/springsecurity/auth/sms-login' },
          { text: 'OAuth2 第三方登录', link: '/framework/springsecurity/auth/oauth2-login' },
          { text: 'CAS 单点登录', link: '/framework/springsecurity/auth/cas' },
        ],
      },
      {
        text: '授权与权限',
        link: '/framework/springsecurity/permission/',
        collapsed: true,
        items: [
          { text: 'Authority vs Role', link: '/framework/springsecurity/permission/authority-role' },
          { text: '权限注解对比', link: '/framework/springsecurity/permission/preauthorize' },
          { text: '方法级别安全', link: '/framework/springsecurity/permission/method-security' },
          { text: '动态权限决策', link: '/framework/springsecurity/permission/access-decision' },
          { text: 'RBAC 权限模型', link: '/framework/springsecurity/permission/rbac' },
          { text: '权限数据模型', link: '/framework/springsecurity/permission/permission-model' },
        ],
      },
      {
        text: 'JWT 与无状态认证',
        link: '/framework/springsecurity/jwt/',
        collapsed: true,
        items: [
          { text: 'JWT 生成与验证', link: '/framework/springsecurity/jwt/jwt' },
          { text: 'JWT 无状态认证流程', link: '/framework/springsecurity/jwt/jwt-filter' },
          { text: 'JWT 刷新与黑名单', link: '/framework/springsecurity/jwt/jwt-refresh' },
          { text: 'Token 防盗用', link: '/framework/springsecurity/jwt/jwt-security' },
        ],
      },
      {
        text: 'Security 高级特性',
        link: '/framework/springsecurity/advanced/',
        collapsed: true,
        items: [
          { text: 'CSRF 防护', link: '/framework/springsecurity/advanced/csrf' },
          { text: 'CORS 跨域', link: '/framework/springsecurity/advanced/cors' },
          { text: 'XSS 防护', link: '/framework/springsecurity/advanced/xss' },
          { text: 'Gateway 统一鉴权', link: '/framework/springsecurity/advanced/gateway-auth' },
          { text: 'Security 6.x', link: '/framework/springsecurity/advanced/v6' },
          { text: 'Security 面试高频', link: '/framework/springsecurity/advanced/interview-summary' },
        ],
      },
    ],
  },
  {
    text: 'Shiro',
    link: '/framework/shiro/',
    items: [
      {
        text: 'Shiro 核心概念',
        link: '/framework/shiro/core/',
        collapsed: true,
        items: [
          { text: 'Shiro 架构', link: '/framework/shiro/core/architecture' },
          { text: 'Shiro vs Security', link: '/framework/shiro/core/vs-spring-security' },
          { text: 'Shiro 认证流程', link: '/framework/shiro/core/authentication' },
          { text: 'Shiro 授权流程', link: '/framework/shiro/core/authorization' },
        ],
      },
      {
        text: 'Shiro 认证机制',
        link: '/framework/shiro/auth/',
        collapsed: true,
        items: [
          { text: 'IniRealm 配置', link: '/framework/shiro/auth/ini-realm' },
          { text: 'JDBCRealm 数据库', link: '/framework/shiro/auth/jdbc-realm' },
          { text: '自定义 Realm', link: '/framework/shiro/auth/custom-realm' },
          { text: '密码加密与盐值', link: '/framework/shiro/auth/credentials-matcher' },
          { text: 'Session 管理', link: '/framework/shiro/auth/session' },
          { text: 'RememberMe', link: '/framework/shiro/auth/remember-me' },
        ],
      },
      {
        text: 'Shiro 与 Spring Boot',
        link: '/framework/shiro/springboot/',
        collapsed: true,
        items: [
          { text: 'Shiro + SB', link: '/framework/shiro/springboot/springboot' },
          { text: 'Shiro 过滤器链', link: '/framework/shiro/springboot/filter-chain' },
          { text: 'Shiro 注解', link: '/framework/shiro/springboot/annotation' },
          { text: 'Shiro JSP 标签', link: '/framework/shiro/springboot/jsp-tag' },
          { text: 'Shiro 缓存', link: '/framework/shiro/springboot/cache' },
          { text: 'Shiro Session', link: '/framework/shiro/springboot/session-redis' },
        ],
      },
      {
        text: 'Shiro 实战与安全',
        link: '/framework/shiro/practice/',
        collapsed: true,
        items: [
          { text: 'Shiro JWT 认证', link: '/framework/shiro/practice/jwt' },
          { text: 'Shiro 权限模型', link: '/framework/shiro/practice/permission-model' },
          { text: 'Shiro CSRF 防护', link: '/framework/shiro/practice/csrf' },
          { text: 'Shiro 面试高频', link: '/framework/shiro/practice/interview-summary' },
        ],
      },
    ],
  },
]
