export const frameworkSidebar = [
  {
    text: 'Spring Framework',
    link: '/framework/spring/',
    items: [
      {
        text: 'Spring 核心概念',
        link: '/framework/spring/core/',
        collapsed: true,
        items: [
          { text: 'Spring 架构总览与模块划分', link: '/framework/spring/core/architecture' },
          { text: 'Spring IoC 容器：控制反转与依赖注入', link: '/framework/spring/core/ioc' },
          { text: 'BeanFactory vs ApplicationContext', link: '/framework/spring/core/beanfactory-context' },
          { text: 'Spring Bean 生命周期全流程', link: '/framework/spring/core/bean-lifecycle' },
          { text: 'Spring Bean 作用域：singleton、prototype、request、session', link: '/framework/spring/core/bean-scope' },
          { text: 'Bean 循环依赖：三级缓存与解决过程', link: '/framework/spring/core/circular-dependency' },
          { text: '构造器注入 vs Setter 注入 vs 字段注入', link: '/framework/spring/core/injection-type' },
          { text: '@Autowired vs @Resource vs @Inject', link: '/framework/spring/core/autowired-resource' },
        ],
      },
      {
        text: 'IoC 容器原理',
        link: '/framework/spring/ioc-principle/',
        collapsed: true,
        items: [
          { text: 'Spring 启动流程源码解析', link: '/framework/spring/ioc-principle/startup-flow' },
          { text: 'Bean 创建流程：实例化、属性填充、初始化', link: '/framework/spring/ioc-principle/bean-create' },
          { text: 'BeanPostProcessor 与前置/后置处理器', link: '/framework/spring/ioc-principle/bean-post-processor' },
          { text: 'BeanFactoryPostProcessor 与属性占位符替换', link: '/framework/spring/ioc-principle/bfpp' },
          { text: 'FactoryBean 与 @Bean 注解解析', link: '/framework/spring/ioc-principle/factory-bean' },
          { text: '依赖注入源码：setAutowiredField() 过程', link: '/framework/spring/ioc-principle/di-source' },
        ],
      },
      {
        text: 'Spring AOP',
        link: '/framework/spring/aop/',
        collapsed: true,
        items: [
          { text: 'AOP 核心概念：切点、切面、通知、连接点', link: '/framework/spring/aop/aop-concept' },
          { text: 'JDK 动态代理 vs CGLIB 动态代理', link: '/framework/spring/aop/jdk-cglib' },
          { text: 'Spring AOP 代理选择规则：何时用 JDK 代理，何时用 CGLIB', link: '/framework/spring/aop/aop-proxy-select' },
          { text: 'AOP 源码解析：ProxyFactory 与 JdkDynamicAopProxy', link: '/framework/spring/aop/aop-source' },
          { text: 'AspectJ 与 Spring AOP 对比', link: '/framework/spring/aop/aspectj-vs-aop' },
          { text: '@AspectJ 注解驱动的 AOP 配置', link: '/framework/spring/aop/aspectj-annotation' },
          { text: 'AOP 应用场景：事务、日志、性能监控、权限校验', link: '/framework/spring/aop/aop-usecase' },
          { text: 'Spring 事务管理：@Transactional 原理', link: '/framework/spring/aop/transaction' },
          { text: 'Spring 事务传播行为 7 种详解', link: '/framework/spring/aop/transaction-propagation' },
          { text: 'Spring 事务失效场景与解决方案', link: '/framework/spring/aop/transaction-fail' },
        ],
      },
      {
        text: 'Spring MVC',
        link: '/framework/spring/mvc/',
        collapsed: true,
        items: [
          { text: 'Spring MVC 请求处理流程', link: '/framework/spring/mvc/flow' },
          { text: 'DispatcherServlet 源码解析', link: '/framework/spring/mvc/dispatcher-servlet' },
          { text: 'HandlerMapping 与 HandlerAdapter', link: '/framework/spring/mvc/handler-mapping' },
          { text: 'HandlerInterceptor 与 Filter 对比', link: '/framework/spring/mvc/interceptor-filter' },
          { text: '参数绑定：@RequestParam、@RequestBody、@PathVariable', link: '/framework/spring/mvc/param-binding' },
          { text: '视图解析与视图技术（Thymeleaf、Freemarker、JSP）', link: '/framework/spring/mvc/view-resolver' },
          { text: '异常处理：@ExceptionHandler 与 @ControllerAdvice', link: '/framework/spring/mvc/exception-handler' },
          { text: '文件上传与下载实现', link: '/framework/spring/mvc/file-upload' },
          { text: 'RESTful API 设计规范', link: '/framework/spring/mvc/restful' },
        ],
      },
      {
        text: 'Spring 注解与配置',
        link: '/framework/spring/annotation/',
        collapsed: true,
        items: [
          { text: 'Spring 配置类 @Configuration 与 @Bean', link: '/framework/spring/annotation/configuration' },
          { text: '@ComponentScan 与组件扫描规则', link: '/framework/spring/annotation/component-scan' },
          { text: '@Conditional 条件装配与底层实现', link: '/framework/spring/annotation/conditional' },
          { text: '@Import 与 ImportSelector 接口', link: '/framework/spring/annotation/import' },
          { text: 'Spring 属性注入：@Value 与 @PropertySource', link: '/framework/spring/annotation/property-source' },
          { text: '@Profile 环境隔离与多环境配置', link: '/framework/spring/annotation/profile' },
          { text: 'Spring 5 新注解：@Indexed 加速组件扫描', link: '/framework/spring/annotation/indexed' },
        ],
      },
      {
        text: 'Spring 高级特性',
        link: '/framework/spring/advanced/',
        collapsed: true,
        items: [
          { text: 'Spring 事件机制：ApplicationEvent 与 @EventListener', link: '/framework/spring/advanced/event' },
          { text: 'Spring 资源加载：Resource 与 ResourceLoader', link: '/framework/spring/advanced/resource' },
          { text: 'Spring 国际化（i18n）实现', link: '/framework/spring/advanced/i18n' },
          { text: 'Spring 类型转换：PropertyEditor 与 Converter', link: '/framework/spring/advanced/type-converter' },
          { text: 'Spring 格式化：Formatter 与 FormattingConversionService', link: '/framework/spring/advanced/formatter' },
          { text: 'Spring 验证：JSR-303 与 Validator', link: '/framework/spring/advanced/validation' },
          { text: 'Spring 动态注册 Bean：BeanDefinitionRegistryPostProcessor', link: '/framework/spring/advanced/bean-registry' },
          { text: 'Spring 扩展点汇总与调用时机', link: '/framework/spring/advanced/extension-point' },
        ],
      },
    ],
  },
  {
    text: 'Spring Boot',
    link: '/framework/springboot/',
    items: [
      {
        text: 'Spring Boot 核心',
        link: '/framework/springboot/core/',
        collapsed: true,
        items: [
          { text: 'Spring Boot vs Spring：自动配置与起步依赖', link: '/framework/springboot/core/springboot-vs-spring' },
          { text: 'Spring Boot 启动流程源码解析', link: '/framework/springboot/core/startup-flow' },
          { text: '@SpringBootApplication 注解解析', link: '/framework/springboot/core/application-annotation' },
          { text: '自动配置原理：@EnableAutoConfiguration 与 META-INF/spring.factories', link: '/framework/springboot/core/autoconfig' },
          { text: 'spring.factories vs spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports', link: '/framework/springboot/core/auto-config-imports' },
          { text: 'ConditionOnClass、ConditionOnBean 等条件注解', link: '/framework/springboot/core/condition-annotation' },
          { text: 'Spring Boot 外部化配置：application.yml 与 @ConfigurationProperties', link: '/framework/springboot/core/external-config' },
          { text: 'Bootstrap.yml 与 application.yml 的加载顺序', link: '/framework/springboot/core/bootstrap' },
        ],
      },
      {
        text: 'Spring Boot Starter',
        link: '/framework/springboot/starter/',
        collapsed: true,
        items: [
          { text: '自定义 Starter 的开发流程', link: '/framework/springboot/starter/custom-starter' },
          { text: 'Starter 自动配置原理与条件装配', link: '/framework/springboot/starter/starter-autoconfig' },
          { text: 'Spring Boot Actuator 监控端点', link: '/framework/springboot/starter/actuator' },
          { text: 'Spring Boot Banner 定制', link: '/framework/springboot/starter/banner' },
        ],
      },
      {
        text: 'Spring Boot 常用功能',
        link: '/framework/springboot/feature/',
        collapsed: true,
        items: [
          { text: 'Spring Boot 日志配置：Logback、SLF4J', link: '/framework/springboot/feature/logging' },
          { text: 'Spring Boot 异常处理：ErrorController 与全局异常', link: '/framework/springboot/feature/error-handler' },
          { text: 'Spring Boot 静态资源配置', link: '/framework/springboot/feature/static-resource' },
          { text: 'CORS 跨域配置', link: '/framework/springboot/feature/cors' },
          { text: 'Spring Boot 拦截器与过滤器注册', link: '/framework/springboot/feature/interceptor-filter' },
          { text: 'Spring Boot 整合 WebSocket', link: '/framework/springboot/feature/websocket' },
          { text: 'Spring Boot 整合 GraphQL', link: '/framework/springboot/feature/graphql' },
        ],
      },
      { text: 'Spring Boot 面试高频问题汇总', link: '/framework/springboot/interview-summary' },
    ],
  },
  {
    text: 'MyBatis',
    link: '/framework/mybatis/',
    items: [
      {
        text: 'MyBatis 核心原理',
        link: '/framework/mybatis/core/',
        collapsed: true,
        items: [
          { text: 'MyBatis 整体架构：Executor、StatementHandler、ParameterHandler、ResultSetHandler', link: '/framework/mybatis/core/architecture' },
          { text: 'MyBatis 初始化流程：SqlSessionFactoryBuilder → XMLConfigBuilder', link: '/framework/mybatis/core/init-flow' },
          { text: 'SqlSessionFactory 创建流程与生命周期', link: '/framework/mybatis/core/sqlsessionfactory' },
          { text: 'SqlSession 获取 Mapper 代理对象', link: '/framework/mybatis/core/sqlsession-mapper' },
          { text: 'Mapper 代理对象生成：JDK 动态代理', link: '/framework/mybatis/core/mapper-proxy' },
        ],
      },
      {
        text: 'MyBatis SQL 执行流程',
        link: '/framework/mybatis/sql/',
        collapsed: true,
        items: [
          { text: 'Executor 执行器：SimpleExecutor、ReuseExecutor、BatchExecutor', link: '/framework/mybatis/sql/executor' },
          { text: 'StatementHandler 与 SQL 预编译', link: '/framework/mybatis/sql/statement-handler' },
          { text: 'ParameterHandler 参数绑定：#{} vs ${}', link: '/framework/mybatis/sql/parameter-handler' },
          { text: 'ResultSetHandler 结果集映射：自动映射 vs 自定义映射', link: '/framework/mybatis/sql/resultset-handler' },
          { text: 'TypeHandler 类型处理器与自定义 TypeHandler', link: '/framework/mybatis/sql/type-handler' },
          { text: 'MyBatis 一级缓存与二级缓存', link: '/framework/mybatis/sql/cache' },
          { text: 'MyBatis 二级缓存失效场景', link: '/framework/mybatis/sql/cache-invalid' },
        ],
      },
      {
        text: 'MyBatis XML 映射',
        link: '/framework/mybatis/xml/',
        collapsed: true,
        items: [
          { text: 'MyBatis XML mapper 文件结构', link: '/framework/mybatis/xml/xml-mapper' },
          { text: 'resultMap 配置详解：association 与 collection', link: '/framework/mybatis/xml/resultmap' },
          { text: '嵌套查询 vs 嵌套结果：N+1 问题与解决', link: '/framework/mybatis/xml/nested-query' },
          { text: '动态 SQL：if、where、set、trim、foreach、choose', link: '/framework/mybatis/xml/dynamic-sql' },
          { text: 'MyBatis 注解方式 vs XML 方式对比', link: '/framework/mybatis/xml/annotation-vs-xml' },
        ],
      },
      {
        text: 'MyBatis Plus 进阶',
        link: '/framework/mybatis-plus/',
        collapsed: true,
        items: [
          { text: 'MyBatis Plus 快速上手与核心注解', link: '/framework/mybatis-plus/quickstart' },
          { text: 'CRUD 接口与条件构造器 Wrapper', link: '/framework/mybatis-plus/wrapper' },
          { text: '分页插件配置与 Page 对象解析', link: '/framework/mybatis-plus/pagination' },
          { text: '自动填充：createTime、updateTime 自动填充', link: '/framework/mybatis-plus/auto-fill' },
          { text: '逻辑删除与全局配置', link: '/framework/mybatis-plus/logic-delete' },
          { text: '乐观锁插件与 @Version 注解', link: '/framework/mybatis-plus/optimistic-lock' },
          { text: '多租户插件实现', link: '/framework/mybatis-plus/tenant' },
          { text: 'MyBatis Plus SQL 性能分析', link: '/framework/mybatis-plus/sql-analyze' },
        ],
      },
      { text: 'MyBatis 面试高频问题汇总', link: '/framework/mybatis/interview-summary' },
    ],
  },
  {
    text: 'ORM 与数据库访问',
    link: '/framework/orm/',
    items: [
      { text: 'ORM 框架对比：JPA/Hibernate vs MyBatis', link: '/framework/orm/orm-compare' },
      { text: 'JDBC 执行流程与手写实现', link: '/framework/orm/jdbc' },
      { text: '数据库连接池：HikariCP、Druid、C3P0 对比', link: '/framework/orm/connection-pool' },
      { text: 'HikariCP 高性能原理：FastStatementList 与 ConcurrentBag', link: '/framework/orm/hikaricp' },
      { text: 'Spring JDBC Template 使用', link: '/framework/orm/jdbc-template' },
    ],
  },
  {
    text: 'Spring Cloud 全家桶',
    link: '/framework/springcloud/',
    items: [
      {
        text: 'Spring Cloud 基础',
        link: '/framework/springcloud/basic/',
        collapsed: true,
        items: [
          { text: 'Spring Cloud 版本命名与组件选型策略', link: '/framework/springcloud/basic/version' },
          { text: 'Spring Cloud 与 Spring Boot 版本对应关系', link: '/framework/springcloud/basic/boot-version' },
          { text: '微服务架构落地：Spring Cloud 全家桶组件总览', link: '/framework/springcloud/basic/overview' },
          { text: 'Spring Cloud Alibaba vs Spring Cloud Netflix 对比', link: '/framework/springcloud/basic/alibaba-vs-netflix' },
        ],
      },
      {
        text: '服务注册与配置',
        link: '/framework/springcloud/registry/',
        collapsed: true,
        items: [
          { text: 'Nacos 服务注册与发现', link: '/framework/springcloud/registry/nacos-discovery' },
          { text: 'Nacos 配置中心：命名空间、Group、Data ID 三层隔离', link: '/framework/springcloud/registry/nacos-config' },
          { text: 'Nacos 热更新：@RefreshScope 与配置动态刷新', link: '/framework/springcloud/registry/nacos-refresh' },
          { text: 'Nacos 集群与持久化', link: '/framework/springcloud/registry/nacos-cluster' },
        ],
      },
      {
        text: '服务调用与网关',
        link: '/framework/springcloud/gateway/',
        collapsed: true,
        items: [
          { text: 'OpenFeign 声明式 HTTP 客户端：@FeignClient 与负载均衡', link: '/framework/springcloud/gateway/openfeign' },
          { text: 'Feign 传参与继承特性', link: '/framework/springcloud/gateway/feign-advanced' },
          { text: 'Gateway 路由配置：Predicates 与 Filters', link: '/framework/springcloud/gateway/gateway-route' },
          { text: 'Gateway 过滤器：GlobalFilter 与 GatewayFilter 链', link: '/framework/springcloud/gateway/gateway-filter' },
          { text: 'Gateway 限流：RequestRateLimiter 与 Redis', link: '/framework/springcloud/gateway/gateway-rate-limit' },
          { text: 'Gateway 熔断降级：Spring Cloud CircuitBreaker 集成', link: '/framework/springcloud/gateway/gateway-circuit-breaker' },
        ],
      },
      {
        text: '服务容错与治理',
        link: '/framework/springcloud/resilience/',
        collapsed: true,
        items: [
          { text: 'Sentinel 流量控制与熔断降级', link: '/framework/springcloud/resilience/sentinel-flow' },
          { text: 'Sentinel @SentinelResource 与热点参数限流', link: '/framework/springcloud/resilience/sentinel-resource' },
          { text: 'Sentinel 规则持久化：推模式与拉模式', link: '/framework/springcloud/resilience/sentinel-persist' },
          { text: 'Sentinel 与 Hystrix 对比', link: '/framework/springcloud/resilience/sentinel-vs-hystrix' },
          { text: 'Sleuth 链路追踪与 Zipkin 可视化', link: '/framework/springcloud/resilience/sleuth-zipkin' },
        ],
      },
      {
        text: '消息与异步',
        link: '/framework/springcloud/message/',
        collapsed: true,
        items: [
          { text: 'Spring Cloud Stream 屏蔽 MQ 底层差异', link: '/framework/springcloud/message/stream' },
          { text: 'Spring Cloud Bus 消息总线与配置刷新', link: '/framework/springcloud/message/bus' },
          { text: 'Spring Cloud Bus + Nacos 实现配置自动刷新', link: '/framework/springcloud/message/bus-nacos' },
        ],
      },
      {
        text: '微服务实战',
        link: '/framework/springcloud/practice/',
        collapsed: true,
        items: [
          { text: 'Spring Cloud 分布式事务：Seata AT 模式集成', link: '/framework/springcloud/practice/seata' },
          { text: 'Spring Cloud 统一认证：Spring Security + OAuth2 + JWT', link: '/framework/springcloud/practice/oauth2-jwt' },
          { text: 'Spring Cloud 多环境配置：Bootstrap + Nacos Namespace', link: '/framework/springcloud/practice/multi-env' },
          { text: 'Spring Cloud 面试高频问题汇总', link: '/framework/springcloud/practice/interview-summary' },
        ],
      },
    ],
  },
  {
    text: 'Spring Security',
    link: '/framework/springsecurity/',
    items: [
      {
        text: 'Security 核心概念',
        link: '/framework/springsecurity/core/',
        collapsed: true,
        items: [
          { text: 'Spring Security 认证与授权核心流程', link: '/framework/springsecurity/core/flow' },
          { text: 'Spring Security 过滤器链：SecurityFilterChain 与 FilterChainProxy', link: '/framework/springsecurity/core/filter-chain' },
          { text: 'WebSecurityConfigurerAdapter 配置方式演进（JDK 5 → 6）', link: '/framework/springsecurity/core/config-adapter' },
          { text: 'UserDetailsService 与自定义登录认证', link: '/framework/springsecurity/core/userdetails' },
          { text: 'PasswordEncoder：BCrypt 密码加密与盐值', link: '/framework/springsecurity/core/password-encoder' },
        ],
      },
      {
        text: '认证机制',
        link: '/framework/springsecurity/auth/',
        collapsed: true,
        items: [
          { text: '表单登录：UsernamePasswordAuthenticationFilter 流程', link: '/framework/springsecurity/auth/form-login' },
          { text: 'Session 会话管理：超时处理与并发控制', link: '/framework/springsecurity/auth/session' },
          { text: 'Remember-Me 功能：Token 持久化与安全', link: '/framework/springsecurity/auth/remember-me' },
          { text: '短信验证码登录：AuthenticationProvider 自定义扩展', link: '/framework/springsecurity/auth/sms-login' },
          { text: 'OAuth2 登录：QQ、微信、GitHub 第三方登录集成', link: '/framework/springsecurity/auth/oauth2-login' },
          { text: 'CAS 单点登录集成', link: '/framework/springsecurity/auth/cas' },
        ],
      },
      {
        text: '授权与权限',
        link: '/framework/springsecurity/permission/',
        collapsed: true,
        items: [
          { text: 'Spring Security 授权模型：Authority 与 Role', link: '/framework/springsecurity/permission/authority-role' },
          { text: '@PreAuthorize 与 @Secured 注解权限控制', link: '/framework/springsecurity/permission/preauthorize' },
          { text: '方法级别安全：@EnableMethodSecurity 与 SpEL 表达式', link: '/framework/springsecurity/permission/method-security' },
          { text: '动态权限决策：投票器（Voter）与 AccessDecisionManager', link: '/framework/springsecurity/permission/access-decision' },
          { text: 'RBAC 权限模型与数据表设计', link: '/framework/springsecurity/permission/rbac' },
          { text: '接口权限数据模型：用户-角色-权限树状结构', link: '/framework/springsecurity/permission/permission-model' },
        ],
      },
      {
        text: 'JWT 与无状态认证',
        link: '/framework/springsecurity/jwt/',
        collapsed: true,
        items: [
          { text: 'JWT 生成与验证：jjwt 库使用', link: '/framework/springsecurity/jwt/jwt' },
          { text: 'JWT 无状态认证流程设计：过滤器链集成', link: '/framework/springsecurity/jwt/jwt-filter' },
          { text: 'JWT 刷新机制与黑名单注销', link: '/framework/springsecurity/jwt/jwt-refresh' },
          { text: 'Token 防盗用：设备指纹 + IP 绑定', link: '/framework/springsecurity/jwt/jwt-security' },
        ],
      },
      {
        text: 'Security 高级特性',
        link: '/framework/springsecurity/advanced/',
        collapsed: true,
        items: [
          { text: 'CSRF 防护机制与 Token 校验', link: '/framework/springsecurity/advanced/csrf' },
          { text: 'CORS 跨域与 Security 配置', link: '/framework/springsecurity/advanced/cors' },
          { text: 'XSS 防护：Filter 与 HttpFirewall', link: '/framework/springsecurity/advanced/xss' },
          { text: 'Security 与微服务：Gateway 统一鉴权中心', link: '/framework/springsecurity/advanced/gateway-auth' },
          { text: 'Spring Security 6.x 新特性与重大变更', link: '/framework/springsecurity/advanced/v6' },
          { text: 'Spring Security 面试高频问题汇总', link: '/framework/springsecurity/advanced/interview-summary' },
        ],
      },
    ],
  },
  {
    text: 'Shiro',
    link: '/framework/shiro/',
    items: [
      {
        text: 'Shiro 核心概念',
        link: '/framework/shiro/core/',
        collapsed: true,
        items: [
          { text: 'Shiro 架构：Subject、SecurityManager、Realms 三大组件', link: '/framework/shiro/core/architecture' },
          { text: 'Shiro 与 Spring Security 对比', link: '/framework/shiro/core/vs-spring-security' },
          { text: 'Shiro 认证流程：login() → SecurityUtils.getSubject()', link: '/framework/shiro/core/authentication' },
          { text: 'Shiro 授权流程：isPermitted() 与 Permissions', link: '/framework/shiro/core/authorization' },
        ],
      },
      {
        text: 'Shiro 认证机制',
        link: '/framework/shiro/auth/',
        collapsed: true,
        items: [
          { text: 'IniRealm 与 properties 方式配置用户权限', link: '/framework/shiro/auth/ini-realm' },
          { text: 'JDBCRealm 连接数据库实现认证授权', link: '/framework/shiro/auth/jdbc-realm' },
          { text: '自定义 Realm：继承 AuthorizingRealm 实现doGetAuthenticationInfo', link: '/framework/shiro/auth/custom-realm' },
          { text: 'Shiro 密码加密：HashedCredentialsMatcher 与盐值', link: '/framework/shiro/auth/credentials-matcher' },
          { text: 'Shiro Session 管理：SessionManager 与 SessionDAO', link: '/framework/shiro/auth/session' },
          { text: 'Shiro RememberMe 功能', link: '/framework/shiro/auth/remember-me' },
        ],
      },
      {
        text: 'Shiro 与 Spring Boot 集成',
        link: '/framework/shiro/springboot/',
        collapsed: true,
        items: [
          { text: 'Shiro + Spring Boot 快速集成：ShiroFilterFactoryBean', link: '/framework/shiro/springboot/springboot' },
          { text: 'Shiro 过滤器链：anon、authc、roles、perms、logout', link: '/framework/shiro/springboot/filter-chain' },
          { text: ' Shiro 注解：@RequiresAuthentication / @RequiresRoles / @RequiresPermissions', link: '/framework/shiro/springboot/annotation' },
          { text: 'Shiro JSP 标签库：\<shiro:principal\> 与 \<shiro:hasRole\>', link: '/framework/shiro/springboot/jsp-tag' },
          { text: 'Shiro 缓存：EhCache / Redis + CacheManager', link: '/framework/shiro/springboot/cache' },
          { text: 'Shiro  session + Redis 分布式会话共享', link: '/framework/shiro/springboot/session-redis' },
        ],
      },
      {
        text: 'Shiro 实战与安全',
        link: '/framework/shiro/practice/',
        collapsed: true,
        items: [
          { text: 'Shiro 实现 JWT 无状态认证', link: '/framework/shiro/practice/jwt' },
          { text: 'Shiro 权限数据模型：用户-角色-权限树状结构设计', link: '/framework/shiro/practice/permission-model' },
          { text: 'Shiro CSRF 防护与 URL 过滤策略', link: '/framework/shiro/practice/csrf' },
          { text: 'Shiro 面试高频问题汇总', link: '/framework/shiro/practice/interview-summary' },
        ],
      },
    ],
  },
]
