export const interviewSidebar = [
  {
    text: '简历优化',
    link: '/interview/resume/',
    items: [
      { text: '一份优秀简历的标准', link: '/interview/resume/standard' },
      { text: '简历各模块写法', link: '/interview/resume/write' },
      { text: 'STAR 法则', link: '/interview/resume/star' },
      { text: '项目经历包装', link: '/interview/resume/project' },
      { text: '简历常见问题与修改建议', link: '/interview/resume/problem' },
      { text: '技术简历模板参考', link: '/interview/resume/template' },
    ],
  },
  {
    text: '算法训练',
    link: '/interview/algorithm/',
    collapsed: true,
    items: [
      { text: '数组与链表高频题', link: '/interview/algorithm/array-linkedlist' },
      { text: '回溯高频题', link: '/interview/algorithm/backtracking' },
      { text: '二分查找高频题', link: '/interview/algorithm/binary-search' },
      { text: '二叉树高频题', link: '/interview/algorithm/binary-tree' },
      { text: '位运算技巧与实战', link: '/interview/algorithm/bit' },
      { text: '动态规划高频题', link: '/interview/algorithm/dp' },
      { text: '哈希表高频题', link: '/interview/algorithm/hash' },
      { text: 'LeetCode 高效刷题方法', link: '/interview/algorithm/method' },
      { text: '单调栈', link: '/interview/algorithm/monotonic-stack' },
      { text: '前缀和与差分数组', link: '/interview/algorithm/prefix-sum' },
      { text: '线段树与树状数组', link: '/interview/algorithm/segment-tree' },
      { text: '排序算法高频题', link: '/interview/algorithm/sort' },
      { text: '栈与队列高频题', link: '/interview/algorithm/stack-queue' },
      { text: '面试算法题类型总结', link: '/interview/algorithm/summary' },
      { text: '字典树（Trie）', link: '/interview/algorithm/trie' },
      { text: '并查集', link: '/interview/algorithm/union-find' },
    ],
  },
  {
    text: '系统设计',
    link: '/interview/system-design/',
    collapsed: true,
    items: [
      { text: '设计搜索自动补全', link: '/interview/system-design/autocomplete' },
      { text: '如何保证系统的高可用', link: '/interview/system-design/availability' },
      { text: '缓存策略在系统设计中的应用', link: '/interview/system-design/cache' },
      { text: 'CAP 理论与系统设计', link: '/interview/system-design/cap' },
      { text: '如何进行容量规划与性能评估', link: '/interview/system-design/capacity' },
      { text: '设计配置中心', link: '/interview/system-design/config-center' },
      { text: '如何保证系统的一致性', link: '/interview/system-design/consistency' },
      { text: '一致性哈希与数据分片', link: '/interview/system-design/consistent-hash' },
      { text: '设计延迟消息队列', link: '/interview/system-design/delay-queue' },
      { text: '设计分布式锁服务', link: '/interview/system-design/distributed-lock' },
      { text: '设计 Feed 流', link: '/interview/system-design/feed' },
      { text: '设计关注/粉丝系统', link: '/interview/system-design/follow' },
      { text: '设计分布式 ID 生成器', link: '/interview/system-design/id-generator' },
      { text: '系统设计面试方法论', link: '/interview/system-design/method' },
      { text: '微服务拆分原则与实践', link: '/interview/system-design/microservices' },
      { text: '消息队列在系统设计中的应用', link: '/interview/system-design/mq' },
      { text: '设计一次性密码（OTP）系统', link: '/interview/system-design/otp' },
      { text: '设计排行榜/热搜系统', link: '/interview/system-design/ranking' },
      { text: '设计 Redis 缓存穿透/击穿/雪崩', link: '/interview/system-design/redis-cache' },
      { text: '设计红包雨/抽奖系统', link: '/interview/system-design/redpacket' },
      { text: '如何设计一个可扩展的架构', link: '/interview/system-design/scalability' },
      { text: '设计秒杀系统', link: '/interview/system-design/seckill' },
      { text: '数据库读写分离与分库分表设计', link: '/interview/system-design/sharding' },
      { text: '设计抢票系统（12306）', link: '/interview/system-design/ticket' },
      { text: '设计 Twitter/微博时间线推送系统', link: '/interview/system-design/timeline' },
      { text: '设计短链接系统', link: '/interview/system-design/url-shortener' },
    ],
  },
  {
    text: 'HR 面与谈薪',
    link: '/interview/hr/',
    collapsed: true,
    items: [
      { text: '自我介绍', link: '/interview/hr/self-intro' },
      { text: 'HR 常问问题汇总与应对话术', link: '/interview/hr/common-question' },
      { text: '离职原因', link: '/interview/hr/leave-reason' },
      { text: '职业规划', link: '/interview/hr/career' },
      { text: '期望薪资', link: '/interview/hr/salary' },
      { text: '福利待遇', link: '/interview/hr/benefits' },
      { text: '反向提问', link: '/interview/hr/ask-interviewer' },
      { text: '背调注意事项', link: '/interview/hr/background-check' },
    ],
  },
  {
    text: '面试经验与复盘',
    link: '/interview/review/',
    collapsed: true,
    items: [
      { text: '如何高效准备技术面试', link: '/interview/review/prepare' },
      { text: '面试高频问题分类与回答框架', link: '/interview/review/question' },
      { text: '面试中的沟通技巧', link: '/interview/review/communication' },
      { text: '如何应对压力面与追问', link: '/interview/review/stress' },
      { text: '面试复盘模板', link: '/interview/review/template' },
      { text: '面试凉了怎么办', link: '/interview/review/after-fail' },
    ],
  },
]
