export const javaSidebar = [
  {
    text: 'Java 基础',
    link: '/java/basic/',
    items: [
      {
        text: '基础语法',
        link: '/java/basic/syntax/',
        collapsed: true,
        items: [
          { text: '数据类型与类型转换', link: '/java/basic/syntax/data-types' },
          { text: '面向对象：封装、继承、多态', link: '/java/basic/syntax/oop' },
          { text: '抽象类 vs 接口', link: '/java/basic/syntax/abstract-interface' },
          { text: '内部类与 lambda 表达式', link: '/java/basic/syntax/inner-class-lambda' },
        ],
      },
      {
        text: 'String 与字符串',
        link: '/java/basic/string/',
        collapsed: true,
        items: [
          { text: 'String 不可变性与实现原理', link: '/java/basic/string/immutable' },
          { text: '字符串常量池与 intern()', link: '/java/basic/string/pool' },
          { text: 'StringBuilder vs StringBuffer', link: '/java/basic/string/build-buffer' },
          { text: 'JDK 8 vs JDK 9+ String 实现差异', link: '/java/basic/string/jdk9' },
        ],
      },
      {
        text: '基本类型与包装类',
        link: '/java/basic/wrapper/',
        collapsed: true,
        items: [
          { text: '自动装箱与拆箱原理', link: '/java/basic/wrapper/box-unbox' },
          { text: 'Integer 缓存池与 IntegerCache', link: '/java/basic/wrapper/integer-cache' },
          { text: 'Integer.valueOf vs new', link: '/java/basic/wrapper/integer-compare' },
          { text: '浮点数精度问题与 BigDecimal', link: '/java/basic/wrapper/float-decimal' },
        ],
      },
      {
        text: '异常体系',
        link: '/java/basic/exception/',
        collapsed: true,
        items: [
          { text: 'Throwable、Error、Exception 体系', link: '/java/basic/exception/hierarchy' },
          { text: '受检异常 vs 非受检异常', link: '/java/basic/exception/checked-unchecked' },
          { text: 'try-with-resources 用法与原理', link: '/java/basic/exception/try-with-resources' },
          { text: '自定义异常的最佳实践', link: '/java/basic/exception/custom-exception' },
        ],
      },
      {
        text: '枚举与注解',
        link: '/java/basic/enum-annotation/',
        collapsed: true,
        items: [
          { text: '枚举的用法与实现原理', link: '/java/basic/enum-annotation/enum' },
          { text: '注解的分类与保留策略', link: '/java/basic/enum-annotation/annotation-type' },
          { text: '注解处理器与 Lombok 原理', link: '/java/basic/enum-annotation/annotation-processor' },
        ],
      },
      { text: '泛型', link: '/java/basic/generics' },
      { text: '序列化', link: '/java/basic/serialization' },
      { text: 'Java 新特性演进（JDK 8~21）', link: '/java/basic/new-features' },
    ],
  },
  {
    text: '集合框架',
    link: '/java/collection/',
    items: [
      {
        text: 'Collection 体系',
        link: '/java/collection/collection/',
        collapsed: true,
        items: [
          { text: 'Collection 接口结构与分类', link: '/java/collection/collection/hierarchy' },
          { text: 'List 实现对比', link: '/java/collection/collection/list' },
          { text: 'ArrayList 扩容机制与位运算', link: '/java/collection/collection/arraylist-resize' },
          { text: 'ArrayList vs LinkedList 深度对比', link: '/java/collection/collection/arraylist-vs-linkedlist' },
        ],
      },
      {
        text: 'Set 与散列表',
        link: '/java/collection/set/',
        collapsed: true,
        items: [
          { text: 'HashSet 实现原理', link: '/java/collection/set/hashset' },
          { text: 'HashMap 底层结构与寻址算法', link: '/java/collection/set/hashmap' },
          { text: 'HashMap 的扰动函数与哈希冲突', link: '/java/collection/set/hashmap-hash' },
          { text: '负载因子 0.75 的深层原因', link: '/java/collection/set/loadfactor' },
          { text: 'HashSet 如何判断元素重复', link: '/java/collection/set/hashset-duplicate' },
          { text: 'LinkedHashSet 与访问顺序 LRU', link: '/java/collection/set/linkedhashset' },
          { text: 'TreeSet 与红黑树', link: '/java/collection/set/treeset' },
        ],
      },
      {
        text: 'HashMap 专题',
        link: '/java/collection/hashmap/',
        collapsed: true,
        items: [
          { text: 'JDK 7：数组 + 链表 + 头插法', link: '/java/collection/hashmap/jdk7' },
          { text: 'JDK 8+ 红黑树', link: '/java/collection/hashmap/jdk8' },
          { text: 'HashMap.put() 全流程源码解析', link: '/java/collection/hashmap/put' },
          { text: 'HashMap 扩容时机与resize过程', link: '/java/collection/hashmap/resize' },
          { text: '红黑树化条件', link: '/java/collection/hashmap/treeify' },
          { text: 'JDK 7 扩容死循环问题', link: '/java/collection/hashmap/resize-loop' },
        ],
      },
      {
        text: 'Map 接口其他实现',
        link: '/java/collection/map/',
        collapsed: true,
        items: [
          { text: 'LinkedHashMap 与 LRU 缓存实现', link: '/java/collection/map/linkedhashmap' },
          { text: 'TreeMap 排序', link: '/java/collection/map/treemap' },
          { text: 'Hashtable：为什么不再推荐', link: '/java/collection/map/hashtable' },
          { text: 'WeakHashMap 与弱引用', link: '/java/collection/map/weakhashmap' },
        ],
      },
      {
        text: '并发容器',
        link: '/java/collection/concurrent/',
        collapsed: true,
        items: [
          { text: 'CHM JDK 7 分段锁', link: '/java/collection/concurrent/hashmap-jdk7' },
          { text: 'CHM JDK 8+ CAS', link: '/java/collection/concurrent/hashmap-jdk8' },
          { text: 'ConcurrentHashMap size() 方法演进', link: '/java/collection/concurrent/size' },
          { text: 'CopyOnWriteArrayList 原理与适用场景', link: '/java/collection/concurrent/copyonwritearraylist' },
          { text: 'ConcurrentLinkedQueue 无锁实现原理', link: '/java/collection/concurrent/concurrent-linked-queue' },
          { text: '生产者-消费者模式', link: '/java/collection/concurrent/blocking-queue' },
          { text: '各并发容器对比与选型', link: '/java/collection/concurrent/compare' },
        ],
      },
      {
        text: 'Queue 与 Deque',
        link: '/java/collection/queue/',
        collapsed: true,
        items: [
          { text: 'Queue 接口与实现类', link: '/java/collection/queue/queue' },
          { text: 'PriorityQueue 堆结构与排序', link: '/java/collection/queue/priority-queue' },
          { text: 'ArrayDeque 原理', link: '/java/collection/queue/array-deque' },
        ],
      },
      { text: 'Collections 工具类常用方法', link: '/java/collection/collections-tool' },
    ],
  },
  {
    text: 'Java 并发编程',
    link: '/java/concurrent/',
    items: [
      {
        text: '线程与进程',
        link: '/java/concurrent/thread/',
        collapsed: true,
        items: [
          { text: '进程与线程的区别与关系', link: '/java/concurrent/thread/process-thread' },
          { text: '创建线程的 3 种方式', link: '/java/concurrent/thread/create-thread' },
          { text: 'Thread 生命周期与状态转换', link: '/java/concurrent/thread/thread-state' },
          { text: 'start() vs run()', link: '/java/concurrent/thread/start-vs-run' },
          { text: 'sleep() vs wait() vs yield()', link: '/java/concurrent/thread/sleep-wait-yield' },
          { text: 'join() 与线程等待', link: '/java/concurrent/thread/join' },
          { text: '守护线程与用户线程', link: '/java/concurrent/thread/daemon-thread' },
        ],
      },
      {
        text: 'synchronized 关键字',
        link: '/java/concurrent/synchronized/',
        collapsed: true,
        items: [
          { text: 'synchronized 锁对象', link: '/java/concurrent/synchronized/object' },
          { text: 'synchronized 修饰方法 vs 代码块', link: '/java/concurrent/synchronized/method-block' },
          { text: '锁升级机制', link: '/java/concurrent/synchronized/lock-escalation' },
          { text: '偏向锁的获取、撤销与批量重偏向', link: '/java/concurrent/synchronized/biased-lock' },
          { text: '轻量级锁：CAS + 自旋', link: '/java/concurrent/synchronized/lightweight-lock' },
          { text: '重量级锁：Monitor 机制与等待队列', link: '/java/concurrent/synchronized/heavyweight-lock' },
          { text: '锁消除与锁粗化优化', link: '/java/concurrent/synchronized/lock-coarsening' },
        ],
      },
      {
        text: 'JUC 并发工具',
        link: '/java/concurrent/juc/',
        collapsed: true,
        items: [
          { text: 'ReentrantLock 原理', link: '/java/concurrent/juc/reentrant-lock' },
          { text: 'ReentrantLock vs synchronized 对比', link: '/java/concurrent/juc/lock-vs-synchronized' },
          { text: 'ReadWriteLock：读写锁原理', link: '/java/concurrent/juc/read-write-lock' },
          { text: 'StampedLock：乐观读 vs 悲观读', link: '/java/concurrent/juc/stamped-lock' },
          { text: 'Semaphore：信号量控制并发数', link: '/java/concurrent/juc/semaphore' },
          { text: 'CountDownLatch：线程倒计时协调', link: '/java/concurrent/juc/countdown-latch' },
          { text: 'CyclicBarrier：循环栅栏', link: '/java/concurrent/juc/cyclic-barrier' },
          { text: 'Condition：精准等待与唤醒', link: '/java/concurrent/juc/condition' },
        ],
      },
      {
        text: '线程池',
        link: '/java/concurrent/threadpool/',
        collapsed: true,
        items: [
          { text: '为什么要用线程池？', link: '/java/concurrent/threadpool/why' },
          { text: 'ThreadPoolExecutor 七大参数详解', link: '/java/concurrent/threadpool/params' },
          { text: '线程池拒绝策略对比', link: '/java/concurrent/threadpool/reject-policy' },
          { text: '常用线程池', link: '/java/concurrent/threadpool/types' },
          { text: '线程池参数配置与调优', link: '/java/concurrent/threadpool/tuning' },
          { text: '线程池执行流程与状态转换', link: '/java/concurrent/threadpool/execute' },
          { text: '定时任务原理', link: '/java/concurrent/threadpool/scheduled-threadpool' },
          { text: 'Fork/Join 框架与工作窃取算法', link: '/java/concurrent/threadpool/fork-join' },
        ],
      },
      {
        text: 'JMM 与 volatile',
        link: '/java/concurrent/jmm/',
        collapsed: true,
        items: [
          { text: 'Java 内存模型：主内存与工作内存', link: '/java/concurrent/jmm/jmm' },
          { text: 'JMM 八大 Happens-Before 规则', link: '/java/concurrent/jmm/happens-before' },
          { text: 'volatile 可见性原理：内存屏障', link: '/java/concurrent/jmm/volatile-visible' },
          { text: 'volatile 有序性', link: '/java/concurrent/jmm/volatile-order' },
          { text: 'volatile 能保证原子性吗？', link: '/java/concurrent/jmm/volatile-atomic' },
          { text: 'DCL 单例模式与 volatile', link: '/java/concurrent/jmm/dcl-singleton' },
        ],
      },
      {
        text: 'CAS 与原子类',
        link: '/java/concurrent/cas/',
        collapsed: true,
        items: [
          { text: 'CAS 原理与问题', link: '/java/concurrent/cas/cas' },
          { text: 'AtomicInteger/AtomicLong 源码解析', link: '/java/concurrent/cas/atomic-integer' },
          { text: 'AtomicReference 与 ABA 问题', link: '/java/concurrent/cas/atomic-reference' },
          { text: 'AtomicStampedReference：解决 ABA 问题', link: '/java/concurrent/cas/atomic-stamped' },
          { text: 'LongAdder 性能', link: '/java/concurrent/cas/long-adder' },
        ],
      },
      {
        text: '并发安全与死锁',
        link: '/java/concurrent/safety/',
        collapsed: true,
        items: [
          { text: '线程安全特性', link: '/java/concurrent/safety/thread-safety' },
          { text: '死锁产生的 4 个必要条件', link: '/java/concurrent/safety/deadlock-condition' },
          { text: '死锁定位与排查方法', link: '/java/concurrent/safety/deadlock-debug' },
          { text: '如何避免死锁：破坏四大条件', link: '/java/concurrent/safety/deadlock-prevent' },
          { text: '活锁与饥饿', link: '/java/concurrent/safety/livelock-starvation' },
          { text: '生产者-消费者问题', link: '/java/concurrent/safety/producer-consumer' },
          { text: '哲学家就餐问题', link: '/java/concurrent/safety/dining-philosophers' },
        ],
      },
      {
        text: 'AQS 原理',
        link: '/java/concurrent/aqs/',
        collapsed: true,
        items: [
          { text: 'AQS 核心思想', link: '/java/concurrent/aqs/aqs' },
          { text: 'AQS 两种模式：独占锁与共享锁', link: '/java/concurrent/aqs/mode' },
          { text: 'AQS 实现 ReentrantLock 源码解析', link: '/java/concurrent/aqs/reentrantlock' },
          { text: 'AQS CountDownLatch', link: '/java/concurrent/aqs/countdownlatch' },
        ],
      },
      {
        text: 'Future 与异步编程',
        link: '/java/concurrent/future/',
        collapsed: true,
        items: [
          {
            text: 'Future 基础',
            link: '/java/concurrent/future/future/',
            collapsed: true,
            items: [
              { text: 'Callable、Future、FutureTask 三者关系', link: '/java/concurrent/future/future/callable-future' },
              { text: 'Future 局限性', link: '/java/concurrent/future/future/limitation' },
              { text: 'Future 接口方法', link: '/java/concurrent/future/future/method' },
            ],
          },
          {
            text: 'CompletableFuture 核心',
            link: '/java/concurrent/future/completablefuture/',
            collapsed: true,
            items: [
              { text: 'CompletableFuture 优势', link: '/java/concurrent/future/completablefuture/completable-future' },
              { text: 'CF 创建方式', link: '/java/concurrent/future/completablefuture/cf-create' },
              { text: 'CF 默认线程池', link: '/java/concurrent/future/completablefuture/cf-default-executor' },
              { text: 'CompletableFuture 常用方法速查表', link: '/java/concurrent/future/completablefuture/cf-method-cheatsheet' },
            ],
          },
          {
            text: 'CompletableFuture 依赖链',
            link: '/java/concurrent/future/chain/',
            collapsed: true,
            items: [
              { text: 'thenApply 同步异步', link: '/java/concurrent/future/chain/then-apply' },
              { text: 'thenAccept thenRun', link: '/java/concurrent/future/chain/then-accept' },
              { text: 'thenCompose 扁平化', link: '/java/concurrent/future/chain/then-compose' },
              { text: 'thenCombine 合并', link: '/java/concurrent/future/chain/then-combine' },
              { text: 'allOf / anyOf：批量等待与最先完成', link: '/java/concurrent/future/chain/allof-anyof' },
            ],
          },
          {
            text: 'CompletableFuture 异常处理',
            link: '/java/concurrent/future/exception/',
            collapsed: true,
            items: [
              { text: 'exceptionally：异常时返回默认值', link: '/java/concurrent/future/exception/exceptionally' },
              { text: 'whenComplete：无论成功失败都执行回调', link: '/java/concurrent/future/exception/when-complete' },
              { text: 'handle：携带异常信息的统一处理', link: '/java/concurrent/future/exception/handle' },
              { text: '异常处理', link: '/java/concurrent/future/exception/exception' },
            ],
          },
          {
            text: 'CompletableFuture 实战',
            link: '/java/concurrent/future/practice/',
            collapsed: true,
            items: [
              { text: '多服务并行调用', link: '/java/concurrent/future/practice/parallel-call' },
              { text: 'allOf 聚合多路查询结果并处理异常', link: '/java/concurrent/future/practice/allof-practice' },
              { text: 'anyOf 实现超时降级与快速失败', link: '/java/concurrent/future/practice/timeout-fallback' },
              { text: 'CF vs ParallelStream', link: '/java/concurrent/future/practice/cf-vs-parallel-stream' },
              { text: 'CF 性能调优', link: '/java/concurrent/future/practice/performance' },
            ],
          },
          { text: '并行流 ParallelStream 原理', link: '/java/concurrent/future/parallel-stream' },
          { text: '异步编程模式总结', link: '/java/concurrent/future/async-pattern' },
        ],
      },
      { text: 'ThreadLocal 原理与内存泄漏', link: '/java/concurrent/threadlocal' },
      { text: 'Java 并发面试高频问题汇总', link: '/java/concurrent/interview-summary' },
    ],
  },
  {
    text: 'JVM',
    link: '/java/jvm/',
    items: [
      {
        text: 'JVM 体系结构',
        link: '/java/jvm/architecture/',
        collapsed: true,
        items: [
          { text: 'JVM 整体架构图解', link: '/java/jvm/architecture/architecture' },
          { text: '类加载子系统与类加载器分类', link: '/java/jvm/architecture/classloader' },
          { text: '双亲委派模型与打破方式', link: '/java/jvm/architecture/parent-delegation' },
          { text: 'ClassLoader 源码', link: '/java/jvm/architecture/classloader-source' },
          { text: '类的主动加载与被动加载', link: '/java/jvm/architecture/class-loading' },
        ],
      },
      {
        text: '运行时数据区',
        link: '/java/jvm/runtime/',
        collapsed: true,
        items: [
          { text: '运行时数据区总览与各区域作用', link: '/java/jvm/runtime/area' },
          { text: '程序计数器：线程私有与分支跳转', link: '/java/jvm/runtime/program-counter' },
          { text: '虚拟机栈：栈帧结构与操作数栈', link: '/java/jvm/runtime/vm-stack' },
          { text: '本地方法栈', link: '/java/jvm/runtime/native-method-stack' },
          { text: '堆内存：年轻代、老年代、TLAB', link: '/java/jvm/runtime/heap' },
          { text: '方法区变迁', link: '/java/jvm/runtime/method-area' },
          { text: '运行时常量池与字符串常量池', link: '/java/jvm/runtime/constant-pool' },
          { text: '直接内存（堆外内存）与 NIO', link: '/java/jvm/runtime/direct-memory' },
        ],
      },
      {
        text: '垃圾回收',
        link: '/java/jvm/gc/',
        collapsed: true,
        items: [
          { text: 'GC 判断存活', link: '/java/jvm/gc/algorithm' },
          { text: '四种引用类型', link: '/java/jvm/gc/reference' },
          { text: '分代收集理论', link: '/java/jvm/gc/generation' },
          { text: 'GC 分代类型', link: '/java/jvm/gc/gc-types' },
          { text: 'GC 算法', link: '/java/jvm/gc/algorithm-type' },
          { text: '垃圾收集器分类与组合关系图', link: '/java/jvm/gc/collector' },
          { text: 'Serial / Serial Old：单线程收集器', link: '/java/jvm/gc/serial-gc' },
          { text: 'ParNew：多线程年轻代收集器', link: '/java/jvm/gc/parnew-gc' },
          { text: 'Parallel GC', link: '/java/jvm/gc/parallel-gc' },
          { text: 'CMS：并发标记-清除收集器', link: '/java/jvm/gc/cms-gc' },
          { text: 'G1：Region 化分代收集器', link: '/java/jvm/gc/g1-gc' },
          { text: 'ZGC / Shenandoah：低延迟收集器', link: '/java/jvm/gc/low-latency-gc' },
          { text: 'GC 日志分析实战', link: '/java/jvm/gc/gc-log' },
          { text: 'Full GC 问题排查与调优', link: '/java/jvm/gc/full-gc-tuning' },
        ],
      },
      {
        text: '性能监控与调优',
        link: '/java/jvm/tuning/',
        collapsed: true,
        items: [
          { text: 'OutOfMemoryError 各类型与原因分析', link: '/java/jvm/tuning/oom' },
          { text: '堆内存溢出（Heap Space OOM）排查', link: '/java/jvm/tuning/heap-oom' },
          { text: '栈溢出排查', link: '/java/jvm/tuning/stackoverflow' },
          { text: 'Metaspace 溢出排查', link: '/java/jvm/tuning/metaspace-oom' },
          { text: 'jstat、jmap、jstack、jhat 工具使用', link: '/java/jvm/tuning/jvm-tools' },
          { text: 'MAT 内存分析工具实战', link: '/java/jvm/tuning/mat' },
          { text: 'Arthas 诊断工具使用', link: '/java/jvm/tuning/arthas' },
          { text: 'JVM 参数配置与调优经验', link: '/java/jvm/tuning/jvm-tuning' },
          { text: 'CPU 高占用分析', link: '/java/jvm/tuning/cpu-high' },
        ],
      },
      {
        text: '字节码与编译优化',
        link: '/java/jvm/bytecode/',
        collapsed: true,
        items: [
          { text: '字节码入门：常用字节码指令', link: '/java/jvm/bytecode/bytecode' },
          { text: '反编译工具', link: '/java/jvm/bytecode/decompile' },
          { text: '虚拟机编译优化：JIT 即时编译', link: '/java/jvm/bytecode/jit' },
          { text: '逃逸分析：标量替换与栈上分配', link: '/java/jvm/bytecode/escape-analysis' },
          { text: '方法内联与热点代码探测', link: '/java/jvm/bytecode/inlining' },
        ],
      },
    ],
  },
  {
    text: 'Java I/O 与网络',
    link: '/java/io/',
    items: [
      { text: 'IO 模型对比', link: '/java/io/io-model' },
      { text: 'BIO、NIO、AIO 编程模型对比', link: '/java/io/bio-nio-aio' },
      { text: 'NIO 核心组件', link: '/java/io/nio-core' },
      { text: 'ByteBuffer 分类与使用陷阱', link: '/java/io/bytebuffer' },
      { text: '直接内存（Direct Buffer）优势与限制', link: '/java/io/direct-buffer' },
      { text: 'Netty 核心组件与线程模型', link: '/java/io/netty' },
      { text: 'Tomcat 线程模型与 NIO 处理', link: '/java/io/tomcat' },
      { text: 'Socket 通信与三次握手', link: '/java/io/socket' },
    ],
  },
  {
    text: 'Java 17+ 新特性',
    link: '/java/new-features/',
    items: [
      { text: 'JDK 9~11 新特性', link: '/java/new-features/jdk9-11' },
      { text: 'JDK 12~16 新特性', link: '/java/new-features/jdk12-16' },
      { text: 'JDK 17~21 新特性', link: '/java/new-features/jdk17-21' },
      { text: '虚拟线程原理', link: '/java/new-features/virtual-thread' },
      { text: 'Record 类型与模式匹配', link: '/java/new-features/record-pattern' },
      { text: 'Switch 表达式增强', link: '/java/new-features/switch' },
      { text: 'Sealed Class 密封类', link: '/java/new-features/sealed-class' },
    ],
  },
]
