export const middlewareSidebar = [
  {
    text: '消息队列',
    link: '/middleware/mq/',
    items: [
      {
        text: '消息队列基础',
        link: '/middleware/mq/common/',
        collapsed: true,
        items: [
          { text: '消息队列核心概念：消息、Producer、Consumer、Broker、Topic、Partition、Group', link: '/middleware/mq/common/core-concept' },
          { text: '消息队列应用场景：异步解耦、削峰填谷、数据收集', link: '/middleware/mq/common/use-case' },
          { text: '消息队列架构设计要点', link: '/middleware/mq/common/architecture-design' },
          { text: 'Kafka vs RabbitMQ vs RocketMQ 选型指南', link: '/middleware/mq/common/select' },
          { text: '如何保证消息的顺序性？', link: '/middleware/mq/common/ordering' },
          { text: '如何保证消息的幂等性消费？', link: '/middleware/mq/common/idempotent-consume' },
          { text: '消息积压处理方案', link: '/middleware/mq/common/message-backlog' },
          { text: '消息重试机制与死信队列', link: '/middleware/mq/common/retry-dlq' },
          { text: '消息队列面试高频问题汇总', link: '/middleware/mq/common/interview-summary' },
        ],
      },
      {
        text: 'Kafka',
        link: '/middleware/mq/kafka/',
        collapsed: true,
        items: [
          { text: 'Kafka 高性能核心原理：顺序写 + Page Cache + 零拷贝 + 分区并行', link: '/middleware/mq/kafka/high-performance' },
          { text: 'Kafka 架构：Broker、Topic、Partition、Replica', link: '/middleware/mq/kafka/architecture' },
          { text: 'Kafka 分区策略：轮询、哈希、时间轮', link: '/middleware/mq/kafka/partition-strategy' },
          { text: 'Kafka 副本机制：Leader Follower ISR', link: '/middleware/mq/kafka/replica' },
          { text: 'Kafka 副本同步原理与故障转移', link: '/middleware/mq/kafka/replica-sync' },
          { text: 'Kafka 消费者组（Consumer Group）与 Rebalance', link: '/middleware/mq/kafka/consumer-group' },
          { text: 'Kafka Rebalance 触发条件与分区分配策略', link: '/middleware/mq/kafka/rebalance' },
          { text: 'Kafka 生产者（Producer）原理：分区、ACK、幂等性、事务', link: '/middleware/mq/kafka/producer' },
          { text: 'Kafka 消息发送模式：同步、异步、异步回调', link: '/middleware/mq/kafka/producer-send' },
          { text: 'Kafka 如何保证消息不丢失：生产者、Broker、消费者', link: '/middleware/mq/kafka/no-data-loss' },
          { text: 'Kafka 如何保证消息不重复消费（幂等性）', link: '/middleware/mq/kafka/idempotency' },
          { text: 'Kafka 消息存储：Segment + Index + 时间索引', link: '/middleware/mq/kafka/message-storage' },
          { text: 'Kafka 日志清理策略：delete vs compact', link: '/middleware/mq/kafka/log-cleanup' },
          { text: 'Kafka 控制器（Controller）：Broker 选举与故障转移', link: '/middleware/mq/kafka/controller' },
          { text: 'Kafka 面试高频问题汇总', link: '/middleware/mq/kafka/interview-summary' },
        ],
      },
      {
        text: 'RabbitMQ',
        link: '/middleware/mq/rabbitmq/',
        collapsed: true,
        items: [
          { text: 'RabbitMQ 核心概念：Exchange、Queue、Binding、RouteKey', link: '/middleware/mq/rabbitmq/core-concept' },
          { text: 'RabbitMQ 交换机类型：Direct、Fanout、Topic、Headers', link: '/middleware/mq/rabbitmq/exchange-type' },
          { text: 'RabbitMQ 架构：Producer → Exchange → Binding → Queue → Consumer', link: '/middleware/mq/rabbitmq/architecture' },
          { text: 'RabbitMQ 消息确认机制：Confirm 与 Return', link: '/middleware/mq/rabbitmq/confirm-return' },
          { text: 'RabbitMQ 消费端确认：ACK 与 NACK', link: '/middleware/mq/rabbitmq/consumer-ack' },
          { text: 'RabbitMQ 消息持久化：交换机、队列、消息', link: '/middleware/mq/rabbitmq/persistence' },
          { text: 'RabbitMQ 死信队列（DLX）与延迟队列', link: '/middleware/mq/rabbitmq/dlx' },
          { text: 'RabbitMQ 集群模式：普通集群 vs 镜像集群 vs 仲裁队列', link: '/middleware/mq/rabbitmq/cluster' },
          { text: 'RabbitMQ 高可用与负载均衡', link: '/middleware/mq/rabbitmq/ha' },
          { text: 'RabbitMQ 与 Kafka 对比与选型', link: '/middleware/mq/rabbitmq/kafka-compare' },
          { text: 'RabbitMQ 面试高频问题汇总', link: '/middleware/mq/rabbitmq/interview-summary' },
        ],
      },
      {
        text: 'RocketMQ',
        link: '/middleware/mq/rocketmq/',
        collapsed: true,
        items: [
          { text: 'RocketMQ 架构：NameServer、Broker、Producer、Consumer', link: '/middleware/mq/rocketmq/architecture' },
          { text: 'RocketMQ 消息类型：普通消息、顺序消息、事务消息、延迟消息', link: '/middleware/mq/rocketmq/message-type' },
          { text: 'RocketMQ 事务消息：半消息与事务状态回查', link: '/middleware/mq/rocketmq/transaction' },
          { text: 'RocketMQ 顺序消息：单 Queue 全局顺序 vs 分区顺序', link: '/middleware/mq/rocketmq/ordered-message' },
          { text: 'RocketMQ 延迟消息实现原理：延迟等级', link: '/middleware/mq/rocketmq/delay-message' },
          { text: 'RocketMQ 高可用：主从复制与 DLeger', link: '/middleware/mq/rocketmq/ha' },
          { text: 'RocketMQ vs Kafka vs RabbitMQ 选型对比', link: '/middleware/mq/rocketmq/compare' },
        ],
      },
    ],
  },
  {
    text: 'RPC 框架',
    link: '/middleware/rpc/',
    items: [
      { text: 'RPC 通信原理：stub、序列化、网络传输', link: '/middleware/rpc/principle' },
      { text: 'RPC vs HTTP vs REST 对比', link: '/middleware/rpc/rpc-vs-http' },
      { text: 'RPC 序列化协议：JSON、Protobuf、Thrift、Hessian、Kryo', link: '/middleware/rpc/serialization' },
      { text: 'Protobuf 原理：IDL 编译器与编解码', link: '/middleware/rpc/protobuf' },
      { text: 'Dubbo vs gRPC vs Thrift 对比', link: '/middleware/rpc/compare' },
      { text: 'gRPC 流式调用：服务端流、客户端流、双向流', link: '/middleware/rpc/grpc-stream' },
      { text: 'RPC 负载均衡：客户端负载均衡 vs 服务端负载均衡', link: '/middleware/rpc/loadbalance' },
      { text: 'RPC 超时控制与重试机制', link: '/middleware/rpc/timeout-retry' },
      { text: 'RPC 链路追踪：OpenTracing 与 SkyWalking', link: '/middleware/rpc/tracing' },
      { text: 'Dubbo SPI 机制与扩展点加载', link: '/middleware/rpc/dubbo-spi' },
    ],
  },
  {
    text: '注册中心',
    link: '/middleware/registry/',
    items: [
      {
        text: 'ZooKeeper',
        link: '/middleware/registry/zookeeper/',
        collapsed: true,
        items: [
          { text: 'ZooKeeper 核心概念：ZNode、版本号、ACL、Watch', link: '/middleware/registry/zookeeper/core' },
          { text: 'ZooKeeper 分布式锁实现：临时顺序节点', link: '/middleware/registry/zookeeper/lock' },
          { text: 'ZooKeeper 集群脑裂问题与过半机制', link: '/middleware/registry/zookeeper/brain-split' },
          { text: 'ZooKeeper 使用场景：配置中心、命名服务、Master 选举', link: '/middleware/registry/zookeeper/use-case' },
        ],
      },
      {
        text: 'Nacos',
        link: '/middleware/registry/nacos/',
        collapsed: true,
        items: [
          { text: 'Nacos 注册中心：服务注册与心跳保活', link: '/middleware/registry/nacos/registry' },
          { text: 'Nacos 配置中心：热更新与多环境隔离', link: '/middleware/registry/nacos/config' },
          { text: 'Nacos 集群一致性：Distro 协议', link: '/middleware/registry/nacos/distro' },
          { text: 'Nacos 选举机制与临时/永久实例', link: '/middleware/registry/nacos/election' },
          { text: 'Nacos vs ZooKeeper vs Consul 对比', link: '/middleware/registry/nacos/compare' },
        ],
      },
      {
        text: 'Eureka',
        link: '/middleware/registry/eureka/',
        collapsed: true,
        items: [
          { text: 'Eureka 架构：服务端、客户端、自我保护机制', link: '/middleware/registry/eureka/eureka' },
          { text: 'Eureka 自我保护机制：心跳超时与阈值', link: '/middleware/registry/eureka/protection' },
          { text: 'Eureka 1.x vs 2.x（已停止维护）与替代方案', link: '/middleware/registry/eureka/deprecated' },
        ],
      },
      {
        text: 'Consul',
        link: '/middleware/registry/consul/',
        collapsed: true,
        items: [
          { text: 'Consul 核心特性：服务发现、健康检查、KV 存储、多数据中心', link: '/middleware/registry/consul/consul' },
          { text: 'Consul vs ZooKeeper vs etcd vs Nacos 对比', link: '/middleware/registry/consul/compare' },
        ],
      },
    ],
  },
  {
    text: 'API 网关',
    link: '/middleware/gateway/',
    items: [
      {
        text: '网关核心功能',
        link: '/middleware/gateway/core/',
        collapsed: true,
        items: [
          { text: 'API 网关核心功能：路由、负载均衡、认证授权、限流熔断、日志监控', link: '/middleware/gateway/core/function' },
          { text: 'API 网关架构设计要点', link: '/middleware/gateway/core/architecture' },
          { text: '网关路由匹配规则：Path、Header、Query 参数路由', link: '/middleware/gateway/core/route-match' },
          { text: '网关过滤器链：Pre 过滤器与 Post 过滤器', link: '/middleware/gateway/core/filter-chain' },
        ],
      },
      {
        text: 'Spring Cloud Gateway',
        link: '/middleware/gateway/sc-gateway/',
        collapsed: true,
        items: [
          { text: 'Spring Cloud Gateway 工作流程：Route、Predicate、Filter', link: '/middleware/gateway/sc-gateway/workflow' },
          { text: 'Spring Cloud Gateway 路由配置与动态路由', link: '/middleware/gateway/sc-gateway/route' },
          { text: 'Spring Cloud Gateway 过滤器：全局过滤器与路由过滤器', link: '/middleware/gateway/sc-gateway/filter' },
          { text: 'Spring Cloud Gateway 限流：RequestRateLimiter 与令牌桶', link: '/middleware/gateway/sc-gateway/rate-limit' },
          { text: 'Spring Cloud Gateway 熔断：Resilience4j 集成', link: '/middleware/gateway/sc-gateway/circuit-breaker' },
          { text: 'Spring Cloud Gateway 与 Zuul 1.x、Zuul 2.x 对比', link: '/middleware/gateway/sc-gateway/vs-zuul' },
        ],
      },
      {
        text: 'Kong',
        link: '/middleware/gateway/kong/',
        collapsed: true,
        items: [
          { text: 'Kong 架构：OpenResty + Nginx + Cassandra/PostgreSQL', link: '/middleware/gateway/kong/architecture' },
          { text: 'Kong 插件体系与常用插件', link: '/middleware/gateway/kong/plugin' },
          { text: 'Kong 服务发现与负载均衡', link: '/middleware/gateway/kong/loadbalance' },
        ],
      },
      { text: '网关选型：Spring Cloud Gateway vs Kong vs Apache APISIX vs Traefik', link: '/middleware/gateway/selection' },
    ],
  },
  {
    text: '搜索引擎',
    link: '/middleware/search/',
    items: [
      {
        text: 'Elasticsearch',
        link: '/middleware/search/es/',
        collapsed: true,
        items: [
          { text: 'Elasticsearch 核心概念：Index、Document、Shard、Replica', link: '/middleware/search/es/core-concept' },
          { text: 'Elasticsearch 架构：Master 节点、数据节点、 coordinating 节点', link: '/middleware/search/es/architecture' },
          { text: '倒排索引原理与分词器（Analyzer）', link: '/middleware/search/es/inverted-index' },
          { text: 'ES 分片策略与副本机制', link: '/middleware/search/es/shard' },
          { text: 'ES 文档 CRUD 与并发控制（乐观锁）', link: '/middleware/search/es/crud' },
          { text: 'ES 搜索原理：Query Phase 与 Fetch Phase', link: '/middleware/search/es/search' },
          { text: 'ES 查询 DSL：match、term、range、bool、嵌套查询', link: '/middleware/search/es/dsl' },
          { text: 'ES 聚合分析：Bucketing、Metric、Pipeline', link: '/middleware/search/es/aggregation' },
          { text: 'ES 索引管理：mapping、settings、alias', link: '/middleware/search/es/index-management' },
          { text: 'ES 分页查询：from/size vs search_after vs scroll', link: '/middleware/search/es/pagination' },
          { text: 'ES 数据同步方案：双写、Logstash、Canal、Debezium', link: '/middleware/search/es/data-sync' },
          { text: 'ES 性能优化：segments 合并、refresh_interval、routing', link: '/middleware/search/es/performance' },
          { text: 'ES 面试高频问题汇总', link: '/middleware/search/es/interview-summary' },
          { text: 'Solr 简介与对比', link: '/middleware/search/es/solr-compare' },
        ],
      },
      {
        text: 'Logstash',
        link: '/middleware/search/logstash/',
        collapsed: true,
        items: [
          { text: 'Logstash 工作流程：Input → Filter → Output 管道模型', link: '/middleware/search/logstash/pipeline' },
          { text: 'Logstash Input 插件：File、Beats、JDBC、Kafka、HTTP', link: '/middleware/search/logstash/input' },
          { text: 'Logstash Filter 插件：Grok 正则解析、JSON 解析、Date 日期转换、Mutate 数据转换', link: '/middleware/search/logstash/filter' },
          { text: 'Logstash 多行处理：multiline 与 codec 编码器', link: '/middleware/search/logstash/multiline' },
          { text: 'Logstash 性能优化：线程模型、队列缓冲区、Filter 顺序调优', link: '/middleware/search/logstash/performance' },
          { text: 'Logstash 集群部署与配置文件管理', link: '/middleware/search/logstash/cluster' },
        ],
      },
      {
        text: 'Kibana',
        link: '/middleware/search/kibana/',
        collapsed: true,
        items: [
          { text: 'Kibana 核心功能：可视化大盘（Dashboard）、探索数据（Discover）、图表绘制（Visualize）', link: '/middleware/search/kibana/core-function' },
          { text: 'Kibana 查询语法：KQL（Kibana Query Language）与 Lucene', link: '/middleware/search/kibana/kql' },
          { text: 'Kibana 可视化类型：折线图、柱状图、饼图、热力图、地图', link: '/middleware/search/kibana/visualization' },
          { text: 'Kibana Timelion 时序数据分析与趋势预测', link: '/middleware/search/kibana/timelion' },
          { text: 'Kibana 告警规则与 threshold alerting', link: '/middleware/search/kibana/alerting' },
          { text: 'Kibana 安全功能：空间（Space）、角色、视图级别权限控制', link: '/middleware/search/kibana/security' },
          { text: 'Kibana 仪表盘分享与嵌入式可视化', link: '/middleware/search/kibana/share' },
        ],
      },
      {
        text: 'ELK 综合与 Beats',
        link: '/middleware/search/elk/',
        collapsed: true,
        items: [
          { text: 'ELK Stack 整体架构与数据流', link: '/middleware/search/elk/architecture' },
          { text: 'Filebeat 轻量级日志采集：Prospector、Harvester、多行日志处理', link: '/middleware/search/elk/filebeat' },
          { text: 'Metricbeat 系统与服务指标采集', link: '/middleware/search/elk/metricbeat' },
          { text: 'Heartbeat 站点与端口健康检测', link: '/middleware/search/elk/heartbeat' },
          { text: 'Packetbeat 网络流量协议分析', link: '/middleware/search/elk/packetbeat' },
          { text: 'ELK + Kafka 组合：日志收集→缓冲→消费的架构设计', link: '/middleware/search/elk/kafka-integration' },
          { text: 'ELK 日志收集最佳实践：日志规范、字段命名、索引生命周期管理（ILM）', link: '/middleware/search/elk/best-practice' },
        ],
      },
    ],
  },
  {
    text: '其他中间件',
    link: '/middleware/other/',
    items: [
      {
        text: '工作流引擎',
        link: '/middleware/other/workflow/',
        collapsed: true,
        items: [
          {
            text: '工作流基础',
            link: '/middleware/other/workflow/basic/',
            collapsed: true,
            items: [
              { text: '工作流核心概念：流程定义、流程实例、任务、流程变量', link: '/middleware/other/workflow/basic/concept' },
              { text: 'BPMN 2.0 规范：流程设计元素与建模规范', link: '/middleware/other/workflow/basic/bpmn' },
              { text: '工作流引擎选型：Flowable vs Camunda vs Activiti', link: '/middleware/other/workflow/basic/compare' },
              { text: '工作流应用场景：审批流、订单处理、自动化业务流程', link: '/middleware/other/workflow/basic/use-case' },
            ],
          },
          {
            text: 'Flowable',
            link: '/middleware/other/workflow/flowable/',
            collapsed: true,
            items: [
              { text: 'Flowable 架构：六个核心引擎（Process、BVM、Case、DMN、Form、Content）', link: '/middleware/other/workflow/flowable/architecture' },
              { text: 'Flowable 与 Activiti 的历史渊源与主要区别', link: '/middleware/other/workflow/flowable/vs-activiti' },
              { text: 'Flowable 流程定义：部署、激活、挂起、删除', link: '/middleware/other/workflow/flowable/deployment' },
              { text: 'Flowable 用户任务：签收任务、完成任务、任务代理与委派', link: '/middleware/other/workflow/flowable/task' },
              { text: 'Flowable 网关：排他网关、并行网关、包容网关、事件网关', link: '/middleware/other/workflow/flowable/gateway' },
              { text: 'Flowable 流程变量与执行上下文', link: '/middleware/other/workflow/flowable/variable' },
              { text: 'Flowable 会签（Multi-Instance）：串行会签与并行会签实现', link: '/middleware/other/workflow/flowable/multi-instance' },
              { text: 'Flowable 子流程：嵌入式子流程、调用活动（Call Activity）', link: '/middleware/other/workflow/flowable/subprocess' },
              { text: 'Flowable 事件监听：执行监听器与任务监听器', link: '/middleware/other/workflow/flowable/listener' },
              { text: 'Flowable 异步执行：作业与定时作业（Job & Timer）', link: '/middleware/other/workflow/flowable/async' },
              { text: 'Flowable Spring Boot 集成与自动配置', link: '/middleware/other/workflow/flowable/springboot' },
              { text: 'Flowable 数据库表结构与核心表说明', link: '/middleware/other/workflow/flowable/table' },
              { text: 'Flowable 高级特性：候选用户、组任务、权限控制', link: '/middleware/other/workflow/flowable/identity' },
            ],
          },
          {
            text: 'Camunda',
            link: '/middleware/other/workflow/camunda/',
            collapsed: true,
            items: [
              { text: 'Camunda 架构：引擎、REST API、Web 应用（Camunda Web）', link: '/middleware/other/workflow/camunda/architecture' },
              { text: 'Camunda BPMN 流程设计与 DMN 决策表', link: '/middleware/other/workflow/camunda/dmn' },
              { text: 'Camunda 与 Spring Boot 集成', link: '/middleware/other/workflow/camunda/springboot' },
              { text: 'Camunda vs Flowable 功能对比', link: '/middleware/other/workflow/camunda/compare' },
            ],
          },
          { text: '工作流面试高频问题汇总', link: '/middleware/other/workflow/interview-summary' },
        ],
      },
      {
        text: 'ShardingSphere',
        link: '/middleware/other/shardingsphere/',
        collapsed: true,
        items: [
          { text: 'ShardingSphere 架构：Sharding-JDBC vs Sharding-Proxy', link: '/middleware/other/shardingsphere/architecture' },
          { text: 'ShardingSphere 数据分片：分片键、分片算法（哈希/范围/时间）', link: '/middleware/other/shardingsphere/sharding' },
          { text: 'ShardingSphere 读写分离配置', link: '/middleware/other/shardingsphere/read-write' },
          { text: 'ShardingSphere 分布式事务：XA 与 BASE 柔性事务', link: '/middleware/other/shardingsphere/transaction' },
          { text: 'ShardingSphere 分布式 ID 生成', link: '/middleware/other/shardingsphere/distributed-id' },
          { text: 'ShardingSphere 编排治理：配置中心与注册中心集成', link: '/middleware/other/shardingsphere/governance' },
        ],
      },
      {
        text: 'Sentinel',
        link: '/middleware/other/sentinel/',
        collapsed: true,
        items: [
          { text: 'Sentinel 核心概念：资源、规则、插槽链', link: '/middleware/other/sentinel/core-concept' },
          { text: 'Sentinel 流量控制：QPS 限流与并发线程数限流', link: '/middleware/other/sentinel/flow-control' },
          { text: 'Sentinel 熔断降级：RT、异常比例、异常数熔断策略', link: '/middleware/other/sentinel/degrade' },
          { text: 'Sentinel 系统自适应限流', link: '/middleware/other/sentinel/system-adaptive' },
          { text: 'Sentinel 注解支持与 Dubbo 集成', link: '/middleware/other/sentinel/annotation' },
          { text: 'Sentinel 与 Hystrix 对比', link: '/middleware/other/sentinel/hystrix-compare' },
        ],
      },
      {
        text: 'Canal',
        link: '/middleware/other/canal/',
        collapsed: true,
        items: [
          { text: 'Canal 工作原理：伪装成 MySQL Slave 接收 binlog', link: '/middleware/other/canal/principle' },
          { text: 'Canal 订阅模式与增量同步配置', link: '/middleware/other/canal/subscribe' },
          { text: 'Canal 集群部署与高可用', link: '/middleware/other/canal/ha' },
          { text: 'Canal 应用场景：数据库实时同步、ES 索引更新、缓存更新', link: '/middleware/other/canal/use-case' },
          { text: 'Canal vs Maxwell vs Debezium 对比', link: '/middleware/other/canal/compare' },
        ],
      },
      {
        text: '分布式任务调度',
        link: '/middleware/other/scheduler/',
        collapsed: true,
        items: [
          {
            text: '任务调度基础',
            link: '/middleware/other/scheduler/basic/',
            collapsed: true,
            items: [
              { text: '任务调度核心概念：触发器、Job、Scheduler、线程池', link: '/middleware/other/scheduler/basic/concept' },
              { text: '单机任务调度 vs 分布式任务调度', link: '/middleware/other/scheduler/basic/single-vs-distributed' },
              { text: '定时任务常见问题：重复执行、时钟漂移、任务堆积', link: '/middleware/other/scheduler/basic/common-problem' },
              { text: 'Quartz vs XXL-Job vs Elastic-Job 选型对比', link: '/middleware/other/scheduler/basic/compare' },
            ],
          },
          {
            text: 'Quartz',
            link: '/middleware/other/scheduler/quartz/',
            collapsed: true,
            items: [
              { text: 'Quartz 核心概念：Scheduler、Trigger、Job、JobDetail', link: '/middleware/other/scheduler/quartz/core' },
              { text: 'Quartz Trigger 类型：Simple Trigger 与 Cron Trigger', link: '/middleware/other/scheduler/quartz/trigger' },
              { text: 'Quartz Job 状态与持久化：Volatile、Stateful、PersistJobDataAfterExecution', link: '/middleware/other/scheduler/quartz/job-state' },
              { text: 'Quartz Spring Boot 集成：@DisallowConcurrentExecution 与 @PersistJobDataAfterExecution', link: '/middleware/other/scheduler/quartz/springboot' },
              { text: 'Quartz 集群原理：JDBC JobStore 与分布式锁', link: '/middleware/other/scheduler/quartz/cluster' },
              { text: 'Quartz Misfire 策略与重试机制', link: '/middleware/other/scheduler/quartz/misfire' },
            ],
          },
          {
            text: 'XXL-Job',
            link: '/middleware/other/scheduler/xxljob/',
            collapsed: true,
            items: [
              { text: 'XXL-Job 架构：调度中心（Admin）与执行器（Executor）', link: '/middleware/other/scheduler/xxljob/architecture' },
              { text: 'XXL-Job 任务类型：Bean 模式、GLUE 模式、Script 脚本', link: '/middleware/other/scheduler/xxljob/task-type' },
              { text: 'XXL-Job 路由策略：FIRST、LAST、ROUND、CONSISTENT_HASH、LEAST_LOADED', link: '/middleware/other/scheduler/xxljob/route' },
              { text: 'XXL-Job 任务超时控制、失败重试与阻塞处理策略', link: '/middleware/other/scheduler/xxljob/retry' },
              { text: 'XXL-Job 任务编排：子任务、任务依赖与执行顺序', link: '/middleware/other/scheduler/xxljob/chaining' },
              { text: 'XXL-Job GLUE 代码开发模式与热更新原理', link: '/middleware/other/scheduler/xxljob/glue' },
              { text: 'XXL-Job 高可用与调度中心集群', link: '/middleware/other/scheduler/xxljob/ha' },
            ],
          },
          {
            text: 'ElasticJob',
            link: '/middleware/other/scheduler/elasticjob/',
            collapsed: true,
            items: [
              { text: 'ElasticJob 架构：LiteJob 与 CloudJob 两种部署模式', link: '/middleware/other/scheduler/elasticjob/architecture' },
              { text: 'ElasticJob 分片原理：Sharding + ShardingItemParameters', link: '/middleware/other/scheduler/elasticjob/sharding' },
              { text: 'ElasticJob 作业类型：Simple、Dataflow、Script', link: '/middleware/other/scheduler/elasticjob/job-type' },
              { text: 'ElasticJob 作业监听器：ElasticJobListener 与 ExecutionListener', link: '/middleware/other/scheduler/elasticjob/listener' },
              { text: 'ElasticJob 作业配置：JobConfiguration 与 Spring Boot 集成', link: '/middleware/other/scheduler/elasticjob/config' },
              { text: 'ElasticJob-Cloud 与 Mesos 的结合', link: '/middleware/other/scheduler/elasticjob/cloud' },
              { text: 'ElasticJob-Lite 注册中心原理：ZooKeeper 节点监听', link: '/middleware/other/scheduler/elasticjob/registry' },
              { text: 'ElasticJob vs XXL-Job vs Quartz 功能对比', link: '/middleware/other/scheduler/elasticjob/compare' },
            ],
          },
          { text: '任务调度面试高频问题汇总', link: '/middleware/other/scheduler/interview-summary' },
        ],
      },
      { text: 'SLS 日志服务', link: '/middleware/other/sls' },
      { text: 'SkyWalking 链路追踪', link: '/middleware/other/skywalking' },
      { text: 'Apollo 配置中心架构', link: '/middleware/other/apollo' },
    ],
  },
]
