export const middlewareSidebar = [
  {
    text: '消息队列',
    link: '/middleware/mq/',
    items: [
      {
        text: '消息队列基础',
        link: '/middleware/mq/common/',
        collapsed: true,
        items: [
          { text: '消息队列核心概念', link: '/middleware/mq/common/core-concept' },
          { text: '消息队列应用场景', link: '/middleware/mq/common/use-case' },
          { text: '消息队列架构设计要点', link: '/middleware/mq/common/architecture-design' },
          { text: 'Kafka MQ 选型指南', link: '/middleware/mq/common/select' },
          { text: '如何保证消息的顺序性？', link: '/middleware/mq/common/ordering' },
          { text: '如何保证消息的幂等性消费？', link: '/middleware/mq/common/idempotent-consume' },
          { text: '消息积压处理方案', link: '/middleware/mq/common/message-backlog' },
          { text: '消息重试机制与死信队列', link: '/middleware/mq/common/retry-dlq' },
          { text: '消息队列面试高频问题汇总', link: '/middleware/mq/common/interview-summary' },
        ],
      },
      {
        text: 'Kafka',
        link: '/middleware/mq/kafka/',
        collapsed: true,
        items: [
          { text: 'Kafka 高性能核心原理', link: '/middleware/mq/kafka/high-performance' },
          { text: 'Kafka 架构', link: '/middleware/mq/kafka/architecture' },
          { text: 'Kafka 分区策略', link: '/middleware/mq/kafka/partition-strategy' },
          { text: 'Kafka 副本机制', link: '/middleware/mq/kafka/replica' },
          { text: 'Kafka 副本同步原理', link: '/middleware/mq/kafka/replica-sync' },
          { text: 'Kafka 消费者组', link: '/middleware/mq/kafka/consumer-group' },
          { text: 'Kafka Rebalance 机制', link: '/middleware/mq/kafka/rebalance' },
          { text: 'Kafka 生产者原理', link: '/middleware/mq/kafka/producer' },
          { text: 'Kafka 消息发送模式', link: '/middleware/mq/kafka/producer-send' },
          { text: 'Kafka 消息不丢失方案', link: '/middleware/mq/kafka/no-data-loss' },
          { text: 'Kafka 消息幂等性', link: '/middleware/mq/kafka/idempotency' },
          { text: 'Kafka 消息存储机制', link: '/middleware/mq/kafka/message-storage' },
          { text: 'Kafka 日志清理策略', link: '/middleware/mq/kafka/log-cleanup' },
          { text: 'Kafka 控制器原理', link: '/middleware/mq/kafka/controller' },
          { text: 'Kafka 面试高频问题汇总', link: '/middleware/mq/kafka/interview-summary' },
        ],
      },
      {
        text: 'RabbitMQ',
        link: '/middleware/mq/rabbitmq/',
        collapsed: true,
        items: [
          { text: 'RabbitMQ 核心概念', link: '/middleware/mq/rabbitmq/core-concept' },
          { text: 'RabbitMQ 交换机类型', link: '/middleware/mq/rabbitmq/exchange-type' },
          { text: 'RabbitMQ 架构', link: '/middleware/mq/rabbitmq/architecture' },
          { text: 'RabbitMQ 消息确认机制', link: '/middleware/mq/rabbitmq/confirm-return' },
          { text: 'RabbitMQ 消费端确认', link: '/middleware/mq/rabbitmq/consumer-ack' },
          { text: 'RabbitMQ 消息持久化', link: '/middleware/mq/rabbitmq/persistence' },
          { text: 'RabbitMQ 死信与延迟队列', link: '/middleware/mq/rabbitmq/dlx' },
          { text: 'RabbitMQ 集群模式', link: '/middleware/mq/rabbitmq/cluster' },
          { text: 'RabbitMQ 与 Kafka 对比与选型', link: '/middleware/mq/rabbitmq/kafka-compare' },
          { text: 'RabbitMQ 面试高频问题汇总', link: '/middleware/mq/rabbitmq/interview-summary' },
        ],
      },
      {
        text: 'RocketMQ',
        link: '/middleware/mq/rocketmq/',
        collapsed: true,
        items: [
          { text: 'RocketMQ 架构', link: '/middleware/mq/rocketmq/architecture' },
          { text: 'RocketMQ 消息类型', link: '/middleware/mq/rocketmq/message-type' },
          { text: 'RocketMQ 事务消息', link: '/middleware/mq/rocketmq/transaction' },
          { text: 'RocketMQ 顺序消息', link: '/middleware/mq/rocketmq/ordered-message' },
          { text: 'RocketMQ 延迟消息', link: '/middleware/mq/rocketmq/delay-message' },
          { text: 'RocketMQ 高可用', link: '/middleware/mq/rocketmq/ha' },
          { text: 'MQ 选型对比', link: '/middleware/mq/rocketmq/compare' },
        ],
      },
    ],
  },
  {
    text: 'RPC 框架',
    link: '/middleware/rpc/',
    items: [
      { text: 'RPC 通信原理', link: '/middleware/rpc/principle' },
      { text: 'RPC vs HTTP vs REST', link: '/middleware/rpc/rpc-vs-http' },
      { text: 'RPC 序列化协议对比', link: '/middleware/rpc/serialization' },
      { text: 'Protobuf 原理', link: '/middleware/rpc/protobuf' },
      { text: 'gRPC 流式调用', link: '/middleware/rpc/grpc-stream' },
      { text: 'RPC 负载均衡', link: '/middleware/rpc/loadbalance' },
      { text: 'RPC 链路追踪', link: '/middleware/rpc/tracing' },
    ],
  },
  {
    text: '注册中心',
    link: '/middleware/registry/',
    items: [
      {
        text: 'ZooKeeper',
        link: '/middleware/registry/zookeeper/',
        collapsed: true,
        items: [
          { text: 'ZooKeeper 核心概念', link: '/middleware/registry/zookeeper/core' },
          { text: 'ZooKeeper 分布式锁', link: '/middleware/registry/zookeeper/lock' },
          { text: 'ZooKeeper 脑裂问题', link: '/middleware/registry/zookeeper/brain-split' },
          { text: 'ZooKeeper 使用场景', link: '/middleware/registry/zookeeper/use-case' },
        ],
      },
      {
        text: 'Nacos',
        link: '/middleware/registry/nacos/',
        collapsed: true,
        items: [
          { text: 'Nacos 注册中心', link: '/middleware/registry/nacos/registry' },
          { text: 'Nacos 配置中心', link: '/middleware/registry/nacos/config' },
          { text: 'Nacos 集群一致性', link: '/middleware/registry/nacos/distro' },
          { text: '注册中心选型对比', link: '/middleware/registry/nacos/compare' },
        ],
      },
      {
        text: 'Eureka',
        link: '/middleware/registry/eureka/',
        collapsed: true,
        items: [
          { text: 'Eureka 架构', link: '/middleware/registry/eureka/eureka' },
          { text: 'Eureka 自我保护机制', link: '/middleware/registry/eureka/protection' },
        ],
      },
      {
        text: 'Consul',
        link: '/middleware/registry/consul/',
        collapsed: true,
        items: [
          { text: 'Consul 核心特性', link: '/middleware/registry/consul/consul' },
          { text: '服务注册中心对比', link: '/middleware/registry/consul/compare' },
        ],
      },
    ],
  },
  {
    text: 'API 网关',
    link: '/middleware/gateway/',
    items: [
      {
        text: '网关核心功能',
        link: '/middleware/gateway/core/',
        collapsed: true,
        items: [
          { text: 'API 网关核心功能', link: '/middleware/gateway/core/function' },
          { text: 'API 网关架构设计', link: '/middleware/gateway/core/architecture' },
          { text: '网关路由匹配规则', link: '/middleware/gateway/core/route-match' },
          { text: '网关过滤器链', link: '/middleware/gateway/core/filter-chain' },
        ],
      },
      {
        text: 'Spring Cloud Gateway',
        link: '/middleware/gateway/sc-gateway/',
        collapsed: true,
        items: [
          { text: 'Gateway 工作流程', link: '/middleware/gateway/sc-gateway/workflow' },
          { text: 'Spring Cloud Gateway 路由配置', link: '/middleware/gateway/sc-gateway/route' },
          { text: 'Spring Cloud Gateway 过滤器', link: '/middleware/gateway/sc-gateway/filter' },
          { text: 'Spring Cloud Gateway 限流', link: '/middleware/gateway/sc-gateway/rate-limit' },
          { text: 'Spring Cloud Gateway 熔断', link: '/middleware/gateway/sc-gateway/circuit-breaker' },
        ],
      },
      {
        text: 'Kong',
        link: '/middleware/gateway/kong/',
        collapsed: true,
        items: [
          { text: 'Kong 架构', link: '/middleware/gateway/kong/architecture' },
          { text: 'Kong 插件体系', link: '/middleware/gateway/kong/plugin' },
        ],
      },
          { text: '网关选型对比', link: '/middleware/gateway/selection' },
    ],
  },
  {
    text: '搜索引擎',
    link: '/middleware/search/',
    items: [
      {
        text: 'Elasticsearch',
        link: '/middleware/search/es/',
        collapsed: true,
        items: [
          { text: 'Elasticsearch 核心概念', link: '/middleware/search/es/core-concept' },
          { text: 'Elasticsearch 架构', link: '/middleware/search/es/architecture' },
          { text: 'ES 搜索原理', link: '/middleware/search/es/search' },
          { text: 'ES 查询 DSL', link: '/middleware/search/es/dsl' },
          { text: 'ES 聚合分析', link: '/middleware/search/es/aggregation' },
          { text: 'ES 索引管理', link: '/middleware/search/es/index-management' },
          { text: 'ES 分页查询', link: '/middleware/search/es/pagination' },
          { text: 'ES 数据同步方案', link: '/middleware/search/es/data-sync' },
          { text: 'ES 性能优化', link: '/middleware/search/es/performance' },
          { text: 'ES 面试高频问题汇总', link: '/middleware/search/es/interview-summary' },
          { text: 'Solr 简介与对比', link: '/middleware/search/es/solr-compare' },
        ],
      },
      {
        text: 'Logstash',
        link: '/middleware/search/logstash/',
        collapsed: true,
        items: [
          { text: 'Logstash 工作流程', link: '/middleware/search/logstash/pipeline' },
          { text: 'Logstash Input 插件', link: '/middleware/search/logstash/input' },
          { text: 'Logstash Filter 插件', link: '/middleware/search/logstash/filter' },
          { text: 'Logstash 多行处理', link: '/middleware/search/logstash/multiline' },
          { text: 'Logstash 性能优化', link: '/middleware/search/logstash/performance' },
          { text: 'Logstash 集群部署', link: '/middleware/search/logstash/cluster' },
        ],
      },
      {
        text: 'Kibana',
        link: '/middleware/search/kibana/',
        collapsed: true,
        items: [
          { text: 'Kibana 核心功能', link: '/middleware/search/kibana/core-function' },
          { text: 'Kibana 查询语法', link: '/middleware/search/kibana/kql' },
          { text: 'Kibana 可视化类型', link: '/middleware/search/kibana/visualization' },
          { text: 'Kibana 告警规则', link: '/middleware/search/kibana/alerting' },
          { text: 'Kibana 安全功能', link: '/middleware/search/kibana/security' },
          { text: 'Kibana 仪表盘分享', link: '/middleware/search/kibana/share' },
        ],
      },
      {
        text: 'ELK 综合与 Beats',
        link: '/middleware/search/elk/',
        collapsed: true,
        items: [
          { text: 'ELK Stack 整体架构', link: '/middleware/search/elk/architecture' },
          { text: 'Filebeat 轻量级日志采集', link: '/middleware/search/elk/filebeat' },
          { text: 'Metricbeat 指标采集', link: '/middleware/search/elk/metricbeat' },
          { text: 'Heartbeat 健康检测', link: '/middleware/search/elk/heartbeat' },
          { text: 'ELK + Kafka 组合', link: '/middleware/search/elk/kafka-integration' },
          { text: 'ELK 日志收集最佳实践', link: '/middleware/search/elk/best-practice' },
        ],
      },
    ],
  },
  {
    text: '其他中间件',
    link: '/middleware/other/',
    items: [
      {
        text: '工作流引擎',
        link: '/middleware/other/workflow/',
        collapsed: true,
        items: [
          {
            text: '工作流基础',
            link: '/middleware/other/workflow/basic/',
            collapsed: true,
            items: [
          { text: '工作流核心概念', link: '/middleware/other/workflow/basic/concept' },
          { text: 'BPMN 2.0 规范', link: '/middleware/other/workflow/basic/bpmn' },
          { text: '工作流引擎选型', link: '/middleware/other/workflow/basic/compare' },
            ],
          },
          {
            text: 'Flowable',
            link: '/middleware/other/workflow/flowable/',
            collapsed: true,
            items: [
          { text: 'Flowable 架构', link: '/middleware/other/workflow/flowable/architecture' },
          { text: 'Flowable 与 Activiti 对比', link: '/middleware/other/workflow/flowable/vs-activiti' },
          { text: 'Flowable 流程定义', link: '/middleware/other/workflow/flowable/deployment' },
          { text: 'Flowable 用户任务', link: '/middleware/other/workflow/flowable/task' },
          { text: 'Flowable 网关类型', link: '/middleware/other/workflow/flowable/gateway' },
          { text: 'Flowable 流程变量', link: '/middleware/other/workflow/flowable/variable' },
          { text: 'Flowable 会签实现', link: '/middleware/other/workflow/flowable/multi-instance' },
          { text: 'Flowable 子流程', link: '/middleware/other/workflow/flowable/subprocess' },
          { text: 'Flowable 事件监听', link: '/middleware/other/workflow/flowable/listener' },
          { text: 'Flowable 异步执行', link: '/middleware/other/workflow/flowable/async' },
          { text: 'Flowable Spring Boot 集成', link: '/middleware/other/workflow/flowable/springboot' },
          { text: 'Flowable 数据库表结构', link: '/middleware/other/workflow/flowable/table' },
            ],
          },
          {
            text: 'Camunda',
            link: '/middleware/other/workflow/camunda/',
            collapsed: true,
            items: [
          { text: 'Camunda 架构', link: '/middleware/other/workflow/camunda/architecture' },
          { text: 'Camunda BPMN 与 DMN', link: '/middleware/other/workflow/camunda/dmn' },
          { text: 'Camunda Spring Boot 集成', link: '/middleware/other/workflow/camunda/springboot' },
            ],
          },
          { text: '工作流面试高频问题汇总', link: '/middleware/other/workflow/interview-summary' },
        ],
      },
      {
        text: 'ShardingSphere',
        link: '/middleware/other/shardingsphere/',
        collapsed: true,
        items: [
          { text: 'ShardingSphere 架构', link: '/middleware/other/shardingsphere/architecture' },
          { text: 'ShardingSphere 数据分片', link: '/middleware/other/shardingsphere/sharding' },
          { text: 'ShardingSphere 分布式事务', link: '/middleware/other/shardingsphere/transaction' },
          { text: 'ShardingSphere 编排治理', link: '/middleware/other/shardingsphere/governance' },
        ],
      },
      {
        text: 'Sentinel',
        link: '/middleware/other/sentinel/',
        collapsed: true,
        items: [
          { text: 'Sentinel 核心概念', link: '/middleware/other/sentinel/core-concept' },
          { text: 'Sentinel 流量控制', link: '/middleware/other/sentinel/flow-control' },
          { text: 'Sentinel 熔断降级', link: '/middleware/other/sentinel/degrade' },
          { text: 'Sentinel 系统自适应限流', link: '/middleware/other/sentinel/system-adaptive' },
          { text: 'Sentinel 注解支持', link: '/middleware/other/sentinel/annotation' },
        ],
      },
      {
        text: 'Canal',
        link: '/middleware/other/canal/',
        collapsed: true,
        items: [
          { text: 'Canal 工作原理', link: '/middleware/other/canal/principle' },
          { text: 'Canal 订阅模式', link: '/middleware/other/canal/subscribe' },
          { text: 'Canal 集群部署', link: '/middleware/other/canal/ha' },
        ],
      },
      {
        text: '分布式任务调度',
        link: '/middleware/other/scheduler/',
        collapsed: true,
        items: [
          {
            text: '任务调度基础',
            link: '/middleware/other/scheduler/basic/',
            collapsed: true,
            items: [
          { text: '任务调度核心概念', link: '/middleware/other/scheduler/basic/concept' },
          { text: '单机 vs 分布式调度', link: '/middleware/other/scheduler/basic/single-vs-distributed' },
          { text: '定时任务常见问题', link: '/middleware/other/scheduler/basic/common-problem' },
            ],
          },
          {
            text: 'Quartz',
            link: '/middleware/other/scheduler/quartz/',
            collapsed: true,
            items: [
          { text: 'Quartz 核心概念', link: '/middleware/other/scheduler/quartz/core' },
          { text: 'Quartz Trigger 类型', link: '/middleware/other/scheduler/quartz/trigger' },
          { text: 'Quartz Job 状态与持久化', link: '/middleware/other/scheduler/quartz/job-state' },
          { text: 'Quartz Spring Boot 集成', link: '/middleware/other/scheduler/quartz/springboot' },
          { text: 'Quartz 集群原理', link: '/middleware/other/scheduler/quartz/cluster' },
            ],
          },
          {
            text: 'XXL-Job',
            link: '/middleware/other/scheduler/xxljob/',
            collapsed: true,
            items: [
          { text: 'XXL-Job 架构', link: '/middleware/other/scheduler/xxljob/architecture' },
          { text: 'XXL-Job 任务类型', link: '/middleware/other/scheduler/xxljob/task-type' },
          { text: 'XXL-Job 路由策略', link: '/middleware/other/scheduler/xxljob/route' },
          { text: 'XXL-Job 任务超时与重试', link: '/middleware/other/scheduler/xxljob/retry' },
          { text: 'XXL-Job 任务编排', link: '/middleware/other/scheduler/xxljob/chaining' },
          { text: 'XXL-Job GLUE 模式', link: '/middleware/other/scheduler/xxljob/glue' },
            ],
          },
          {
            text: 'ElasticJob',
            link: '/middleware/other/scheduler/elasticjob/',
            collapsed: true,
            items: [
          { text: 'ElasticJob 架构', link: '/middleware/other/scheduler/elasticjob/architecture' },
          { text: 'ElasticJob 分片原理', link: '/middleware/other/scheduler/elasticjob/sharding' },
          { text: 'ElasticJob 作业类型', link: '/middleware/other/scheduler/elasticjob/job-type' },
          { text: 'ElasticJob 作业监听器', link: '/middleware/other/scheduler/elasticjob/listener' },
          { text: 'ElasticJob 作业配置', link: '/middleware/other/scheduler/elasticjob/config' },
          { text: 'ElasticJob 注册中心原理', link: '/middleware/other/scheduler/elasticjob/registry' },
            ],
          },
          { text: '任务调度面试高频问题汇总', link: '/middleware/other/scheduler/interview-summary' },
        ],
      },
      { text: 'SLS 日志服务', link: '/middleware/other/sls' },
      { text: 'SkyWalking 链路追踪', link: '/middleware/other/skywalking' },
      { text: 'Apollo 配置中心架构', link: '/middleware/other/apollo' },
    ],
  },
]
